### ISSUE TITLE
List[T] is not faithful representation of PG ARRAY

### ISSUE THREAD

**Issue by strelec** [tminglei/slick-pg#103]
Currently, your code only works for `List`-s of something. Since the list has only prepend efficient O(1) and append in O(n), I conclude it is not a good data type to represent postgres ARRAY datatype.

Suggested fixes:

a) Switch to `Vector` from `List`.
b) Make the code work for any `Seq` or even `Traversable` (so you could even use things like `Set`).

I propose the later.

**Comment by btd** [comment]
Thanks, it worked. But i have question regarding plain sql queries support. Assume i have class:
```
case class User(emails: Seq[String])
// and if i have some plain sql query
val query = ...
```
So question is how should i define GetResult mapping? By idea i should use `nextObject`, but how i can map this AnyRef object to my column type?

**Comment by tminglei** [comment]
Hi @btd, array support for Plain SQL, you can check use cases [here](https://github.com/tminglei/slick-pg/blob/slick2/src/test/scala/com/github/tminglei/slickpg/PgArraySupportTest.scala#L157).

**Comment by btd** [comment]
@tminglei that works perfect. Thanks for the great work.

**Comment by schmitch** [comment]
@tminglei how does it work? 
I get always:

```could not find implicit value for parameter f: slick.jdbc.GetResult[Option[List[String]]]```

**Comment by tminglei** [comment]
Hi @schmitch, can you file a new issue? And pls provide more details, including your customized postgres driver, your usage codes, error details, etc.

_Array support is works ok for a long time, so your problem should be related to your environment._
