### ISSUE TITLE
JSONB Support for Postgres 9.4

### ISSUE THREAD

**Issue by mdedetrich** [tminglei/slick-pg#120]
For `postgres-9.4`, `JSONB` has been added (its essentially a binary representation of `JSON`, and should be used in all cases as its performance characteristics are superior to standard `JSON`)

Is `JSONB` supported, and if not, when should we expect it to be implemented?

**Comment by tminglei** [comment]
Hi @mdedetrich I just implemented it on branch [`json94`](https://github.com/tminglei/slick-pg/tree/json94). Related PR is #121.

_But now it has a little problem: it can't pass travis ci testing, since postgres 9.4 is not supported by travis ci yet. :)_

**Comment by mdedetrich** [comment]
Cool thanks, will check it out locally?

**Comment by tminglei** [comment]
@mdedetrich it's already released, you can use `slick-pg` `v0.8.1` to experience it. :)

**Comment by mdedetrich** [comment]
Cheers!
