### ISSUE TITLE
Can we add support for json4s.jackson?

### ISSUE THREAD

**Issue by mlvn23** [tminglei/slick-pg#123]
I tried overriding the jsonMethods using the jackson, but it didn't work due to incompatible types.

Error:(46, 18) overriding value jsonMethods in trait PgJson4sSupport of type org.json4s.JsonMethods[CustomPostgresDriverTrait.this.DOCType];
 value jsonMethods has incompatible type
    override val jsonMethods = org.json4s.jackson.JsonMethods
                 ^

**Comment by tminglei** [comment]
Hi @mlvn23 to keep consistent, you need specify both `jsonMethods ` and `DOCType` at the same time. For details, you can check the test [codes](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/addon/PgJson4sSupportTest.scala).

**Comment by mlvn23** [comment]
@tminglei, thanks for the pointers. I got it to work with:

```
    type DOCType = JValue
    override val jsonMethods = org.json4s.jackson.JsonMethods
```

Thank you for sharing your work. Keep it up!
