### ISSUE TITLE
querying DateTime fields

### ISSUE THREAD

**Issue by hmvien** [tminglei/slick-pg#124]
Hi, first of all I would like to say great work on slick-pg extension! It made working with hstore datatype much easier. 

I am currently running into issue querying DateTime. It wasn't very clear from the test that your extension supports date range query. I would like to query my table given a start and end date; is this possible with slick-pg? Thanks

**Comment by tminglei** [comment]
Hi @hmvien are you mean querying `timestamp range`?

**Comment by hmvien** [comment]
Yes, specifically, I would like to do something like
```
tableQuery.filter(_.date >= DateTime.now.minusDays(1))
```

**Comment by tminglei** [comment]
_Well, you're not using `timestamp` `Range` type._

You code should work. Do you use `joda-time`, and the column's scala type is `jada-time` DateTime?

**Comment by magicknot** [comment]
According to [supported Date/Time Oper/Functions](https://github.com/tminglei/slick-pg/tree/master/core/src/main/scala/com/github/tminglei/slickpg/date) `>=` should not work, or am I missing something?

**Comment by tminglei** [comment]
Slick has built-in support for '>=', so I needn't make another one _:)_

**Comment by magicknot** [comment]
Yes :stuck_out_tongue: I deleted my comment because I just realised that after pressing the "Comment" button.

**Comment by tminglei** [comment]
:stuck_out_tongue:
