### ISSUE TITLE
Support Slick Async

### ISSUE THREAD

**Issue by mdedetrich** [tminglei/slick-pg#125]
Slick has a new Async interface that is coming in Slick `2.2`.

I am pretty sure a separate implementation of `slick-pg` would be needed to use this interface, since slick async does not use the JDBC driver (it uses https://github.com/mauricio/postgresql-async instead)

**Comment by tminglei** [comment]
Yeah, it's an exciting feature. I'll implement it in `slick-pg` asap.
Will keep updated!

**Comment by nremond** [comment]
@mdedetrich are you sure about the use of postgresql-async ? 
In a talk at Scala-Romandie, @szeiger said that Slick maintains a pool of jdbc connection and that using async wasn't really needed.

**Comment by szeiger** [comment]
Slick only uses JDBC at the moment. We'll have to do some benchmarks to see how much a non-blocking driver could improve over the current situation.

**Comment by mdedetrich** [comment]
@nremond , that was *somewhat* true, and I watched that talk around a week ago. iirc, I don't think they made a scientific consensus, it was more that it didn't appear that the postgres driver provided much performance improvements in their limited testing

In any case, I would image using slick-async would have some improvement, whether in performance or memory usage. How much is another question, and as @szeiger  mentioned, you would need to do this scientifically

**Comment by tminglei** [comment]
@mdedetrich, I can't support postgres-async, without `slick` foundation support.

**Comment by mdedetrich** [comment]
All good, I think `slick` may have changed their trajectory after they got initial readings that using `postgresql-async` wasn't that much of a benefit.

I suppose we can reopen if slick ends up supporting `postgresql-async `

**Comment by tminglei** [comment]
Ok. If `slick` started supporting async drivers, I'd like to follow up.
