### ISSUE TITLE
Could not find implicit value while using any classes with geometry field

### ISSUE THREAD

**Issue by yadavan88** [tminglei/slick-pg#126]
Hi,
I am trying to use postgis in my scala application. I am using slick-pg extension for the implementation.
But I got stuck with one issue and spent almost 5 hours on that, with no luck.

I am getting error as

Error:(34, 67) could not find implicit value for parameter gr: scala.slick.jdbc.GetResult[com.myapp.entity.Location]
class LocationService(repository: ImplLocationRepository) extends CrudActor[LocationTable, Location, Long](repository)

CrudActor expects Implicit GetResult parameter for the case class. This is required since in some cases we need to use the Plain sql query.
I believe the issue is because it is not able to find the implicit converssion for the Geometry type. I have no idea how to fix it. Any help is appreciated.

I have followed the same instruction and sample code from https://github.com/tminglei/slick-pg . Used the 'usage' section code as MyPostgreDriver in my code as well.

I am pasting parts of my code here.

    case class Location(override val id: Long, name: String, levelId: Option[Long] = None, altitude: Option[Double] = None, description: Option[String] = None,override val isRemoved: Boolean, locationCode: Option[String] = None, locationType: Long, override val isPendingForApproval: Boolean = false,override val createdBy: Long,override val createDate: java.sql.Timestamp,override val modifiedBy: Long,override val modifiedDate: java.sql.Timestamp, locationArea: Option[Geometry]) extends AggregateRoot[Long] with MasterDataEntity[Long]

    implicit def GetResultLocation(implicit e0: GR[Long], e1: GR[String], e2: GR[Option[Long]], e3: GR[Option[Double]], e4: GR[Option[String]], e5: GR[Boolean], e6: GR[java.sql.Timestamp], e7: GR[Option[Geometry]]): GR[Location] = GR{
        prs => import prs._
          Location.tupled((<<[Long], <<[String], <<?[Long], <<?[Double], <<?[String], <<[Boolean], <<?[String], <<[Long], <<[Boolean], <<[Long], <<[java.sql.Timestamp], <<[Long], <<[java.sql.Timestamp], <<?[Geometry]))
      }
      class LocationTable(_tableTag: Tag) extends BaseTable[Location](_tableTag, Some("base"), "Location") {
        def * = (id, name, levelId, altitude, description, isRemoved, locationCode, locationType, isPendingForApproval, createdBy, createDate, modifiedBy, modifiedDate, locationArea) <> (Location.tupled, Location.unapply)
        def ? = (id.?, name.?, levelId, altitude, description, isRemoved.?, locationCode, locationType.?, isPendingForApproval.?, createdBy.?, createDate.?, modifiedBy.?, modifiedDate.?, locationArea).shaped.<>({r=>import r._; 1.map(_=> Location.tupled((_1.get, 2.get, 3, 4, 5, 6.get, 7, 8.get, 9.get, 10.get, 11.get, 12.get, 13.get, 14)))}, (_:Any) =>  throw new Exception("Inserting into ? projection not supported."))
        override val id: Column[Long] = column[Long]("LocationId", O.AutoInc, O.PrimaryKey)
        val name: Column[String] = column[String]("Name", O.Length(150,varying=true))
        val levelId: Column[Option[Long]] = column[Option[Long]]("LevelId", O.Default(None))
        val altitude: Column[Option[Double]] = column[Option[Double]]("Altitude", O.Default(None))
        val description: Column[Option[String]] = column[Option[String]]("Description", O.Length(50,varying=true), O.Default(None))
        override val isRemoved: Column[Boolean] = column[Boolean]("IsRemoved")
        val locationCode: Column[Option[String]] = column[Option[String]]("LocationCode", O.Length(20,varying=true), O.Default(None))
        val locationType: Column[Long] = column[Long]("LocationType")
        val isPendingForApproval: Column[Boolean] = column[Boolean]("IsPendingForApproval", O.Default(false))
        val createdBy: Column[Long] = column[Long]("CreatedBy")
        val createDate: Column[java.sql.Timestamp] = column[java.sql.Timestamp]("CreateDate")
        val modifiedBy: Column[Long] = column[Long]("ModifiedBy")
        val modifiedDate: Column[java.sql.Timestamp] = column[java.sql.Timestamp]("ModifiedDate")
        val locationArea: Column[Option[Geometry]] = column[Option[Geometry]]("LocationArea", O.Length(2147483647,varying=false))
        lazy val levelTableFk = foreignKey("fk_location", levelId, levelTable)(r => r.id, onUpdate=ForeignKeyAction.NoAction, onDelete=ForeignKeyAction.NoAction)
        lazy val locationTypeTableFk = foreignKey("fk_location_0", locationType, locationTypeTable)(r => r.id, onUpdate=ForeignKeyAction.NoAction, onDelete=ForeignKeyAction.NoAction)
    }
      lazy val locationTable = new TableQuery(tag => new LocationTable(tag))

**Comment by tminglei** [comment]
@yadavan88 I need your driver definition codes to check which was missed.

**Comment by yadavan88** [comment]
@tminglei I copied the exact MyPostgresDriver class from the sample on the github page. Any way, I will update the code here as well.

**Comment by tminglei** [comment]
Hi @yadavan88 there are many MyPostgresDriver classes in `slick-pg`'s test codes, I need know which one?

**Comment by yadavan88** [comment]
@tminglei, this is the postgres driver code. I am importing this file instead of scala.slick.driver.Postgresdriver in my code.

package com.myapp.drivers


import slick.driver.PostgresDriver
import com.github.tminglei.slickpg._

trait MyPostgresDriver extends PostgresDriver
with PgArraySupport
with PgDateSupport
with PgRangeSupport
with PgHStoreSupport
with PgPlayJsonSupport
with PgSearchSupport
with PgPostGISSupport {

  override lazy val Implicit = new ImplicitsPlus {}
  override val simple = new SimpleQLPlus {}

  //////
  trait ImplicitsPlus extends Implicits
  with ArrayImplicits
  with DateTimeImplicits
  with RangeImplicits
  with HStoreImplicits
  with JsonImplicits
  with SearchImplicits
  with PostGISImplicits

  trait SimpleQLPlus extends SimpleQL
  with ImplicitsPlus
  with SearchAssistants
  with PostGISAssistants
}

object MyPostgresDriver extends MyPostgresDriver

**Comment by tminglei** [comment]
Hi @yadavan88 your definition is for Lifted Embedding SQL.

For Plain SQL, you should define it like this:
```scala
object MyPlainPostgresDriver extends PostgresDriver
                              with PgArraySupport
                              with PgJsonSupport
                              with PgNetSupport
                              with PgLTreeSupport
                              with PgRangeSupport
                              with PgHStoreSupport
                              with PgSearchSupport
                              with PgPostGISSupport {
  ///
  val plainImplicits = new Implicits with SimpleArrayPlainImplicits
                                     with SimpleJsonPlainImplicits
                                     with SimpleNetPlainImplicits
                                     with SimpleLTreePlainImplicits
                                     with SimpleRangePlainImplicits
                                     with SimpleHStorePlainImplicits
                                     with SimpleSearchPlainImplicits
                                     with PostGISPlainImplicits  {}
}
```

**Comment by yadavan88** [comment]
Thanks for the response. I will try that out and let you know.

**Comment by yadavan88** [comment]
@tminglei I amnot able to resolve SimpleArrayPlainImplicits or any other plain implicits, Do I need to add any other dependency other than "com.github.tminglei" "slick-pg" "0.7.0" ?

**Comment by tminglei** [comment]
@yadavan88 pls use the latest version `v0.8.1`.
_Plain SQL support was added in v0.8.0._

**Comment by yadavan88** [comment]
@tminglei My Bad.. I upgraded to 0.8.1. Now PostGISPlainImplicits is not resolving, Rest all other traits have resolved.

**Comment by tminglei** [comment]
Are you sure?

**Comment by yadavan88** [comment]
[error]  object PgPostGISSupport is not a member of package com.github.tminglei.slickpg
[error] Note: trait PgPostGISSupport exists, but it has no companion object.
[error] import com.github.tminglei.slickpg.PgPostGISSupport.PostGISPlainImplicits
[error]                                    ^
[error] MyPostgresDriver.scala:49: not found: type PostGISPlainImplicits
[error]     with PostGISPlainImplicits  {}
[error]          ^
[error] two errors found

**Comment by yadavan88** [comment]
This is my whole file.

import com.github.tminglei.slickpg.PgPostGISSupport.PostGISPlainImplicits

import slick.driver.PostgresDriver
import com.github.tminglei.slickpg._

trait MyPostgresDriver extends PostgresDriver
with PgArraySupport
with PgDateSupport
with PgRangeSupport
with PgHStoreSupport
with PgPlayJsonSupport
with PgSearchSupport
with PgPostGISSupport {

  override lazy val Implicit = new ImplicitsPlus {}
  override val simple = new SimpleQLPlus {}

  //////
  trait ImplicitsPlus extends Implicits
  with ArrayImplicits
  with DateTimeImplicits
  with RangeImplicits
  with HStoreImplicits
  with JsonImplicits
  with SearchImplicits
  with PostGISImplicits

  trait SimpleQLPlus extends SimpleQL
  with PostGISImplicits
  with SearchAssistants
  with PostGISAssistants
}

object MyPostgresDriver extends MyPostgresDriver

object MyPlainPostgresDriver extends PostgresDriver with PgArraySupport with PgJsonSupport with PgNetSupport with PgLTreeSupport with PgRangeSupport with PgHStoreSupport with PgSearchSupport {

  val plainImplicits = new Implicits with SimpleArrayPlainImplicits
    with SimpleJsonPlainImplicits
    with SimpleNetPlainImplicits
    with SimpleLTreePlainImplicits
    with SimpleRangePlainImplicits
    with SimpleHStorePlainImplicits
    with SimpleSearchPlainImplicits
    with PostGISPlainImplicits  {}
}

**Comment by tminglei** [comment]
Pls check source code, there isn't object `PgPostGISSupport`. It's a trait.

**Comment by tminglei** [comment]
I made them as traits, to enable users can mix them on demand. :)

**Comment by yadavan88** [comment]
I have the "import com.github.tminglei.slickpg._  "
But with "PostGISPlainImplicits" is not getting resolved.

What am I doing wrong. Sorry to disturb you this much.

**Comment by yadavan88** [comment]
Sorry, I think I made a mistake again. :( I am not mixing it with PgPostGISSupport. Let me try with that.

**Comment by tminglei** [comment]
Hi @yadavan88,  yes, `PostGISPlainImplicits` is a trait in trait `PgPostGISSupport`.

So normally it should be used like this:
```scala
object MyPlainPostgresDriver extends PostgresDriver
                              ...
                              with PgPostGISSupport {
  ///
  val plainImplicits = new Implicits with SimpleArrayPlainImplicits
                                     ...
                                     with PostGISPlainImplicits  {}
}
```

Sorry for my stiff words. But I really invite you to read the test codes, since it's a personal project, and I know I haven't provide enough guide texts. :-)

**Comment by yadavan88** [comment]
Not yet.. :( Still trying. I am using both lifted and plain queries in my application. Getting the same error even after adding the plain implicits. 

class MyService extende GenericService[](repository:MyRepository)  (implicit GetResult[Location])

Location is a case class with Option[Geometry] field. 
I will let you know as soon as I crack it. :)

**Comment by yadavan88** [comment]
@tminglei : Finally, I was able to fix the compilation error. But now, the problem in reading the database value correctly, It is giving in the hex format, unable to convert it to POINT format.

implicit object GetGeometry extends scala.AnyRef with scala.slick.jdbc.GetResult[Option[Geometry]] {
    override def apply(rs : scala.slick.jdbc.PositionedResult) :Option[Geometry]  = { val str = rs.nextStringOption().get;  Some(new WKTReader().read(str).asInstanceOf[Point]) }
  }

**Comment by tminglei** [comment]
Hi @yadavan88 here's the postgis support's source [code](https://github.com/tminglei/slick-pg/blob/master/src/main/scala/com/github/tminglei/slickpg/addon/PgPostGISSupport.scala).
If you really need convert geom string manually, pls use `PgPostGISSupportUtils.fromLiteral`, which will help resolve the HEX format for you.

**Comment by yadavan88** [comment]
@tminglei Finally, solved the issues.. Thanks a lot for all your time... You are a saviour! :)

**Comment by tminglei** [comment]
@yadavan88 you're welcome!
