### ISSUE TITLE
Feature: support for concat operator ||

### ISSUE THREAD

**Issue by killdashnine** [tminglei/slick-pg#128]
See http://stackoverflow.com/questions/28454405/slick-like-query-with-column-as-parameter/

To be able to perform queries like:

    SELECT * FROM   rates
    WHERE  '3113212512' LIKE (prefix || '%') and  present = true
    ORDER  BY prefix DESC
    LIMIT  1;

It would require something like following:

    val concat = SimpleBinaryOperator[String]("||")
    
    Rates.filter(_.ratePlanId === ratePlan)
    .filter(_.present === true)
    .filter(s => LiteralColumn(prefix) like concat(s.prefix, "%"))
    .sortBy(_.prefix.desc).firstOption

It would be nice if slick-pg is able to provide the concatenation operator as per my information this operator is postgres specific? (Not sure)

**Comment by tminglei** [comment]
@killdashnine, yeah, we need add more pg string support in `slick-pg`.
I'll implement it asap.

Will keep you posted!

**Comment by tminglei** [comment]
Hi @killdashnine, I noticed that `slick` already support `concat` with `++`.
Doesn't it work for you?

**Comment by killdashnine** [comment]
You are absolutely right:

    filter(s => LiteralColumn(prefix) like (s.prefix ++ "%"))

Does the same thing
