### ISSUE TITLE
Support for Arrays of composite types with plain SQL

### ISSUE THREAD

**Issue by mlovretovich** [tminglei/slick-pg#131]
I'm trying to pass an array of a composite row type into a function using plainSQL and get the following error: could not find implicit value for parameter pconv: scala.slick.jdbc.SetParameter

**Comment by tminglei** [comment]
Hi @mlovretovich, I have added some built-in support for composite array in Plain SQL.
But I'd better to make it more convenient.

_I'll do it asap._

**Comment by tminglei** [comment]
Hi @mlovretovich, I have added plain SQL support for composite/array in f72aeb9.

**Comment by mlovretovich** [comment]
works great @tminglei This is exactly what I needed.
Thanks!

**Comment by tminglei** [comment]
Hi @mlovretovich, I have released the changes in `slick-pg` `v0.8.2`.
_Pls update your dependency to use it._
