### ISSUE TITLE
implicit for converting Hstore in plain SQL queries

### ISSUE THREAD

**Issue by killdashnine** [tminglei/slick-pg#132]
When using Slick plain SQL queries for a case class with a hstore column (Map[String,String]) scala will complain about the following:

    diverging implicit expansion for type scala.slick.jdbc.GetResult[T1]
    starting with object GetString in object GetResult

The reason for this is, that there is no mapper for Map[String,String] in scala.slick.jdbc.GetResult

This may be fixed by providing an implicit to allow slick to map the Map[String,String] as follows:

    implicit object GetHstore extends GetResult[Map[String, String]] {
      def apply(rs: PositionedResult) = WrapAsScala.mapAsScalaMap(HStoreConverter.fromString(rs.nextString()).asInstanceOf[java.util.Map[String, String]]).toMap
    }

**Comment by tminglei** [comment]
Hi @killdashnine, did you check the related `hstore` [tests](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgHStoreSupportTest.scala#L109)?

_I have added Plain SQL support for pg `hstore`. :)_

**Comment by killdashnine** [comment]
You are right, I just need a Plain driver with SimpleHstorPlainImplicits implicit :)
