### ISSUE TITLE
provided dependencies

### ISSUE THREAD

**Issue by drapp** [tminglei/slick-pg#135]
What's the logic in having provided dependencies? I just updating to 0.8.2 and lost a bunch of time trying to figure out why it worked in some contexts and failed in others. It turned out to depend on whether or not some other dependency was pulling in scala-reflect
https://github.com/tminglei/slick-pg/commit/29c1e5cd30fb5fbcdc38934a522c02cb5813f6f5#diff-215113124f1de02f228327ba7abb45f7R69
I've got it working again, but why not have transitive dependencies?

**Comment by tminglei** [comment]
Hi @drapp, `provided` dependencies won't be added to your project automatically, which requires you to do it manually.

But it help prevent from 
- auto importing unnecessary dependencies, for these third party dependencies, like `joda`, `json4s`, `jts`, etc. and 
- reduce version conflicts, for `scala-reflect`, when your scala's **minor** version is not same as that one in `slick-pg`.

**Comment by tminglei** [comment]
I updated the `README` to remind this.
_Thanks! :)_

**Comment by tminglei** [comment]
Hi @drapp, after resloved #136, I realized that I worried the conflict too much.
I'll declare it as a transitive dependency again.

**Comment by tminglei** [comment]
I just released the changes, pls update your dependency to use it.
