### ISSUE TITLE
Transitive dependency on slf4j-simple causes multiple-binding error

### ISSUE THREAD

**Issue by mackler** [tminglei/slick-pg#136]
I'm using logback, and the dependency on slf4j-simple is causing a conflict.  From the slf4j documentation:

> Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose. When you come across an embedded component declaring a compile-time dependency on any SLF4J binding, please take the time to contact the authors of said component/library and kindly ask them to mend their ways.

Details here:
http://www.slf4j.org/codes.html#multiple_bindings

**Comment by tminglei** [comment]
Hi @mackler, `slick-pg` didn't declare a dependency for `slf4j`. It comes from `slick`.
I'll send a pull request to `slick` to declare the dependency to `provided`, which will allow you to add yours safely.

**Comment by mackler** [comment]
Thank you, and thanks for this great extension!

**Comment by tminglei** [comment]
You're welcome! And pls watch the pull request processing. :)

**Comment by tminglei** [comment]
Hi @mackler, I made a mistake to `slick`, and just submitted a change to fix this issue.

**Comment by tminglei** [comment]
Hi @mackler, I have released the changes, pls update your dependency to use it.
