### ISSUE TITLE
Why tests no run in master branch?

### ISSUE THREAD

**Issue by mackler** [tminglei/slick-pg#142]
I'm trying to run some tests but I'm failing to do it correctly.  On the the  `master` branch if I do:

    > testOnly com.github.tminglei.slickpg.PgDate2SupportTest

I can tell the tests are being skipped because I have *_not_* created the `test` database, yet I get a message claiming success:

    [info] Passed: Total 2, Failed 0, Errors 0, Passed 2
    [success] Total time: 247 s, completed Mar 24, 2015 11:00:06 PM

And I even changed a value passed to one of the `assertEquals()` invocations, which should have caused it to fail (no?), and yet I got the same message.

On the other hand, If I checkout the `slick2` branch and run the same command then I can see the tests *do* run because they try to connect to the non-existent database and I get the appropriate failure message:

    [error] Failed: Total 2, Failed 2, Errors 0, Passed 0
    [error] Failed tests:
    [error] 	com.github.tminglei.slickpg.PgDate2SupportTest
    [error] (slick-pg/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
    [error] Total time: 218 s, completed Mar 24, 2015 10:49:41 PM

In both cases I am doing it from the `sbt` prompt.  In both cases `sbt` tells me 

    [info] Set current project to slick-pg

What am I missing?

**Comment by tminglei** [comment]
Yes, you're right. So strange!
I'll investigate it asap.

**Comment by tminglei** [comment]
Well, seems same problem occurred in `slick` tests.

**Comment by tminglei** [comment]
Hmm... should be the futures not to be executed as expected.

**Comment by tminglei** [comment]
The tests were executed now, but need some more enhancement.

**Comment by timcharper** [comment]
Was this the result of a regression I introduced? If so, I apologize!

**Comment by tminglei** [comment]
Hi @timcharper, sorry for wrongly involved you in. _It's not related to you. ;)_

**Comment by vikraman** [comment]
Looks like this was caused by me, the changes for slick 3.0 were incomplete, sorry!

**Comment by tminglei** [comment]
Don't say that. You did some I need to do.
_I'll take care of it. :)_
