### ISSUE TITLE
PgDateSupport Interval.toString incorrectly renders seconds (0,00 secs)

### ISSUE THREAD

**Issue by Primetalk** [tminglei/slick-pg#143]
It uses new DecimalFormat with default locale. And in some locales decimal separator is ','.

Have a look at PGInterval. It sets separator specially to '.'.

**Comment by tminglei** [comment]
Hi @Primetalk, we encountered the problem before at #99, but don't know where it's different.
Can you reference #99 first, and help provide more details?

**Comment by Primetalk** [comment]
In org.postgresql.util.PGInterval there is a piece of code to deal with the issue:

     private final static DecimalFormat secondsFormat;
     static {
        secondsFormat = new DecimalFormat("0.00####");
        DecimalFormatSymbols dfs = secondsFormat.getDecimalFormatSymbols();
        dfs.setDecimalSeparator('.');
        secondsFormat.setDecimalFormatSymbols(dfs);
     }

However, in com.github.tminglei.slickpg.Interval

    object Interval {
      private val secondsFormat = new DecimalFormat("0.00####")

'.' here is not enough. It only shows the position of the decimal separator. It is also necessary to fix the character of the separator to be '.'. As one can see DecimalFormat uses default locale:

    /**
     * Creates a DecimalFormat using the given pattern and the symbols
     * for the default locale. This is a convenient way to obtain a
     * DecimalFormat when internationalization is not the main concern.
     * <p>
     * To obtain standard formats for a given locale, use the factory methods
     * on NumberFormat such as getNumberInstance. These factories will
     * return the most appropriate sub-class of NumberFormat for a given
     * locale.
     *
     * @param pattern A non-localized pattern string.
     * @exception NullPointerException if <code>pattern</code> is null
     * @exception IllegalArgumentException if the given pattern is invalid.
     * @see java.text.NumberFormat#getInstance
     * @see java.text.NumberFormat#getNumberInstance
     * @see java.text.NumberFormat#getCurrencyInstance
     * @see java.text.NumberFormat#getPercentInstance
     */
    public DecimalFormat(String pattern) {
        // Always applyPattern after the symbols are set
        this.symbols = new DecimalFormatSymbols(Locale.getDefault(Locale.Category.FORMAT));
        applyPattern(pattern, false);
    }

I think it would be better to have the following code:

    object Interval {
      private val secondsFormat = {
        val format = new DecimalFormat("0.00####")
        val dfs = secondsFormat.getDecimalFormatSymbols()
        dfs.setDecimalSeparator('.')
        format.setDecimalFormatSymbols(dfs)
        format
      }

**Comment by tminglei** [comment]
Ok, I'll apply it to `slick-pg` asap.
_Thanks for your pointing it out! :)_

**Comment by tminglei** [comment]
Hi @Primetalk, applied your suggested changes to `slick-pg`.
_But haven't found a good case to test it yet._
