### ISSUE TITLE
Code copy from test case not work.

### ISSUE THREAD

**Issue by djx314** [tminglei/slick-pg#153]
success code
<https://github.com/djx314/slick-pg-issue/blob/master/src/main/scala/org/xarcher/pgtest/Test.scala#L29>

fail code
<https://github.com/djx314/slick-pg-issue/blob/issue/src/main/scala/org/xarcher/pgtest/Test.scala#L20>

copy from
<https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/addon/PgPlayJsonSupportSuite.scala#L18>

if the slick-pg test successed,is it the problem from the package ?
```scala
package com.github.tminglei.slickpg
```

**Comment by tminglei** [comment]
I can't explain why. Maybe we should turn to scala/sbt community for help.

_BTW, slick-pg tests were really succeeded._

**Comment by djx314** [comment]
I reproduce the bug by moving the driver objcet to the global scope. see
<https://github.com/djx314/slick-pg/commit/e50f77efbff2372aad2645815427e9d5c8b60cf2>
<https://github.com/djx314/slick-pg/commit/9a9b9d08abb034406b63f5dd6aee4dbffad53fdb>
The second url is the final version for the reproducing bug.

And I fix it by set the api via define the api objcet as a object. see
<https://github.com/djx314/slick-pg/commit/63ca9408aaed421a8a5c42f618e6fec49b87f82a>
This demo compiles successfully.

**Comment by tminglei** [comment]
Yeah, that's the only difference. But I'm still not know why.
To help others to avoid this problem, maybe you'd better send a PR with your fixing changes to me.

_Thanks very much!_

**Comment by tminglei** [comment]
I also updated `README.md` to reflect that.

**Comment by djx314** [comment]
Great to hear that after I get up.
