### ISSUE TITLE
Convert between PostGIS geom type and geoJson string for mapped projection?

### ISSUE THREAD

**Issue by hanfeisun** [tminglei/slick-pg#155]
I am using slick pg 0.8.2 and tried to make a custom mapped projection between a table and a case class. (convert between Geo JSON and LineString type in PostGIS)

```
import java.sql.Timestamp
import com.vividsolutions.jts.geom.LineString
import utils.common.PgDriver.simple._

case class TripPathGeoJson (
    id: Long,
    path: String,   // Geo JSON wrapped in a String
    timeSeries: List[Timestamp]
    )


class TripPathTable(tag: Tag) extends Table[TripPathRecord](tag, "TripPath") {
  def id = column[Long]("id", O.AutoInc, O.PrimaryKey)

  def tripID = column[Long]("tripID")

  def beginTime = column[Timestamp]("beginTime")

  def endTime = column[Timestamp]("endTime")

  def path = column[LineString]("path")

  def timeSeries = column[List[Timestamp]]("timeSeries")

  def createTime = column[Timestamp]("createTime")

  def updateTime = column[Timestamp]("updateTime")


  def trip = foreignKey("tripFk", tripID, trips)(trip => trip.id)

  def * = (id, tripID, beginTime, endTime, path) <>(TripPathRecord.tupled, TripPathRecord.unapply)

  private def geoJsonApply(id: Long, path: LineString, timeSeries: List[Timestamp]) = {
    val geoJsonPath = path.bind.asGeoJSON()
    new TripPathGeoJson(id, geoJsonPath, timeSeries)
  }

  private def geoJsonUnapply(input: TripPathGeoJson) = {
    val path = geomFromGeoJSON(input.path)
    Some(input.id, path, input.timeSeries)
  }

  def tripPathGeoJson = (id, path, timeSeries) <> ((geoJsonApply _).tupled, geoJsonUnapply)
}
```

However, I found these lines throws an error:

```
    val geoJsonPath = path.bind.asGeoJSON()
    new TripPathGeoJson(id, geoJsonPath, timeSeries)
```

The `path` is `LineString` type, I want to convert it into a String type(geoJson) by `path.bind.asGeoJSON()`. But the result type is `Column[String]` type instead of `String` type..

Is there a way to get the string from `Column[String]` so it can be used to construct the case class?

**Comment by tminglei** [comment]
Hi @hanfeisun, `asGeoJSON()` is shadow of a db function, so `path.bind.asGeoJSON()` is an illegal usage.

To convert a `LineString` to a `GeoJSON` string, you should do it in **jvm** instead.
If you can find a utility that can help convert jts Geometry objects to GeoJSON strings, that will be great.

**Comment by hanfeisun** [comment]
Thanks! It seems that JTS Topology Suite doesn't have the utility to convert Geometry object to GeoJSON string.. And the conversion has to depend on PostGIS anyway..

Finally I use the approach below 
```
          val query = for {
            t <- tripPaths
            if t.id === pathID
          } yield (t.id, t.path.asGeoJSON(), t.timeSeries)
          TripPathGeoJson.tupled(query.first)
```

It is not so concise as the mapped projection approach but it works well..

**Comment by tminglei** [comment]
Hi @hanfeisun, your way may lead to bad performance.

I found a lib [`jts2geojson`](https://github.com/bjornharrtell/jts2geojson), you can give it a try.

**Comment by hanfeisun** [comment]
Thanks, @tminglei 

I'm not sure about the performance issue..

Shouldn't this for-expression
```
          for {
            t <- tripPaths
            if t.id === pathID
          } yield (t.id, t.path.asGeoJSON(), t.timeSeries)
```
 be translated directly into

```
select id, ST_AsGeoJSON(path), timeSeries from tripPaths where id = "$myPathID"
```
?

If so, I thought it is the conversion to GeoJSON is handled by Postgres/PostGIS during the database querying and seems quite efficient.. 

Do you mean the conversion can be done better without resorting to Postgres?

**Comment by tminglei** [comment]
Yes. Since what you want is to construct a `TripPathGeoJson` with some member values `id: Long, path: LineString, timeSeries: List[Timestamp]` existed in jvm, it's obviously more efficient to execute it totally in jvm.

**Comment by hanfeisun** [comment]
I see, but now the type of path member of `TripPathGeoJson` is `String` instead of `LineString`. I thought no extra conversion is needed..

```
case class TripPathGeoJson (
    id: Long,
    path: String,   // Geo JSON wrapped in a String
    timeSeries: List[Timestamp]
    )
```

**Comment by tminglei** [comment]
Ok. Anyway your solution works. :)

**Comment by hanfeisun** [comment]
ok~
