### ISSUE TITLE
Inserting a Point

### ISSUE THREAD

**Issue by mkeshav** [tminglei/slick-pg#156]
Hi there,
   I am trying to insert a point into table with no luck. Can you please point me to an example. Below is what i am trying to do.

val c = new Coordinate(37.8136, 144.9631)
        val gmf = new GeometryFactory()
        val p:Point = gmf.createPoint(c)

and inserting it into the table. When i run the test i can see that it is unable to substitute the values for point.

insert into "event" ("event_time","location","attributes")  values (1431157817234,?,'"key"=>"value"')

Please help me out

**Comment by tminglei** [comment]
Hi @mkeshav, you can find the test case [here](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/addon/PgPostGISSupportSuite.scala).

**Comment by mkeshav** [comment]
thank you so much

**Comment by tminglei** [comment]
You're welcome!
