### ISSUE TITLE
value ?? is not a member of slick.lifted.Rep[play.api.libs.json.JsValue]

### ISSUE THREAD

**Issue by photex** [tminglei/slick-pg#159]
Hello!

Having trouble getting my driver setup apparently.

```
package atlas.storage.sql.postgres

import com.github.tminglei.slickpg._

class AtlasPostgresDriver extends ExPostgresDriver
    with PgDateSupport
    with PgPlayJsonSupport
    with PgSearchSupport
{
  override val pgjson = "jsonb"
  override val api = AtlasAPI
  override lazy val Implicit = new ImplicitsPlus {}
  override val simple = new SimpleQLPlus {}

  object AtlasAPI extends API
      with DateTimeImplicits
      with PlayJsonImplicits
      with SearchImplicits
      with SearchAssistants

  trait ImplicitsPlus extends Implicits
      with DateTimeImplicits
      with PlayJsonImplicits
      with SearchImplicits

  trait SimpleQLPlus extends SimpleQL
      with ImplicitsPlus
      with SearchAssistants
}

object AtlasPostgresDriver extends AtlasPostgresDriver
```

In my dao I'm trying to filter rows by those with a certain key:

`activeVerts.filter(_._1.properties ?? key.bind).result`

This won't compile though. The error is:
`value ?? is not a member of slick.lifted.Rep[play.api.libs.json.JsValue]`

I'm not connecting the dots somehow. (slick 3.0.0, play 2.4.0-RC3, play-slick 1.0.0-RC2, slick-pg 0.9.0)

Does any of the above stand out as obviously wrong?

Cheers!

**Comment by tminglei** [comment]
Hi @photex, did you add `import atlas.storage.sql.postgres.AtlasPostgresDriver.api._` to your dao?

**Comment by photex** [comment]
Hi @tminglei, I do import that. The structure is as follows:

```
trait Schema {
  import AtlasPostgresDriver.simple._
  // table definitions and table query instances
}

class MyDAO extends Schema {
  import AtlasPostgresDriver.api._
  // ...
  def vertices(key: String) = {
    val action = activeVerts.filter(_._1.properties ?? key).result.map(_.map(toVertex))
    db.run(action)
  }
  // ...
}
```

The column mappers for `JsValue` work fine, I just can't seem to get the extension methods in scope perhaps.

**Comment by tminglei** [comment]
Well, in slick 3.0, the `simple` and `Implicit` were deprecated, and users should turn to use the `api`.
You can use the `api` only and try again.

**Comment by photex** [comment]
Unfortunately I get the same result. I will try to move some things around. I've looked at the PgJsonExtensions trait and from what I can tell it's straight forward and this should work as is..

**Comment by photex** [comment]
@tminglei My driver didn't include the mappers in the API object I created. I simplified it and ended up with the following driver which works:

```
trait AtlasPostgresDriver extends ExPostgresDriver
    with PgDateSupport
    with PgArraySupport
    with PgPlayJsonSupport
{
  override val pgjson = "jsonb"
  override val api = AtlasAPI

  object AtlasAPI extends API
      with JsonImplicits
      with ArrayImplicits
      with DateTimeImplicits
  {
    implicit val strListTypeMapper = new SimpleArrayJdbcType[String]("text").to(_.toList)
    implicit val json4sJsonArrayTypeMapper =
      new AdvancedArrayJdbcType[JsValue](
        pgjson,
        (s) => utils.SimpleArrayUtils.fromString[JsValue](Json.parse(_))(s).orNull,
        (v) => utils.SimpleArrayUtils.mkString[JsValue](_.toString())(v)
      ).to(_.toList)
  }
}

object AtlasPostgresDriver extends AtlasPostgresDriver
```

**Comment by tminglei** [comment]
Cheers! :)
