### ISSUE TITLE
Slick PG modules

### ISSUE THREAD

**Issue by alternegro** [tminglei/slick-pg#161]
Hello,
Are the different modules documented anywhere?
How does one know which modules to add to build.sbt?
I'm currently getting the following errors when I attempt to compile:

>TMPostgresDriver.scala:23: not found: type NetImplicits
>                          with NetImplicits
>                                ^
>TMPostgresDriver.scala:24: not found: type LTreeImplicits
>                         with LTreeImplicits

**Comment by tminglei** [comment]
Hi @alternegro, `NetImplicits` belongs to `PgNetSupport`, `LTreeImplicits` belongs to `PgLTreeSupport`.
You can find them [here](https://github.com/tminglei/slick-pg/tree/master/src/main/scala/com/github/tminglei/slickpg).

**Comment by alternegro** [comment]
@tminglei thanks I found them. Should I send a pull request that updates `README.md` to include `PgNetSupport` & `LTreeImplicits` in the traits extended by `MyPostgresDriver` ?

**Comment by tminglei** [comment]
OK. I haved merged your PR. _Thanks! :-)_
