### ISSUE TITLE
Support for java.time.Instant

### ISSUE THREAD

**Issue by vikraman** [tminglei/slick-pg#165]
Hi,

I'm trying to add support for `java.time.Instant`, which should map to the `timestamp` postgres type. This is my attempt, but I'm unable to make the tests pass.

https://github.com/vikraman/slick-pg/commit/130f35b726f3be4e56acf4df709fd91fd8cc6a12
https://travis-ci.org/vikraman/slick-pg/jobs/65711894

**Comment by tminglei** [comment]
Hi @vikraman,

Travis reported two test failures:
```
[info] - Java8 date Lifted support *** FAILED ***
[info]   java.time.format.DateTimeParseException: Text '2001-01-03 13:21:00.102203' could not be parsed at index 10
[info]   at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1947)
```
and
```
[info] - Java8 date Plain SQL support *** FAILED ***
[info]   java.time.format.DateTimeParseException: Text '1 year 2 mons 25 days' could not be parsed at index 0
[info]   at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1947)
```

For problem 1, that's because you used `Instant.parse(_)` in 
```scala
    protected val fromInstantOrInfinity: String => Instant = fromInfinitable(
      Instant.MAX, Instant.MIN, Instant.parse(_))
```
But here `java.time` put a tricky question to us, because it didn't provide a method `Instant.parse(s, formatter)` to us.
And I checked the codes, it seems we can't construct a `Instant` from a `LocalDateTime`. And `java.sql.Timestamp` and `java.util.Date` seems also can't help. 

For problem 2, that's because you forgot to add one more column when the create table sql, and do related adjustments.

------------------------------------
For problem 1, I haven't found a way to resolve it.
The best way to let `java.time` to provide `Instant.parse(s, formatter)`, but can they?

**Comment by vikraman** [comment]
Thank you for the pointers, I was able to get it working by pasrsing with `LocalDateTime` and converting using `toInstant`. The tests are passing now.

https://github.com/vikraman/slick-pg/commit/af48634b17dae4fa7c621584447d271e8266384b
https://travis-ci.org/vikraman/slick-pg/builds/65770861

Now, how do I add support for timestamp functions? I think I have to add implicits using the `TimestampColumnExtensionMethods` class, but I don't exactly understand what the type parameters are doing. Any pointers would be appreciated, thanks.

**Comment by tminglei** [comment]
_Wow, I forgot this is java 8, so the interfaces can have default method implementations. :-)_

_Cheers!_

**Comment by tminglei** [comment]
Hi @vikraman, sorry for missed your last question.

To add support for timestamp functions, I think you can do like this:
```scala
  implicit def date2Timestamp1ColumnExtensionMethods(c: Rep[Instant])(implicit tm: JdbcType[INTERVAL]) =
    new TimestampColumnExtensionMethods[LocalDate, LocalTime, Instant, INTERVAL, Instant](c)
  implicit def date2Timestamp1OptColumnExtensionMethods(c: Rep[Option[Instant]])(implicit tm: JdbcType[INTERVAL]) =
    new TimestampColumnExtensionMethods[LocalDate, LocalTime, Instant, INTERVAL, Option[Instant]](c)

```

**Comment by btd** [comment]
Actually it is possible to convert both Calendar and java.util.Date to instat, see https://docs.oracle.com/javase/8/docs/api/java/util/Date.html#toInstant--

**Comment by pauldijou** [comment]
Any plan to integrate this work into slick-pg? Instant is a core member of the `java.time` package and the closest one to the `timestamp` type.

**Comment by tminglei** [comment]
Hi @vikraman, would you send out a PR?

**Comment by tminglei** [comment]
_Did it myself. ;-)_

**Comment by pauldijou** [comment]
Sweet. Thanks a lot.

**Comment by vikraman** [comment]
Thanks.
