### ISSUE TITLE
Are there known issues for List[Array[Byte]]

### ISSUE THREAD

**Issue by bearrito** [tminglei/slick-pg#177]
Are there any known issue with attempting this?

I am currently trying 

```implicit val byteATypeMapper = new SimpleArrayJdbcType[Array[Byte]]("bytea").to(_.toVector)```

When I try that I receive a notImplementedException.

If there are limitations and there isn't something wrong with my code I assume it is a JDBC limitation, are there links to this limitation?

**Comment by tminglei** [comment]
Hi @bearrito, what do you want is a mapper of byte array?
If yes, you can try `implicit val byteATypeMapper = new SimpleArrayJdbcType[Byte]("bytea").to(_.toVector)`.

_p.s. here, the type parameter should be `Byte` instead of `Array[Byte]`._

**Comment by bearrito** [comment]
Why should it be `Byte` and not `Array[Byte]` ? Slick code-gen generates the following

```
 /** Database column bson_id SqlType(bytea) */
    val bsonId: Rep[Array[Byte]] = column[Array[Byte]]("bson_id")

```

What I want is the corresponding scala type of `bytea[]` which I believe corresponds to an Array[Array[Byte]]. This is a multi-dimensional array which I don't believe is supported by PG JDBC

**Comment by tminglei** [comment]
Oh, yes, `pgjdbc` doesn't support array of array, and so do `slick-pg`.

**Comment by bearrito** [comment]
That confirms might thoughts.
