### ISSUE TITLE
Support for hstore within composite types

### ISSUE THREAD

**Issue by mlovretovich** [tminglei/slick-pg#178]
I'd like to include an hstore within a composite type. it does not appear to be listed in the type converters and is throwing errors

**Comment by tminglei** [comment]
I'll implement is ASAP.
But you may wait some time, since I'm very busy these days.

**Comment by mlovretovich** [comment]
thank you VERY much. 
hopefully it is not much work. this is a very big part of our data model.

**Comment by tminglei** [comment]
Hi @mlovretovich, supporting hstore within composite type won't be easy, since its output string contains `,`, which will conflict with normal separator `,`. That's why I give up supporting it at first time.

But anyway I'll try again.

**Comment by tminglei** [comment]
Hi @mlovretovich, seems we're lucky. It was resolved successfully in #182. _;-)_

**Comment by tminglei** [comment]
Hi @mlovretovich, I released slick-pg v0.9.1 to pick up the change.
_Pls check it. Thanks!_
