### ISSUE TITLE
Querying Option[Point] with PgPostGIS

### ISSUE THREAD

**Issue by nelsonblaha** [tminglei/slick-pg#179]
I need to find users near a given Point, but I want a nullable user location as well: 

    def findNear(point: Point): Future[Map[User, Int]] = {
        DB withSession { implicit session =>
          Future.successful {
            slickUsers.filter(u => u.location.dWithin(point.bind, distance.bind))
          }
        }
      }

I can't think of a way around this error: 
    
    value dWithin is not a member of scala.slick.lifted.Column[Option[com.vividsolutions.jts.geom.Point]]

**Comment by tminglei** [comment]
Hi @nelsonblaha, you're using a `slick2` version of slick-pg, right?
That should be OK, you can check the new [pull](https://github.com/tminglei/slick-pg/commit/8c10f8702ad0fd92ce9abe4fd0937067441372dc).

_Maybe you forgot to import the necessary implicits, can you double check?_

**Comment by nelsonblaha** [comment]
@tminglei I wasn't using slick2 branch. Is there a way to do so with maven or do I need to learn some other method of installation for slick-pg? I'm attempting to upgrade to 0.9.0 in the hope that it includes such geom-option-handling as well. Is this a reasonable strategy? 

I am having a similar problem upgrading to 0.9.0, in which the PgPlayJsonSupport does not upgrade from 0.6.5.3 (it's the newest version I could find for Maven). The import "scala.slick.lifted.Column" is missing. I see it isn't used in the current master slick-pg, but I don't know how to install that.

Can you direct me to some resource about how to install these alternate/updated versions of slick-pg and components? I feel so close to being back on track...

**Comment by tminglei** [comment]
`slick-pg` merged these 3rd support into its main codes, so you needn't import them any more.
pls check the [desc](https://github.com/tminglei/slick-pg/releases/tag/v0.7.0) of v0.7.0 for details.

**Comment by nelsonblaha** [comment]
Option[Point] is not the problem I'm having, at least not yet. I simplified my project to use Column[Point] without Options, but I think I don't know how to use GeometryColumnExtensionMethods, because I'm getting this error:

    value dWithin is not a member of scala.slick.lifted.Column[com.vividsolutions.jts.geom.Point]

I can't find a working example, I promise I've combed the slick-pg source code- I'm still a little new to Scala. Is it an import I'm missing?

    import models.daos.UserDAO
    import java.util.UUID
    import com.mohiva.play.silhouette.api.LoginInfo
    import play.Logger
    import play.api.db.slick._
    import play.api.db.slick.Config.driver.simple._
    import scala.concurrent.Future
    import models.daos.pg.DBTableDefinitions._
    import com.vividsolutions.jts.geom.Point

**Comment by tminglei** [comment]
Seems you're using `play-slick`, and the `driver.simple` didn't contain the expected extensions.

Did you check the example project [here](https://github.com/tminglei/slick-pg/tree/master/examples/play-slick-example) and its conf [file](https://github.com/tminglei/slick-pg/blob/master/examples/play-slick-example/conf/application.conf)?

**Comment by nelsonblaha** [comment]
I gave up and started over from a newer activator seed, to better match the play-scala example.
