### ISSUE TITLE
PSQLException: type not found, when calling bind on custom enums.

### ISSUE THREAD

**Issue by iain-logan** [tminglei/slick-pg#180]
I have a custom enum ```Role```.
Scala code:
```
object Roles extends Enumeration {
  type Role = Value
  val Member, Leader, Organiser = Value
}
```
PostgreSQL code:
```
CREATE TYPE "Role" AS ENUM ('Member', 'Leader', 'Organiser');
```
I have it setup working fine for filtering on ```Role``` columns for equality, but If I try any queries that require me to do .bind to a value of type ```Role``` I get ```PSQLException: Unknown type role```.

For example [this test case](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgEnumSupportSuite.scala#L91) will cause the exception to be thrown when I implemented it as shown below.

```
  def getRole(role: Role): Future[Seq[Any]] = {
    db.run(
    tripMembers.filter(_.userId === 1L).map(t => null.asInstanceOf[Role].bind range t.userRole).result
    )
  }
```
Table is shown below for completeness.
```
  class Members(tag: Tag) extends Table[Member](tag, "Member") {
    def userId = column[Long]("UserId")
    def userRole = column[Role]("UserRole")

    def * = (userId, userRole) <> (Member.tupled, Member.unapply _)
  }
```

Here are the mappers from my custom postgres driver.
```
  override val api = new API with ArrayImplicits
    with DateTimeImplicits
    with PlayJsonImplicits
    with NetImplicits
    with LTreeImplicits
    with RangeImplicits
    with HStoreImplicits
    with SearchImplicits
    with SearchAssistants
    with CustomEnumImplicits {}

  trait CustomEnumImplicits {
    implicit val roleTypeMapper = createEnumJdbcType("Role", Roles)
    implicit val roleListTypeMapper = createEnumListJdbcType("Role", Roles)

    implicit val roleColumnExtensionMethodsBuilder = createEnumColumnExtensionMethodsBuilder(Roles)
    implicit val roleOptionColumnExtensionMethodsBuilder = createEnumOptionColumnExtensionMethodsBuilder(Roles)
  }
```

So In queries which do not require me to call .bind on some ```Role``` value, things seem to be working perfectly. When .bind is needed I get an exception at runtime. Am I missing something from my custom mappings?

I am using slick 3.0 with postgres 9.3.

**Comment by tminglei** [comment]
well, when declaring enum type, you wrapped it with double quotes, so it should be accessed by quoted name.

pls try to define your role type mapper as this:
```scala
implicit val roleTypeMapper = createEnumJdbcType("Role", Roles, true)
```

**Comment by iain-logan** [comment]
It works, thanks for your quick response, and thanks for making slick-pg, it has proved to be very useful.

**Comment by tminglei** [comment]
You're welcome! :-)
