### ISSUE TITLE
Support for Java 8 Duration

### ISSUE THREAD

**Issue by bearrito** [tminglei/slick-pg#181]
From the README it appears that Java 8 Durations are supported by I don't seem to see support in PgDateSupport. 

My driver extends the correct Traits but no luck compiling.

**Comment by bearrito** [comment]
This can be closed. I see that my Driver must actually extend `with PgDate2Support` as shown in https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/addon/PgDate2SupportSuite.scala

**Comment by tminglei** [comment]
Yes, it's supported in `PgDate2Support`. _:-)_
