### ISSUE TITLE
Support for simple nested lists

### ISSUE THREAD

**Issue by sundriver** [tminglei/slick-pg#184]
Hi there,

 Thanks for the nice work, Could you please advise how one could map List[List[Double]] ?

 I have a feeling that nested collections are not supported. In Postgres there is real[][] data type.

Thanks,

**Comment by tminglei** [comment]
`PgJdbc` didn't support array of array, so `slick-pg` didn't support it too.
_Why you want to use it? it seems not a good data structure._

**Comment by sundriver** [comment]
Thanks for clarification, then I just close this issue.

**Comment by tminglei** [comment]
_np ;-)_
