### ISSUE TITLE
Please publish the other libraries(slick-pg_play-json, slick-pg_date2 etc.) for 0.10.0-M1

### ISSUE THREAD

**Issue by ghost** [tminglei/slick-pg#186]
I am trying to use `0.10.0-M1` but am finding that only `slick-pg` is published.
I would like to use the libraries with a smaller granularity

**Comment by tminglei** [comment]
They are included in `slick-pg`, you can check.

**Comment by tminglei** [comment]
Hi @ghost, I already restored to publish them as independent jars at `slick-pg` v0.10.0.
