### ISSUE TITLE
Does slick-pg support postgres COPY command ?

### ISSUE THREAD

**Issue by sundriver** [tminglei/slick-pg#188]
Hi there,
 I would like to know if slick-pg supports postgres COPY command ?
 If not, could you mark this as a feature request.

Thanks for the great work,

**Comment by tminglei** [comment]
Well, COPY command is a pg type extension method?

_If not, it may be not suitable as a feature of `slick-pg`._

**Comment by Daenyth** [comment]
@tminglei I think this would be a good slick-pg feature, as `COPY` for postgres is supported via the postgres-jdbc-specific `CopyManager` class

**Comment by tminglei** [comment]
@Daenyth why don't use plain sql to do this? As you know, slick-pg only cares about pg custom types and their associated operators/methods.

**Comment by Daenyth** [comment]
The postgres driver doesn't support it - it throws an exception. See for example Doobie's implementation: https://tpolecat.github.io/doobie/docs/15-Extensions-PostgreSQL.html#copy-manager

**Comment by tminglei** [comment]
Well, slick w/ slick-pg uses postgres driver to communicate with pg. All slick-pg's abilities derived from pg and pg/jdbc.

**Comment by Daenyth** [comment]
Right, I'm proposing a new `copy` DSL that would compile down to `CopyManager` operations. Perhaps it doesn't fit with slick's implementation strategy.
