### ISSUE TITLE
Update to slick 3.0.1

### ISSUE THREAD

**Issue by damirv** [tminglei/slick-pg#189]
http://slick.typesafe.com/news/2015/08/06/slick-3.0.1-released.html

Should this be done on the 0.9.x branch? I just checked, this update also fixes the classloader issue (see #163).

**Comment by tminglei** [comment]
ok, I'll do it asap.

**Comment by tminglei** [comment]
Hi @damirv, I published `slick-pg v0.9.2`, which upgraded `slick` to v3.0.1 and picked up some other changes.
Pls check it.

**Comment by damirv** [comment]
Looks good to me!
