### ISSUE TITLE
plain sql usage - newbie

### ISSUE THREAD

**Issue by sundriver** [tminglei/slick-pg#190]
Hi, 
 This is a newbie question, I am trying to use plain sql syntax to build an upsert operation, like below:

     def insertOrUpdate(ident: Int, ts: DateTime, value: Option[Float], tags: List[String], metadata: JsValue) = sql"""
      		  begin;
      		  update "data"."data_1" set "value"=? where "ident"=? and "ts"=?;
      		  insert into "data"."data_1" ("ident","ts","value","tags","metadata") select $ident,$ts,$value,$tags,$metadata where not exists (select 1 from "data"."data_1" where "ident"=$ident and "ts"=$ts );
      		  end;
      		"""

And I am getting 

***could not find implicit value for parameter e: slick.jdbc.SetParameter[List[String]]***

in my MyPgDriver I have:

    trait MyPostgresDriver extends ExPostgresDriver
        with PgArraySupport
        with PgDateSupportJoda
        with PgRangeSupport
        with PgHStoreSupport
        with PgPlayJsonSupport
        with PgSearchSupport
        with PgNetSupport
        with PgLTreeSupport {
      override val pgjson = "jsonb" //to keep back compatibility, pgjson's value was "json" by default
    
      override val api = MyAPI
    
      object MyAPI extends API with ArrayImplicits
          with JodaDateTimePlainImplicits
          with JsonImplicits
          with NetImplicits
          with LTreeImplicits
          with RangeImplicits
          with HStoreImplicits
          with SearchImplicits
          with SearchAssistants {
    
        implicit val strListTypeMapper = new SimpleArrayJdbcType[String]("text").to(_.toList)
    
        implicit val playJsonArrayTypeMapper =
          new AdvancedArrayJdbcType[JsValue](pgjson,
            (s) => utils.SimpleArrayUtils.fromString[JsValue](Json.parse(_))(s).orNull,
            (v) => utils.SimpleArrayUtils.mkString[JsValue](_.toString())(v)
          ).to(_.toList)
    
        implicit val dateTimeColumnType = MappedColumnType.base[DateTime, java.sql.Timestamp](
          dt => new java.sql.Timestamp(dt.getMillis),
          t => new DateTime(t.getTime).withZone(DateTimeZone.UTC)
        )
    
      }
    
    }
    
    object MyPostgresDriver extends MyPostgresDriver

When I remove tags:List[String] parameter, then I get similar error but for type JsValue. 

I appreciate if someone could advice as how to correctly use plain sql with pg-slick. Thanks

**Comment by sundriver** [comment]
for reference, solved it by adding with PlayJsonPlainImplicits with SimpleArrayPlainImplicits

Thanks for the great library. I am closing the issue.

**Comment by tminglei** [comment]
:-)
