### ISSUE TITLE
Missing timezone from table definition when DateTime used

### ISSUE THREAD

**Issue by sundriver** [tminglei/slick-pg#193]
Hi,
 I have the following schema:

```scala
class DataTableSchema (tableName: String, tag: Tag) extends Table[DataTable](tag, tableName) {

	def timestamp = column[DateTime]("ts")
	def value = column[Option[Float]]("value")
	def pk = primaryKey("pk_" + tableName, (timestamp))
	def * = (timestamp, valu) <>((DataTable.apply _).tupled, DataTable.unapply)
}
```

This schema generates the following table, but the ts column is missing timezone. My understanding was if I use LocalDateTime it implies no timezone, and using DateTime implies DateTime with timezone.

```sql
CREATE TABLE data
(
  ts timestamp without time zone NOT NULL,
  value real,
)
```

I appreciate your comment

**Comment by tminglei** [comment]
Hi @sundriver, I don't know what happened on your side.
But I tried to comment the `drop schema` actions in PgDate2SupportSuite/PgDate2bpSupportSuite/PgDateSupportJodaSuite, then run, and it looks ok.

Can you double check?

**Comment by sundriver** [comment]
Thanks for checking this. Yes, the issue was from my side.
