### ISSUE TITLE
JSON: checking if value IS NULL

### ISSUE THREAD

**Issue by mustajarvi** [tminglei/slick-pg#205]
What's the idiomatic way of checking if a JSON value is null?

I tried

    .filter{tweet => (tweet.rawJson +>> "coordinates").isDefined}

but since `isDefined is not a member of slick.lifter.Rep[String]` I had to work around it by using the deprecated `isNotNull`:

    .filter{tweet => (tweet.rawJson +>> "coordinates").isNotNull}

Besides generated deprecation warnings when compiling, I'm a bit worried that `isNotNull` will be removed in a future release of Slick.

**Comment by tminglei** [comment]
Hi @mustajarvi, `isNotNull` was removed in slick `v3.1.0-M2`.

`isDefined` is an extension method of `Rep[Option[_]]` instead of `Rep[_]`, so you should try:
```scala
.filter{ tweet => (tweet.rawJson +>> "coordinates").?.isDefined }
```

**Comment by mustajarvi** [comment]
Ahh, thanks. Of course. Somehow it had slipped my mind.

Link if someone else encounters this: http://slick.typesafe.com/doc/3.0.0/upgrade.html#isnull-and-isnotnull

Aside from the workaround, shouldn't `+>>` et al really return `Option[String]` instead of `String`? I realize it would break backwards compatibility in a big way, but I'm interested in your thoughts on the matter.

**Comment by tminglei** [comment]
Hi @mustajarvi, for the compatibility of `slick` you should turn to ask @szeiger ^^

**Comment by mustajarvi** [comment]
I mean slick-pg backwards compatibility. From PgJsonExtensions :

```scala
 def +>>[P2, R](key: Rep[P2])(implicit om: o#arg[String, P2]#to[String, R]) = {
        om.column(jsonLib.BiArrow, n, key.toNode)
      }
```

From the Postgres doc at http://www.postgresql.org/docs/9.4/static/functions-json.html :

>The field/element/path extraction operators return NULL, rather than failing, if the JSON input does not have the right structure to match the request; for example if no such element exists.

Since the operators can return NULL shouldn't the function `def +>>` return `Option[String]`?

**Comment by tminglei** [comment]
Hi @mustajarvi, I don't think it was always the right way to return `Option[Rep[_]]` for `NULLABLE`  column. So I'd like to let users to do it themselves.

**Comment by mustajarvi** [comment]
Ok, thanks for your thoughts @tminglei . Closing this one.
