### ISSUE TITLE
tsVector() with Option?

### ISSUE THREAD

**Issue by ErunamoJAZZ** [tminglei/slick-pg#211]
Hello!

I'm trying to use search function over a Option column. Using your test as example, its some like this:

```scala
class TestTable(tag: Tag) extends Table[TestBean](tag, "tsTestTable") {
    def id = column[Long]("id", O.AutoInc, O.PrimaryKey)
    def text = column[String]("text")
    def comment = column[String]("comment")
    def myOptionColumn = column[Option[String]]("my_option_column")

    def * = (id, text, comment) <> (TestBean.tupled, TestBean.unapply)
  }
val Tests = TableQuery[TestTable]

//...
Tests.filter(r => tsVector(r.myOptionColumn) @@ tsQuery("cat & rat"))
```
https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgSearchSupportSuite.scala

**This does not compile**, because just allowed String types. Now, if you add a `.get` or `getOrElse`, ie: `Tests.filter(r => tsVector(r.myOptionColumn.get) @@ tsQuery("cat & rat"))`, this will compile, but then fail in execution time:

> `Execution exception[[SlickException: Caught exception while computing default value for Rep[Option[_]].getOrElse -- This cannot be done lazily when the value is needed on the database side]]`

This error was documented in https://github.com/slick/slick/issues/549

Thanks.

**Comment by tminglei** [comment]
Hi @ErunamoJAZZ, resolved, pls help check. _Thanks!_
