### ISSUE TITLE
Support for CITEXT extension type

### ISSUE THREAD

**Issue by frosforever** [tminglei/slick-pg#213]
`CITEXT` is not currently supported by slick out of the box. Treating it as a `String` in slick will cause queries to be cast to `text` forcing postgres to be case sensitive.

**Comment by tminglei** [comment]
Ok, I'll add support for it asap.

**Comment by tminglei** [comment]
If we add support for it, which existing scala type can be used to mapping?

**Comment by frosforever** [comment]
@tminglei I think it would have to be a `String` in Scala. Though it would mean that sql queries would be case insensitive, but in memory comparisons will be as a regular string (ie. user must use `equalsIgnoreCase`)

**Comment by tminglei** [comment]
Well, `String` shouldn't be bind to both `text` and `citext`, which will lead to slick/slick-pg won't know how to attach extension methods to it.

**Comment by tminglei** [comment]
BTW, there are some special methods for `citext`? Seems not found in the doc.

**Comment by frosforever** [comment]
Argh you're right. It would be nice if `O.SqlType` could be used.

I don't think there are any special methods for `citext`. Per the docs, http://www.postgresql.org/docs/9.1/static/citext.html

> Essentially, it internally calls lower when comparing values. Otherwise, it behaves almost exactly like text.

**Comment by tminglei** [comment]
@frosforever, so, it resolved your problem, right?

**Comment by frosforever** [comment]
@tminglei This does not resolve the problem of `citext` being treated as `text` in slick statements. Though, I'm not sure what the best way forward is. One possible way is introducing a `Citext` class that would also have case insensitive equals and hash code.

I don't know enough about slick statement generation. Is there a way to mark what `String` should compile to, `text` or `citext`? My understanding is that `O.SqlType` is only used in schema generation and not in statement generation. Is that indeed the case or can that be leveraged here?

**Comment by tminglei** [comment]
But it seems ok to me.

With the [changes](https://github.com/tminglei/slick-pg/commit/fdd3c60bf2049cfc144ab61471b1dc90efcc20f9), and don't forget add `citext` extension to your postgres, run `sbt test`, then you'll find the column type of `test_tab1.COL3` is `citext`.

**Comment by frosforever** [comment]
@tminglei Thanks for taking the time with this!

I have added a test https://github.com/frosforever/slick-pg/commit/0c248c130bfd7b4b574f05417e7b7b31132b2f8e that demonstrates the issue. It doesn't come up when a simple query is used (eg `.filter(_.col === "A string")` ) but only when the query is compiled and then executed.

**Comment by tminglei** [comment]
This is expected. `citext` will be treated as insensitive text **only** executing on db.
Outside of db, it's normal text.

**Comment by tminglei** [comment]
I enhanced the test codes, you can check it.

**Comment by frosforever** [comment]
The compiled query is still executed on the the DB. I would have thought that there would be no difference between running a query or compiling it first and then running it.
Is there a way to signify to the query compiler that the column should be treated as `citext` and not `text`?

**Comment by tminglei** [comment]
I can't find out why. Maybe we should turn to @szeiger for help.

**Comment by frosforever** [comment]
This seems to be the same issue as https://stackoverflow.com/questions/12031613/postgresql-citext-datatype-issue-jpa-hibernate. 
See this answer specifically http://stackoverflow.com/a/12031620/2620122. Would you know if that's controllable in slick to explicitly specify the `citext` datatype as the parameter type to the query?

I have also verified that setting the `dbUrl` in `utils` to `jdbc:postgresql://localhost/test?user=postgres&stringtype=unspecified`allows the tests with compiled queries to run without issue. I don't know if that comes with a performance penalty or other issues.

**Comment by tminglei** [comment]
Inspired by you, I resolved it. Pls see the changes [here](https://github.com/tminglei/slick-pg/commit/2baec08dd8c8048797a5b538cfd7e05586353c5c).

**Comment by frosforever** [comment]
@tminglei That does indeed work! So there are at least 2 solutions to the `citext` problem.
1. Adding `stringtype=unspecified` to the jdbc url
2. explicitly calling `asColumnOfType`

I've also verified that `asColumnOfType` works on a slick mapped class, i.e. something that extends `MappedTo` or has an implicit `MappedColumnType`.

Thanks very much for your help! I'm closing this issue.

**Comment by tminglei** [comment]
_You're welcome!_

**Comment by perotom** [comment]
I tried to use `stringtype=unspecified` but it didn't work out and `asColumnOfType` is not available. Any ideas how to work with CITEXT?
