### ISSUE TITLE
Object creation impossible by using the example

### ISSUE THREAD

**Issue by ysihaoy** [tminglei/slick-pg#218]
I am very new to use this library and I got some issue when I used it.

```scala
import com.github.tminglei.slickpg._

trait MyPostgresDriver extends ExPostgresDriver
                          with PgDateSupport
                          with PgHStoreSupport {
  override val api = MyAPI

  object MyAPI extends API with DateTimeImplicits
                           with HStoreImplicits {
  }
}

object MyPostgresDriver extends MyPostgresDriver
```

I used either the above code or example code README file, it's not working.

The error is for MyPostgresDriver object creation impossible and Intellij alerts me there are couple of methods not implemented.

Did I miss something?

**Comment by ysihaoy** [comment]
Also, it seems the use case for Java 8 Date is not existing? Could you please provide an example for that?

**Comment by tminglei** [comment]
Hi @ysihaoy, I copied the codes into a temp file on local project, and it was compiled successfully.
Don't know what errors you encountered, can you paste more details?

_For the use case for Java 8 Date, sorry, it's broken when I splitting the plugins to independent jars._
I have fixed it, pls help check again.

**Comment by ysihaoy** [comment]
Thanks @tminglei , Sorry to confuse you.

I think it's Intellij IDE bug, I use command line and it compiles successfully.

Thanks.

**Comment by tminglei** [comment]
_It's ok. Glad to hear that! :-)_
