### ISSUE TITLE
println in ExPostgresDriver.scala

### ISSUE THREAD

**Issue by kwark** [tminglei/slick-pg#221]
There are some println in ExPostgresDriver.scala

println(s"[info]\u001B[36m >>> binding $pgType -> $scalaType \u001B[0m")

println(s"[info]\u001B[36m jdbcTypeToScala - jdbcType $jdbcType, typeName: $typeName \u001B[0m")

Can you remove them or make them log statements, so we can choose whether they show up or not?

**Comment by tminglei** [comment]
Ok, I'll change it. _Thanks for pointing it out!_

**Comment by tminglei** [comment]
Hi @kwark, I have changed them to log statements.

**Comment by prettynatty** [comment]
please, release this. It's critical for async environments.

**Comment by tminglei** [comment]
Ok, I'll do it soon.

**Comment by tminglei** [comment]
Released, pls check it.
