### ISSUE TITLE
value +>> is not a member of slick.lifted.Rep[org.json4s.JValue]

### ISSUE THREAD

**Issue by simao** [tminglei/slick-pg#222]
Hi,

I am getting this message when trying to use `+>>` to filter a query:

````scala
import CPostgresDriver.api._
vehicles.filter(_.details.@>>("") === "")

// Error:
// value +>> is not a member of slick.lifted.Rep[org.json4s.JValue]
````

I am using a postgres driver like this:

````scala
trait CPostgresDriver extends ExPostgresDriver
with PgRangeSupport
with PgJson4sSupport
with PgPostGISSupport {

  def pgjson = "jsonb"

  type DOCType = JValue
  override val jsonMethods = org.json4s.jackson.JsonMethods

  override val api = MyAPI

  object MyAPI extends API
  with JsonImplicits
  with PostGISImplicits
  with RangeImplicits
  with DateTimeMapper
}

object CPostgresDriver extends CPostgresDriver
````

This is with slick-pg 0.9.2. Am I missing something?

**Comment by tminglei** [comment]
I can't imagine it. But you see it's ok in the test [case](https://github.com/tminglei/slick-pg/blob/master/addons/json4s/src/test/scala/com/github/tminglei/slickpg/PgJson4sSupportSuite.scala#L78).

**Comment by simao** [comment]
Hi,

Thanks for your reply.

I managed to isolate the problem in a small test project, here it is:

**Comment by tminglei** [comment]
Ok, I'll check it. Thanks!

**Comment by tminglei** [comment]
Hi @simao, if you add array support to your customized postgres driver, the issue will be resolved.

_The cause is: I declared an unnecessary `JdbcType[List[String]]` implicit in `implicit def json4sJsonColumnExtensionMethods(c: Rep[JValue])(...`. When no `JdbcType[List[String]]` found, the binding to `JsonColumnExtensionMethods` will fail, then it can't find `+>>` method for JValue type._

I have fixed it in the [submit](https://github.com/tminglei/slick-pg/commit/884c25265e50725bfe08542093327f71154ba372).

**Comment by simao** [comment]
That works! Thanks a lot for checking it!
