### ISSUE TITLE
buildCreateSql for Composite Type?

### ISSUE THREAD

**Issue by danishin** [tminglei/slick-pg#223]
First of all, amazing library very nicely done :100:  Thank you so much for doing all this.

I've only recently got up to speed with this library and wonder if there is support for `buildCreateSql` for `composite` type. I've confirmed there is one for `enum` type. 

Is this not supported yet? I've looked through your test cases and it seems that you are creating `composite` type manually by passing sql string unlike the one for `enum`.

Thanks!

+
Also could you explain what `PgCompositeSupportUtils.mkCompositeFromString` and its friends are for? I can't find their usage in your test cases

**Comment by tminglei** [comment]
[Here's](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgCompositeSupportSuite.scala) the test cases.
Yes, no support for `buildCreateSql` for `composite` type.

_It seems not all info creating a `composite` type can be expressed by a case class, so I leave users to do it themselves._

**Comment by danishin** [comment]
@tminglei Thanks for quick response! Yeah I can definitely just create it on the fly.

Yet, I've been having issues with combining `enum` and `composite`. Something like the following seems to fail:

```
CREATE TYPE noti_event_enum_type AS ENUM (
  'receive', 'send'
)

CREATE TYPE noti_type (
  noti_event noti_event_enum_type
)
```

Is putting `enum` inside `composite` not supported?

**Comment by danishin** [comment]
fyi, the above code is just a translation in SQL. Everything is done using your library.

**Comment by tminglei** [comment]
They will fail, when you execute them sequentially?

**Comment by tminglei** [comment]
This is executed in postgres, no need special support from `slick-pg`.

**Comment by danishin** [comment]
@tminglei Turns out that wasn't the issue (and you're right indeed). I've zeroed in where the error happened.

It fails when I include:

```
  trait CompositeImplicits {
    implicit val notiRecordMapper = createCompositeJdbcType[NotiRecord](NotiRecord.pgTypeName)
    implicit val notiRecordArrayMapper = createCompositeArrayJdbcType[NotiRecord](NotiRecord.pgTypeName).to(_.toList)
  }
```

I'm using `Play` and it simply fails when `guice` injection takes place without stacktrace.
Not sure what the problem is.

**Comment by tminglei** [comment]
I also don't know why.

But do you notice the codes in the test [case](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgCompositeSupportSuite.scala#L55):
```scala
utils.TypeConverters.register(mapToString)
utils.TypeConverters.register(stringToMap)
```

If your `composite` type contained a `enum` type, you need add two converters for it.

**Comment by danishin** [comment]
That indeed was the reason. I had to add for both `enum` and `JsValue`. Thank you so much for your help!

**Comment by tminglei** [comment]
_You're welcome!_
