### ISSUE TITLE
Array Extension methods not found

### ISSUE THREAD

**Issue by danishin** [tminglei/slick-pg#224]
I'm having issue with extension methods for `Array` type like `unnest`, `@>` etc.

I also tried importing your test case on `Array` [here](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgArraySupportSuite.scala) and it also cannot find the extension methods either.

All others work fine. Do you have any idea?

**Comment by tminglei** [comment]
I don't know what happened in your side.

But not all types' array were built-in supported. Did you add array support for your type?

**Comment by danishin** [comment]
Hmm okay, this is weird. Turns out it does compile but it's just that my IDE (Intellij) for some reason cannot find them. I find this kind of stuff happens occasionally when implicit types are a little too complicated. Is there a way I can make the `import` more explicit? 

Perhaps do something with `PgArrayExtensions`? Thanks

**Comment by danishin** [comment]
I believe this issue is related to [this](https://github.com/tminglei/slick-pg/issues/168)

**Comment by tminglei** [comment]
I don't what happened. But I don't think it's related to #222.

**Comment by danishin** [comment]
Through some hacking on your library, I found that using `implicit class` in place of `implicit def` and `class` does remedy the problem.

But I guess it's not worthwhile since it's just a problem with IDE. I decided to go SQL on this since it became kinda ugly anyway. Thanks for your help as always
