### ISSUE TITLE
Parsing empty play-JSON object throws

### ISSUE THREAD

**Issue by danishin** [tminglei/slick-pg#225]
Hello, so I found that passing empty Json object from `play-json` using `Json.object()` throws the following exception:
> com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: {; line: 1, column: 0])
> at [Source: {; line: 1, column: 3]

My code is something like:
```
foo.map(fooRecord +: _.foo_records).result.head
```
where `FooRecord` is `composite` type and has a `JsValue` field and is constructed like:
```
FooRecord(json: Json.obj())
```

Not sure if this issue is specific to my use case or `slick-pg_play-json`'s json parsing in general.

**Comment by danishin** [comment]
On a side note, is there a way to `update` by `append` to `Array`?

For example in SQL:
```
UPDATE Foos SET foo_records = foo_records || $foo_record 
```
is one-liner but yet I haven't found the equivalent in slick. Currently:
```
foos.map($foo_record +:_.foo_records).result.head.flatMap(updated => foos.map(_.foo_records).update(updated))
```

**Comment by tminglei** [comment]
Not understand your problem. Can you provide more details?

**Comment by danishin** [comment]
Hello, sorry for being not clear. I was in rush last week, should've took more time.

The first was fixed simply using `Option[JsValue]` instead.

But the second remains as just a question. What I meant by that was
```
UPDATE Foos SET foo_records = foo_records || $foo_record
```
requires one db access to update `foo_records` by appending to it.

whereas in slick-pg AFAIK,
```
foos.map(_.foo_records + $foo_records).result.head.flatMap(updated => foos.map(_.foo_records).update(updated))
```
requires two db access to first fetch updated `foo_records` and then to do another `UPDATE`, which roughly translates to:
```
SELECT foo_records || $foo_records FROM Foo;
UPDATE Foo SET foo_records = $updated_foo_records;
```
I was wondering if this can be avoided due to the lack of my knowledge in slick-pg.

Thanks for your help

**Comment by tminglei** [comment]
Hi @danishin, `slick` didn't provide a way to resolve your problem. If it's really a concern, you can try plain sql.

BTW, from my view, I may do it like this:
```scala
db.stream(foos.mutate.transactionally).foreach { 
  m => m.row = m.row.copy(foo_records = foo_records + $foo_records)
}
```

**Comment by danishin** [comment]
That's a nice workaround. Thanks for your help! :smile_cat:
