### ISSUE TITLE
Feature request: add window function

### ISSUE THREAD

**Issue by srusev** [tminglei/slick-pg#226]
We are using a lot of Window Functions in postgres:
http://www.postgresql.org/docs/9.1/static/tutorial-window.html

Can we add the support in slick-pg?

**Comment by tminglei** [comment]
This requires support from `slick`. I ever sent a PR in slick/slick#797 and slick/slick#796.
Not sure what is the current status. I'll check it asap.

**Comment by srusev** [comment]
ok, thanks I've subscribed to these issues.

**Comment by n0tel** [comment]
What with this now?

**Comment by tminglei** [comment]
`slick-pg` already implemented some [window functions](https://github.com/tminglei/slick-pg/tree/master/core/src/main/scala/com/github/tminglei/slickpg/window), for usage you can check it [here](https://github.com/tminglei/slick-pg/blob/master/core/src/test/scala/com/github/tminglei/slickpg/PgWindowFuncSupportSuite.scala).

So this issue I'll close it.
