### ISSUE TITLE
make the driver useable from the slick code generator

### ISSUE THREAD

**Issue by hepin1989** [tminglei/slick-pg#228]
Hi,I am using it with 
and 
```
slickCodegenDriver := new PostgresDriver
  with PgPlayJsonSupport
  with PgDate2Support
{
  override def pgjson: String = "jsonb"
}
```
it still generate the error
```
[paymentServer] $ [ForkJoinPool-3-worker-11] WARN slick.driver.PostgresDriver$ModelBuilder - Found unknown jdbc type 1111. Assuming String. This may be wrong. You can override ModelBuilder#Table#Column#tpe to fix this.
[ForkJoinPool-3-worker-11] WARN slick.driver.PostgresDriver$ModelBuilder - Found unknown jdbc type 1111. Assuming String. This may be wrong. You can override ModelBuilder#Table#Column#tpe to fix this.
[ForkJoinPool-3-worker-11] WARN slick.driver.PostgresDriver$ModelBuilder - Found unknown jdbc type 1111. Assuming String. This may be wrong. You can override ModelBuilder#Table#Column#tpe to fix this.
[ForkJoinPool-3-worker-11] WARN slick.driver.PostgresDriver$ModelBuilder - Found unknown jdbc type 1111. Assuming String. This may be wrong. You can override ModelBuilder#Table#Column#tpe to fix this.
[ForkJoinPool-3-worker-11] WARN slick.driver.PostgresDriver$ModelBuilder - Found unknown jdbc type 1111. Assuming String. This may be wrong. You can override ModelBuilder#Table#Column#tpe to fix this.
[ForkJoinPool-3-worker-11] WARN slick.driver.PostgresDriver$ModelBuilder - Found unknown jdbc type 1111. Assuming String. This may be wrong. You can override ModelBuilder#Table#Column#tpe to fix this.

```

I still need to override the 
```
override def createModelBuilder(tables: Seq[MTable], ignoreInvalidDefaults: Boolean)(implicit ec: ExecutionContext): JdbcModelBuilder
```
to generate the right code,like the hand writing code ```def json = column[JsValue]("json", O.Default(Json.parse(""" {"a":"v1","b":2} """)))```

so is there any plan for this?

**Comment by tminglei** [comment]
Not clear for your problem. Is the code gen sample project not useful?

**Comment by hepin1989** [comment]
我想用github.com/tototoshi/sbt-slick-codegen 这个插件,然后用你的这个库来使用pg.
通过slickCodeGen 来生成model类.
因为我如果直接使用slick自带的Driver,那么生成的代码类型是和你的这个不匹配的.
比如我要用playjson,那么它生成的类型是Rep[String]而不是Rep[JsValue]
我看了下,得重写Driver,重写里面的`createModelBuilder`方法,并且重写它的`ColumnBuilder`的方法
`
      override def tpe = meta.typeName match {
        case "bytea" => "Array[Byte]"
        case "lo" if meta.sqlType == java.sql.Types.DISTINCT => "java.sql.Blob"
        case "uuid" => "java.util.UUID"
        case "jsonb" => "play.api.libs.json.JsValue"
        case otherType => {
          println(s"unhandled column type [$otherType]")
          super.tpe
        }
      }
`

但事实上的工作还更多,我弄了下,出来的代码倒是替换了,但是还有什么DefaultValue啊.以及最终的Table.scala编译也有问题.比如
``
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:81: No matching Shape found.
[error] Slick does not know how to map the given types.
[error] Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).
[error]   Required level: slick.lifted.FlatShapeLevel
[error]      Source type: (slick.lifted.Rep[String], slick.lifted.Rep[String], slick.lifted.Rep[Option[play.api.libs.json.JsValue]], slick.lifted.Rep[play.api.libs.json.JsValue], slick.lifted.Rep[String])
[error]    Unpacked type: (String, String, Option[play.api.libs.json.JsValue], play.api.libs.json.JsValue, String)
[error]      Packed type: Any
[error]     def * = (game, channel, config, schema, description) <> (PaymentRow.tupled, PaymentRow.unapply)
[error]                                                          ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:83: could not find implicit value for parameter od: slick.lifted.OptionLift[Tables.this.profile.api.Rep[play.api.libs.json.JsValue],O]
[error]     def ? = (Rep.Some(game), Rep.Some(channel), config, Rep.Some(schema), Rep.Some(description)).shaped.<>({ r => import r._; _1.map(_ => PaymentRow.tupled((_1.get, _2.get, _3, _4.get, _5.get))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))
[error]                                                                 ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:83: not found: value _1
[error]     def ? = (Rep.Some(game), Rep.Some(channel), config, Rep.Some(schema), Rep.Some(description)).shaped.<>({ r => import r._; _1.map(_ => PaymentRow.tupled((_1.get, _2.get, _3, _4.get, _5.get))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))
[error]                                                                                                                               ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:83: not found: value _1
[error]     def ? = (Rep.Some(game), Rep.Some(channel), config, Rep.Some(schema), Rep.Some(description)).shaped.<>({ r => import r._; _1.map(_ => PaymentRow.tupled((_1.get, _2.get, _3, _4.get, _5.get))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))
[error]                                                                                                                                                              ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:83: not found: value _2
[error]     def ? = (Rep.Some(game), Rep.Some(channel), config, Rep.Some(schema), Rep.Some(description)).shaped.<>({ r => import r._; _1.map(_ => PaymentRow.tupled((_1.get, _2.get, _3, _4.get, _5.get))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))
[error]                                                                                                                                                                      ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:83: not found: value _3
[error]     def ? = (Rep.Some(game), Rep.Some(channel), config, Rep.Some(schema), Rep.Some(description)).shaped.<>({ r => import r._; _1.map(_ => PaymentRow.tupled((_1.get, _2.get, _3, _4.get, _5.get))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))
[error]                                                                                                                                                                              ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:83: not found: value _4
[error]     def ? = (Rep.Some(game), Rep.Some(channel), config, Rep.Some(schema), Rep.Some(description)).shaped.<>({ r => import r._; _1.map(_ => PaymentRow.tupled((_1.get, _2.get, _3, _4.get, _5.get))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))
[error]                                                                                                                                                                                  ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:83: not found: value _5
[error]     def ? = (Rep.Some(game), Rep.Some(channel), config, Rep.Some(schema), Rep.Some(description)).shaped.<>({ r => import r._; _1.map(_ => PaymentRow.tupled((_1.get, _2.get, _3, _4.get, _5.get))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))
[error]                                                                                                                                                                                          ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:90: could not find implicit value for parameter tt: slick.ast.TypedType[Option[play.api.libs.json.JsValue]]
[error]     val config: Rep[Option[play.api.libs.json.JsValue]] = column[Option[play.api.libs.json.JsValue]]("config", O.Default(None))
[error]                                                                                                     ^
[error] /home/kerr/devProject/ideaProject/guaji-server/stack/paymentServer/app/model/Tables.scala:92: could not find implicit value for parameter tt: slick.ast.TypedType[play.api.libs.json.JsValue]
[error]     val schema: Rep[play.api.libs.json.JsValue] = column[play.api.libs.json.JsValue]("schema")
[error]                                                                                     ^
[error] 10 errors found
[error] (paymentServer/compile:compileIncremental) Compilation failed

``

**Comment by hepin1989** [comment]
@tminglei 不好意思哈,中文交流应该要方便点.

**Comment by tminglei** [comment]
其实我自己不太喜欢代码生成的，所以相应的 demo 项目要人催着或帮忙才会更新的。

`sbt-slick-codegen` 项目有一个配置：
```
// required (If not set, postgresql driver is choosen)
slickCodegenDriver := slick.driver.PostgresDriver
```
貌似可以允许使用定制 driver。
这个你试过吗？

**Comment by tminglei** [comment]
另外，定制代码还是要有的，需要把这样的代码
```scala
    new slick.codegen.SourceCodeGenerator(model) {
      override def Table = new Table(_) { table =>
        override def Column = new Column(_) { column =>
          // customize db type -> scala type mapping, pls adjust it according to your environment
          override def rawType: String = model.tpe match {
            case "java.sql.Date" => "org.joda.time.LocalDate"
            case "java.sql.Time" => "org.joda.time.LocalTime"
            case "java.sql.Timestamp" => "org.joda.time.LocalDateTime"
            // currently, all types that's not built-in support were mapped to `String`
            case "String" => model.options.find(_.isInstanceOf[ColumnOption.SqlType])
              .map(_.asInstanceOf[ColumnOption.SqlType].typeName).map({
                case "hstore" => "Map[String, String]"
                case "geometry" => "com.vividsolutions.jts.geom.Geometry"
                case "int8[]" => "List[Long]"
                case _ =>  "String"
              }).getOrElse("String")
            case _ => super.rawType.asInstanceOf[String]
          }
        }
      }

      // ensure to use our customized postgres driver at `import profile.simple._`
      override def packageCode(profile: String, pkg: String, container: String, parentType: Option[String]) : String = {
        s"""
package ${pkg}
// AUTO-GENERATED Slick data model
/** Stand-alone Slick data model for immediate use */
object ${container} extends {
  val profile = ${profile}
} with ${container}
/** Slick data model trait for extension, choice of backend or usage in the cake pattern. (Make sure to initialize this late.) */
trait ${container}${parentType.map(t => s" extends $t").getOrElse("")} {
  val profile: $profile
  import profile.api._
  ${indent(code)}
}
      """.trim()
      }
    }
  }
```

插入到这个配置项的相应地方
```scala
// optional, pass your own custom source code generator
slickCodegenCodeGenerator := { (model: m.Model) => new SourceCodeGenerator(model) }
```

**Comment by hepin1989** [comment]
我就是这么做的，重写这个对象里面的createModelBuilder方法,返回一个自定义的的ColumnBuilder，这个ColumnBuilder里面需要重写```      override def tpe = meta.typeName match ```方法，返回数据库类型到schema的映射。

**Comment by hepin1989** [comment]
你的意思是光改了这个还不够，还需要更改SourceCodeGenerator里面TableDef的ColumnDef？
我朋友写like倒是也是用的手写的，scala中国群的小星心也是手写的，是不是我太懒了...

**Comment by tminglei** [comment]
印象中重写 `def tpe` 并不能达到目的，所以我后来重写了 `def rawType`，并且要求 `slick` 那边做了些调整。

**Comment by tminglei** [comment]
是啊，我是觉得手写更好的。费不了多少事，改起来也容易。
代码生成把很多事情搞复杂了，而且，一旦有问题，肯定是比较低优先级支持的。

**Comment by hepin1989** [comment]
可以的，重生成的代码里面的Rep[String]变成了Rep[play.api.Json.JsValue].我今天也是想和你这个结合用下jsonb,然后就不行了。我抽空再看下，谢谢了哦。
原生的那个codegenerator的扩展性的确不是很好。不过我今天倒是用的pgjdbc-ng，也是好使的。

**Comment by tminglei** [comment]
不客气 :)

**Comment by hepin1989** [comment]
并且，再传入自定义的Driver后，生成的代码的profile也就是你指定的那个Driver了。

**Comment by tminglei** [comment]
嗯，应该是的 :-)

**Comment by hepin1989** [comment]
您可以在有空的时间补充下wiki么，比如重新组织下？我对你的这个项目的整体架构也不是很理解。
不管怎么说，谢啦，这个也是你的业余项目，辛苦辛苦哈。

**Comment by tminglei** [comment]
架构很简单啦，就是 core 项目定义了一下 pg 类型的扩展/操作，然后各个 support 在这基础上跟各种 java/scala 类型绑定、implicit、以及 plain sql 支持。

你看了代码就明白了。

**Comment by hepin1989** [comment]
好的，谢谢，我check下代码看看。
