### ISSUE TITLE
Comparison operator doesn't work with Joda DateTime

### ISSUE THREAD

**Issue by arjun-v** [tminglei/slick-pg#231]
Hi @tminglei ,

A big fan of slick-pg and have been using it for a while now. I am trying to fetch records having a timestamptz (with time zone) postgres field greater/lesser than a given timestamp and I am using Joda DateTime for this purpose.

My build.sbt
```
    "com.typesafe.slick" %% "slick" % "3.1.0",
    "com.github.tminglei" %% "slick-pg" % "0.10.1",
    "com.github.tminglei" %% "slick-pg_joda-time" % "0.10.1", 
```

My case class
```
case class Merchant (
  dateTimetz : DateTime,
  modifiedDateTimetz : DateTime
)
```

Corresponding DAO
```
 def dateTimetz      = column[DateTime] ("dateTimetz", O.SqlType("TIMESTAMPTZ"))
 def modifiedDateTimetz = column[DateTime] ("modifiedDateTimetz", O.SqlType("TIMESTAMPTZ"))
```

And then I try to fetch records the following way
```
 val query = 
      for(m <- merchants if m.modifiedDateTimetz < DateTime.now;
          mi <- merchantInfos if mi.merchantId === m.merchantId
      ) yield (mi)
```
 
And the sql statement generated is 
> select x2 from "merchants" x3, "merchantInfos" x2 where (x3."modifiedDateTimetz" < ?) and (x2."merchantId" = x3."merchantId")

I am not sure why this would be the case. As a next step, I tried to create implicit mapper
```
trait MyPostgresDriver extends PostgresDriver with PgDateSupportJoda {
     override val api = new API with DateTimeImplicits

    implicit def date2dateTime = MappedColumnType.base[org.joda.time.DateTime, Date](
	  	dateTime => new Date(dateTime.getMillis),
		date => new DateTime(date)
	)

    implicit val dateTimeColumnType = MappedColumnType.base[org.joda.time.DateTime, Timestamp](
      	{ dt => new java.sql.Timestamp(dt.getMillis) },
      	{ ts => new DateTime(ts) }
    )

  	implicit val timeZoneColumnType = MappedColumnType.base[DateTimeZone, String](
      	{ tz => tz.getID },
      	{ s => org.joda.time.DateTimeZone.forID(s) }
    )
}

object MyPostgresDriver extends MyPostgresDriver
```

I followed this by creating a sqlbuilder query (dtString = current datetime)
>  val sqlQuery: DBIO[DateTime]  = sql"""select x3."modifiedDateTimetz" from "merchants" x3, "merchantInfos" x2 where (x3."modifiedDateTimetz" < $dtString) and (x2."merchantId" = x3."merchantId")""".as[DateTime]

It throws no implicit conversion provided.

Any suggestion as to how I get this working?

Thanks
Arjun

**Comment by tminglei** [comment]
Your last case is related to plain sql, but your driver was prepared for lifted sql.
You can check the [test case](https://github.com/tminglei/slick-pg/blob/master/addons/joda-time/src/test/scala/com/github/tminglei/slickpg/PgDateSupportJodaSuite.scala#L222) for details.

--------------------------------
_BTW, why need you define your own date time mapper, and bind both sql `Date` and `Timestamp` to joda `DateTime`?_

**Comment by arjun-v** [comment]
Driver part explains what you are saying. 

But I never bothered trying all this until I realized the I couldn't directly use comparison operator. Mapping both is probably a consequence of copy pasting things here and there from different sources. 

Do you think it is possible to get the joda DateTime to directly work with comparison?

**Comment by tminglei** [comment]
I don't know exactly what you mean.
But for your last case, you should use `import MyPostgresDriver.plainAPI._` instead, as my test case showed.

**Comment by tminglei** [comment]
We can use `>` on joda `DateTime`.

In my test case, when I pasted these codes into it,
```scala
  test("terwtewr") {
    Await.result(db.run(
      DBIO.seq(
        sqlu"SET TIMEZONE TO '+8';",
        (Datetimes.schema) create,
        ///
        Datetimes forceInsertAll List(testRec1, testRec2, testRec3)
      ).andThen(
        DBIO.seq(
          Datetimes.filter(_.datetimetz > DateTime.parse("2012-05-07 11:31:06.113-05", jodaTzDateTimeFormatter).bind).to[List].result.map(
            r => r.foreach { b => println(s"datetime -> ${b.dateTimetz}") }
          )
        )
      ).andFinally(
        (Datetimes.schema) drop
      ).transactionally
    ), concurrent.duration.Duration.Inf)
  }
```
then run, and I got,
```
Testing started at 8:25 AM ...
datetime -> 2012-05-09T00:31:06.113+08:00
datetime -> 2019-11-03T18:19:03.000+08:00

Process finished with exit code 0
```

**Comment by arjun-v** [comment]
It was a silly mistake on my part that I wasn't binding the datetime value.
```
val query = 
      for(m <- merchants if m.modifiedDateTimetz < DateTime.now.*bind*;
          mi <- merchantInfos if mi.merchantId === m.merchantId
      ) yield (mi)
```

Sorry for wasting your time. I am closing this issue. Appreciate your help.

**Comment by tminglei** [comment]
_You're welcome! :-)_
