### ISSUE TITLE
Any support for circe ?

### ISSUE THREAD

**Issue by djx314** [tminglei/slick-pg#232]
circe is a greate json library for scala. It released 0.2.0 a few days ago. The start is more than 200. So are you interested in adding the slick-pg support for circe?

**Comment by tminglei** [comment]
No plan for it.
But if you sent a PR, I won't reject it. _;-)_

**Comment by djx314** [comment]
Oh, just wait for an answer.
If slick-pg won't support. I will just write a extension with slick-pg and use it for myself. Don't mind.
