### ISSUE TITLE
jsonb indexing

### ISSUE THREAD

**Issue by franckrasolo** [tminglei/slick-pg#233]
Is it possible to create the following index using `slick-pg`?

```sql
CREATE INDEX entry_idx ON entries USING GIN (entry jsonb_path_ops);
```
where `entry` is a column of type `JSONB`.

See http://www.postgresql.org/docs/9.4/static/datatype-json.html

**Comment by tminglei** [comment]
This depends on `slick`.

Checked slick's related codes, currently it only support such index syntax as below:
```
CREATE UNIQUE INDEX name ON table (column [, ...]);
```

We can't declare index type and expression (like jsonb_path_ops) yet.

**Comment by franckrasolo** [comment]
Could `TableDDLBuilder` in `ExPostgresDriver` be made to allow the addition of such indices?

In fact, for the time being, would you recommend trying to get this done inside my custom driver?

**Comment by tminglei** [comment]
Seems not, since it involves case class `Index`, `IndexBuilder` and others.

Couldn't you do it with plain SQL?

**Comment by franckrasolo** [comment]
Do you mean appending plain SQL to `TableDDLBuilder`'s `createPhase1` like this?
```scala
trait MyPostgresDriver extends ExPostgresDriver
  class TableDDLBuilder(table: Table[_]) extends super.TableDDLBuilder(table) {
    override def createPhase1 = super.createPhase1 ++ Iterable(plainSQL)
  }
}
```

**Comment by tminglei** [comment]
No, I mean you can do it like [this](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgCompositeSupportSuite.scala#L165).

**Comment by franckrasolo** [comment]
Ok, that will suffice for now. Thanks!
