### ISSUE TITLE
Source code generation with geometry types 

### ISSUE THREAD

**Issue by alfonsovng** [tminglei/slick-pg#236]
I'm trying to use the source code generation with a table which has a column of type geometric. The source is generated but it doesn't compile. The error is:

    [error] /home/alfonso/IdeaProjects/test/app/models/postgresql/Tables.scala:35: No matching Shape found.
    [error] Slick does not know how to map the given types.
    [error] Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).
    [error]   Required level: slick.lifted.FlatShapeLevel
    [error]      Source type: (slick.lifted.Rep[Int], slick.lifted.Rep[Option[String]], slick.lifted.Rep[Option[com.vividsolutions.jts.geom.Geometry]], slick.lifted.Rep[Int], slick.lifted.Rep[Int], slick.lifted.Rep[Int])
    [error]    Unpacked type: (Int, Option[String], Option[com.vividsolutions.jts.geom.Geometry], Int, Int, Int)
    [error]      Packed type: Any
    [error]     def * = (id, city, location, coffee, merch, total) <> (CoffeeHouseRow.tupled, CoffeeHouseRow.unapply)
    [error]                                                        ^
    [error] /home/alfonso/IdeaProjects/test/app/models/postgresql/Tables.scala:37: No matching Shape found.
    [error] Slick does not know how to map the given types.
    [error] Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).
    [error]   Required level: slick.lifted.FlatShapeLevel
    [error]      Source type: (slick.lifted.Rep[Option[Int]], slick.lifted.Rep[Option[String]], slick.lifted.Rep[Option[com.vividsolutions.jts.geom.Geometry]], slick.lifted.Rep[Option[Int]], slick.lifted.Rep[Option[Int]], slick.lifted.Rep[Option[Int]])
    [error]    Unpacked type: U
    [error]      Packed type: Any
    [error]     def ? = (Rep.Some(id), city, location, Rep.Some(coffee), Rep.Some(merch), Rep.Some(total)).shaped.<>({r=>import r._; _1.map(_=> CoffeeHouseRow.tupled((_1.get, _2, _3, _4.get, _5.get, _6.get)))}, (_:Any) =>  throw new Exception("Inserting into ? projection not supported."))
    [error]                                                                                                ^
    [error] /home/alfonso/IdeaProjects/test/app/models/postgresql/Tables.scala:37: not found: value _1
    [error]     def ? = (Rep.Some(id), city, location, Rep.Some(coffee), Rep.Some(merch), Rep.Some(total)).shaped.<>({r=>import r._; _1.map(_=> CoffeeHouseRow.tupled((_1.get, _2, _3, _4.get, _5.get, _6.get)))}, (_:Any) =>  throw new Exception("Inserting into ? projection not supported."))
   ... and continues...

I'm using the table CoffeeHouse defined in [https://github.com/tminglei/slick-pg/blob/master/examples/codegen-customization/src/sql/create-tables.sql](https://github.com/tminglei/slick-pg/blob/master/examples/codegen-customization/src/sql/create-tables.sql)

Is there something that I forgot to put in? The Tables.scala generated is attached.

[Tables.scala.txt](https://github.com/tminglei/slick-pg/files/55709/Tables.scala.txt)

**Comment by alfonsovng** [comment]
My fault! It seems that I just needed to sleep a few hours. I forgot to add the PostGISImplicits. Sorry and thanks for your amazing code.

**Comment by tminglei** [comment]
@alfonsovng, you're welcome! ;)

**Comment by tminglei** [comment]
@alfonsovng, you're welcome! ;)
