### ISSUE TITLE
[NOT ISSUE, but a question] Slick 3.0 bulk insert returning order for Postgres DB

### ISSUE THREAD

**Issue by ysihaoy** [tminglei/slick-pg#237]
Sorry guys, I shouldn't post here but I guess you guys will probably answer this Slick related question. I will close this as soon as I get the answer. Thanks.

Question here is:
I want to do a bulk insert using Slick 3.0 ++= function and also using returning to return the inserted objects.

I am wondering whether the return objects (Future[Seq[Something]]) has the same order as my arguments Seq[Something] (without id).

More specifically,

```
val personList: Seq[Person] = Seq(Person("name1"), Person("name2"), Person("name3"))
persons returning persons ++= personList
```

Is the result definitely be Future(Seq(Person(1, "name1"), Person(2, "name2"), Person(3, "name3")))? or can be in other result order?

Thanks.

**Comment by tminglei** [comment]
Just checked `slick` codes, and I'm sure they will be the same order as my arguments `Seq[Something]`.

**Comment by ysihaoy** [comment]
Thank you so much.
