### ISSUE TITLE
Create a Gitter Channel

### ISSUE THREAD

**Issue by mdedetrich** [tminglei/slick-pg#240]
We should set up a gitter channel, as it would help in debugging.

Also somewhat selfish reason is that I am trying to add support on slick-pg for ordered-index's, but will it looks like I will need some support (there appears to be zero documentation in this area) :smile:

**Comment by tminglei** [comment]
OK, created, and added the icon to `README.md`.
_Pls check! ;-)_

**Comment by mdedetrich** [comment]
Thanks, just posted a question there!
