### ISSUE TITLE
Undesirable runtime errors when creating custom types for Array

### ISSUE THREAD

**Issue by mdedetrich** [tminglei/slick-pg#244]
When creating custom types for pg-array's type, its possible to get runtime cast errors (i.e. the code compiles fine)

As an example (and we had this happen to us), you can define a `List[BigDecimal]` mapping like this

```scala
implicit val bigDecimalTypeWrapper = new SimpleArrayJdbcType[BigDecimal]("numeric").to(_.toList)
```

You get a class cast exception at runtime (unable to cast a `java.math.BigDecimal` to a `scala.mathBigDecimal`). The following version is what you need to do

```scala
implicit val bigDecimalTypeWrapper = new SimpleArrayJdbcType[scala.math.BigDecimal]("numeric")
  .basedOn[java.math.BigDecimal]({ scalaBigDecimal: scala.math.BigDecimal => scalaBigDecimal.bigDecimal }, 
   javaBigDecimal => scala.math.BigDecimal(javaBigDecimal)).to(_.toList)
```

Both versions compile fine. The former should throw a compile time error (or work as desired)

**Comment by tminglei** [comment]
Yes, I should enhance it.

**Comment by tminglei** [comment]
Yes, we should enhance it.

**Comment by tminglei** [comment]
Hi @mdedetrich, I added type checking logic, but it only took effect when running instead of compiling.
If you have a better idea, pls don't hesitate to tell me.

**Comment by mdedetrich** [comment]
@tminglei I will have a better look as to why this is happening, is there a reason why this happens in `slick-pg` and not `slick`.

Maybe the only thing we need to do is to add implicit conversions from all of the Java JDBC types, which is another solution to the problem

**Comment by tminglei** [comment]
@mdedetrich, you mean, define another conversion interface, and make implementations for every supported Java JDBC types?

**Comment by mdedetrich** [comment]
@tminglei Yes. So we would create default conversions for all of the JDBC types (i.e. `java.math.BigDecimal` to `scala.math.BigDecimal`, `java.lang.Long` to `scala.Long`). Any custom types should fall outside of that

**Comment by tminglei** [comment]
Ok, I'll try on it.

**Comment by tminglei** [comment]
Enhanced, you can help check it again. _Thanks!_

**Comment by tminglei** [comment]
@mdedetrich enhanced. Can you help check it again?

_Thanks!_

**Comment by mdedetrich** [comment]
@tminglei Looking at it now

**Comment by mdedetrich** [comment]
@tminglei All good, seems to be working fine now with zero problems!
