### ISSUE TITLE
Support for "At Time Zone" Timestamp Function

### ISSUE THREAD

**Issue by keithblaha** [tminglei/slick-pg#250]
Hi there- first off I want to say that slick-pg is awesome! Thanks for making such an awesome tool :)

I have a question about support for the timestamp function "at time zone" (http://www.postgresql.org/docs/current/static/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT)

I am currently trying to aggregate based on different time intervals (e.g. month, quarter, year, etc.) using the trunc function, which works perfectly. However, different users will have different time zones and I'd like to be able to trunc the dates after first transforming to the time zones of each user.

I'm using 10.2 with the joda-time library and can't find support for converting time zones anywhere in documentation though (https://github.com/tminglei/slick-pg/tree/master/core/src/main/scala/com/github/tminglei/slickpg/date).

Is there support for this, either existing or planned?

**Comment by tminglei** [comment]
@keithblaha no, there isn't. I'll add support for it.

**Comment by keithblaha** [comment]
:+1: much appreciated!

**Comment by tminglei** [comment]
@keithblaha done. You can help check. _Thanks! :-)_

**Comment by keithblaha** [comment]
@tminglei wow that was fast! Works perfectly for me publishing locally. Do you have an estimate for when I'll be able to grab from central repo?

Thank you for being so responsive!

**Comment by tminglei** [comment]
@keithblaha will be soon.

**Comment by keithblaha** [comment]
Just deployed using 0.11.0, works perfectly! Thanks for the fast work

**Comment by tminglei** [comment]
_You're welcome! :)_

**Comment by feliperazeek** [comment]
Exactly what I need, thank you @tminglei!
