### ISSUE TITLE
slick-pg is inserting UTC ZonedDateTime with a different offset

### ISSUE THREAD

**Issue by veegee** [tminglei/slick-pg#252]
If I create a `val ts = ZonedDateTime.now(ZoneOffset.UTC)`, and insert a new row whose column is of type `java.time.ZonedDateTime`, my constraint which ensures that the time zone offset is 0 fails:

```
org.postgresql.util.PSQLException: ERROR: new row for relation "entities" violates check constraint "entities_ts_created_check"
  Detail: Failing row contains (6c3f4bd8-cd28-4319-b866-c3ab0a8c56ac, null, null, 10204315917251690, null, 2016-01-01 16:05:51.337-05)
```

Note the last column timestamp is formatted as `-05` for some reason, even though the timestamp is explicitly generated with the UTC offset. Although the time itself is correct, it should be formatted as `2016-01-01 21:05:51.337+00` not `2016-01-01 16:05:51.337-05`.

This is really strange because calling `toZonedDateTimeOrInfinity(ts)` is returning a correctly-formatted string with a UTC offset.

**Comment by veegee** [comment]
Update: setting `connectionInitSql = "SET TIME ZONE 'UTC';"` in my database config seems to solve the issue. It looks like JDBC sets all connections to use local timezone by default, which converts the ZonedDateTime object for some reason.

Is there another way around this?

**Comment by tminglei** [comment]
@veegee I haven't found another way yet.
