### ISSUE TITLE
How do I insert a tsvector via to_tsvector()?

### ISSUE THREAD

**Issue by veegee** [tminglei/slick-pg#255]
I generated a table model (`MyTable` and `MyTableRow`) using a customized code generator, and the table contains a `TsVector` column. How do I create a new `MyTableRow` record such that when the row is inserted, its `tsvector` column contains correct data from the output of `to_tsvector()`?

Doing `MyTableRow(tsVector('some text'))` does not work because `tsVector()`/`toTsVector()` return `Rep[TsVector]`, but the type of the column is `TsVector`.

**Comment by veegee** [comment]
Are there any thoughts on this?

**Comment by tminglei** [comment]
@veegee `slick` doesn't support that, since it can't construct a insert sql like `insert into mytable (..., search) values (..., to_tsvector( ? ))`, then use `PreparedStatement` to set the parameters.

`PreparedStatement` doesn't allow to set a parameter like `to_tsvector('my text')` to be set.
