### ISSUE TITLE
Cannot use bytea in plain sql

### ISSUE THREAD

**Issue by terro** [tminglei/slick-pg#260]
I have added `PgHStoreSupport`, `ArrayImplicits`, and `SimpleArrayPlainImplicits`. But it fails to compile plain sql with an `Array[Byte]` parameter with the following compilation error:

`could not find implicit value for parameter e: slick.jdbc.SetParameter[Array[Byte]]`

**Comment by tminglei** [comment]
It may be related to your project details. Can you provide more details, such as your custom driver definition and usage codes (including imports)?

**Comment by terro** [comment]
I have a function for upsert:

```
CREATE FUNCTION upsert_data(id INT, data BYTEA, updateTime TIMESTAMP)
  RETURNS INT AS $$
DECLARE
  id INTEGER;
BEGIN
  LOOP
    UPDATE "TABLE" SET "DATA" = data, "UPDATE_TIME" = updateTime WHERE "ID" = id;
    IF FOUND THEN
      SELECT "ID" FROM "TABLE" WHERE "ID" = id INTO id;
      RETURN id;
    END IF;
    BEGIN
      INSERT INTO "TABLE" VALUES (id, data, updateTime) RETURNING "ID" INTO id;
      RETURN id;
    EXCEPTION WHEN unique_violation THEN
    END;
  END LOOP;
END;
$$ LANGUAGE plpgsql;
```
When I invoke this function in plain sql using `sql"SELECT upsert_card($id, $data, $updateTime)".as[Int]`, where `data` if of type `Array[Byte]`, I met this compilation error:

```
could not find implicit value for parameter e: slick.jdbc.SetParameter[Array[Byte]]
```

Thanks!

**Comment by tminglei** [comment]
@terro it's complaining `could not find ...`, but I didn't see your usage context codes, which lead to I can't point out what you lost.

**Comment by terro** [comment]
This is my PGDriver class:

```
package dao.impl

import com.github.tminglei.slickpg._

trait PGDriver extends ExPostgresDriver
                  with PgArraySupport
                  with PgDate2Support
                  with PgHStoreSupport
                  with PgEnumSupport {

  override val api = PgAPI

  object PgAPI extends API with DateTimeImplicits
                           with Date2DateTimePlainImplicits
                           with HStoreImplicits
}

object PGDriver extends PGDriver
```

And here is the context:

```
package dao.impl

import java.time.LocalDateTime

import dao.DataDAO
import dao.impl.PGDriver.api._
import play.api.Application
import play.api.db.slick._
import slick.driver.JdbcProfile

import scala.concurrent.Future

final class PGDataDAO(implicit app: Application) extends HasDatabaseConfig[JdbcProfile] with DataDAO {
  protected val dbConfig = DatabaseConfigProvider.get[JdbcProfile]

  override def updateData(id: Int, data: Array[Byte], updateTime: LocalDateTime): Future[Int] = {
    db.run(sql"SELECT upsert_card($id, $data, $updateTime)".as[Int].head)
  }
}
```

Thanks a lot!

**Comment by tminglei** [comment]
pls change `... extends HasDatabaseConfig[JdbcProfile]` to `... extends HasDatabaseConfig[PGDriver]`.

**Comment by terro** [comment]
Thanks for your help. I've changed `extends` and mixed `SimpleArrayPlainImplicits`, however I still met the same compilation error.

**Comment by tminglei** [comment]
My fault, there isn't plain sql `Array[Byte]` support in `slick-pg`.
There is built-in support for JdbcType `Array[Byte]` in `slick`, so I forgot to do it for plain sql, and nobody pointed it out to me.

Just added plain sql support for `Array[Byte]`, and released slick-pg `v0.11.3`, pls update your project dependencies to use it.

_p.s. BTW, strictly, `Array[Byte]` is not a pg `ARRAY`. It maps to `bytea` instead of `byte ARRAY`._

**Comment by terro** [comment]
Thanks for your very fast fix!

**Comment by tminglei** [comment]
_You're welcome!_
