### ISSUE TITLE
Can't find the slick-pg_circe-json dependency in maven repository

### ISSUE THREAD

**Issue by djx314** [tminglei/slick-pg#265]
I add the dependency in build.sbt
```scala
"com.github.tminglei" %% "slick-pg_circe-json" % "0.12.0"
```
It seems to that sbt can't find the denpendency.
I search it in <http://search.maven.org/#search|ga|1|com.github.tminglei> and can't find and dependency about circe, any fix?

**Comment by djx314** [comment]
Oh! I just see other denpendency with version "0.12.0". All of the slick-pg "0.12.0" denpendencies is not avaliable now.
Sorry for creating a stupid issue.

**Comment by tminglei** [comment]
But you can found them with `https://oss.sonatype.org/#nexus-search;quick~slick-pg`.
_Strange!_

**Comment by tminglei** [comment]
Let me try whether it can be fixed by releasing.

**Comment by djx314** [comment]
In search.maven.org I can't find slick-pg 0.12.0, but in repo1.maven.org I can just find other jars, only slick-pg_circe-json is missing. @tminglei

**Comment by tminglei** [comment]
oh, it's unbelievable. I missed check that!!!

**Comment by tminglei** [comment]
Released again. Pls help check some time later. :-)

**Comment by djx314** [comment]
Already updated to 0.12.0 with slick-pg_circe-json successfully.

**Comment by tminglei** [comment]
^^
