### ISSUE TITLE
  PgArraySupportSuite with a test case using plain api with a custom type

### ISSUE THREAD

**Issue by mzumbin** [tminglei/slick-pg#272]
Hi, I'm trying to use a custom type with the array support and make queries using plain sql. The array suite tests do has a test case using custom type with lift support, but doesn't has one using plain api.
A test case  using plain api with a custom type  would be very helpful.

**Comment by tminglei** [comment]
@mzumbin added test case for plain sql array support of custom type, pls check.

**Comment by mzumbin** [comment]
Thank you for your for your reply, it helps me a lot!

**Comment by tminglei** [comment]
_You're welcome! :-)_
