### ISSUE TITLE
No implicit format for Option[Point] available.

### ISSUE THREAD

**Issue by xpete** [tminglei/slick-pg#273]
I'am getting the error "No implicit format for Option[Point] available."
how can I add an implicit to support Option[Point]?

Shouldn't this be supported on PgPostGISSupport?

**Comment by xpete** [comment]
Forget about this. Already fixed the problem.

**Comment by leoromanovsky** [comment]
What'd you end up doing?

**Comment by xpete** [comment]
Created an implicit like this:
  implicit val pointFormatter:Format[Point] = Json.format[Point]
It's only need for play json.
