### ISSUE TITLE
Feature request: Add support for array_agg

### ISSUE THREAD

**Issue by Ajk4** [tminglei/slick-pg#276]
I'm refering to function `array_agg` which aggregates results into an array. It's described at http://www.postgresql.org/docs/9.4/static/functions-aggregate.html page.

Could we add support for this function?

**Comment by tminglei** [comment]
I ever did a try in slick/slick#796, but it's not a slick/collection style.

_Maybe, I can try it again, just in slick-pg side._

**Comment by tminglei** [comment]
Hi @Ajk4 I added aggregate and window function support. Pls check latest release/codes for details.

**Comment by Ajk4** [comment]
Thanks! I will surely use to anytime soon!
