### ISSUE TITLE
org.postgresql.util.PSQLException: Unknown type int[]

### ISSUE THREAD

**Issue by windy1** [tminglei/slick-pg#277]
https://gist.github.com/windy1/a6c67ac7da02792af59f5a6b3c68388a

Perhaps there is a better way to go about this but I'm attempting to add an implicit conversion for a `List` of an `Enumeration` I have and I'm getting the above error when trying to use a `AdvancedArrayJdbcType`. I've included the relevant classes and error log in the link above.

**Comment by tminglei** [comment]
Try to use a more specific one: `int2`, `int4`, `int8`, or `smallint`/`integer`/`bigint`.

**Comment by windy1** [comment]
Ah that did the trick. Thanks for your speedy reply.
