### ISSUE TITLE
PgRangeSupport Crashes When Parsing Empty Ranges

### ISSUE THREAD

**Issue by jeffreyr-porch** [tminglei/slick-pg#279]
As outlined in [PostgreSQL Documentation: Range Types](http://www.postgresql.org/docs/9.3/static/rangetypes.html), empty ranges are normalized to the value `empty`:
```
-- includes no points (and will be normalized to 'empty')
SELECT '[4,4)'::int4range;
```

Unfortunately, `PgRangeSupport` does not support empty ranges, giving a `MatchError` in `mkRangeFn` when it hits the string `empty`.

This function needs to be updated to handle this special case constant. A reasonable behavior would be to return an empty range (e.g. `[0,0)`).

**Comment by jeffreyr-porch** [comment]
For reference, the top of the trace is:
```
ERROR [2016-05-10 23:01:44,854] com.porch.commons.service.ResourceResponse: Transforming unexpected error into status=500; message=Internal Server Error
! scala.MatchError: empty (of class java.lang.String)
! at com.github.tminglei.slickpg.PgRangeSupportUtils$$anonfun$mkRangeFn$1.apply(PgRangeSupport.scala:135) ~[slick-pg_2.11-0.11.2.jar:0.11.2]
! at com.github.tminglei.slickpg.PgRangeSupportUtils$$anonfun$mkRangeFn$1.apply(PgRangeSupport.scala:135) ~[slick-pg_2.11-0.11.2.jar:0.11.2]
! at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.getValue(PgCommonJdbcTypes.scala:23) ~[slick-pg_core_2.11-0.11.2.jar:0.11.2]
```

**Comment by tminglei** [comment]
Yes, let's enhance it.

**Comment by jeffreyr-porch** [comment]
Cool, thanks.

**Comment by tminglei** [comment]
@jeffreyr-porch fixed, can you help check it?
