### ISSUE TITLE
<@: do not work the same way as postgres <@ operator

### ISSUE THREAD

**Issue by vkorbut** [tminglei/slick-pg#280]
`<@:` works exactly the same way as `@>`. It matches ancestors. 
But postgres `<@` matches children.

The problem may be here: 
https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/ltree/PgLTreeExtensions.scala#L42

There should be 
```scala
 om.column(LTreeLibrary.<@, n, e.toNode) 
```

Also there are errors in documentation [here](https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/ltree/README.md):

`'Top.Science' @> 'Top.Science.Astronomy'` returns `false`
`'Top.Science' <@ 'Top.Science.Astronomy'` return `true`

Howewer these query return opposite values:
```sql
select cast('Top.Science' as LTree) @>  'Top.Science.Astronomy'
```
returns `true`.
```sql 
select cast('Top.Science' as LTree) <@  'Top.Science.Astronomy'
```
returns `false`

**Comment by tminglei** [comment]
@vkorbut yes, you're right. I'll correct it asap.

**Comment by tminglei** [comment]
@vkorbut fixed, can you help check?
