### ISSUE TITLE
Question: How to compare two timestamps (using joda.DateTime) in the database?

### ISSUE THREAD

**Issue by asazernik** [tminglei/slick-pg#283]
From slick-codegen I get a table looking more or less like the following (I've cut out most of the columns):

```scala
case class TestTableRow(id: Int, flat: Boolean, ts: Option[DateTime])
class TestTable(_tableTag: Tag) extends Table[TestTableRow](_tableTag, "test_table") {
  def * = (id, flag, ts) <> (TestTableRow.tupled, TestTableRow.unapply)
  val id: Rep[Int] = column[Int]("id", O.AutoInc, O.PrimaryKey)
  val flag: Rep[Boolean] = column[Boolean]("flag")
  val ts: Rep[Option[DateTime]] = column[Option[DateTime]]("ts", O.Default(None))
}
lazy val TestTable = new TableQuery(tag => new TestTable(tag))
```

I'm trying to perform the equivalent of

```sql
SELECT t1.id, t2.id from test_table where t1.flag and not t2.flag and t1.ts < t2.ts
```

However, the '<' method is not defined on `Rep[Option[DateTime]]` or `Rep[DateTime]`, and `isBefore` expects a constant DateTime value. Is there some way to do this?

**Comment by tminglei** [comment]
@asazernik `slick` has built-in support for `<`, which can be applied to any `Rep[T]`.
_You can try it._

**Comment by asazernik** [comment]
Hmmm. I end up getting `/opt/parsley/app/util/StdlibSync.scala:108: value < is not a member of models.Tables.profile.api.Rep[Option[org.joda.time.DateTime]]`. :-\

**Comment by asazernik** [comment]
(That was what I'd originally tried.)

**Comment by asazernik** [comment]
Ah. Tried doing the implicit conversion manually, and got:

```
/opt/parsley/app/util/StdlibSync.scala:108: could not find implicit value for evidence parameter of type slick.ast.BaseTypedType[Option[org.joda.time.DateTime]]
[error]         columnExtensionMethods(userProduct.lastStdlibExpansion) < stdlibProduct.lastStdlibExpansion
```

**Comment by asazernik** [comment]
Ignore me, I'm dumb. And using a different library.

*runs and hides*
