### ISSUE TITLE
Outdated example codegen-customization

### ISSUE THREAD

**Issue by chuckyouliu** [tminglei/slick-pg#284]
Changing codegen's dependencies:
slick/slick-codegen 3.0.0 -> 3.1.1
slick-pg 0.9.0 -> 0.13.0

adding additional dependencies:
"com.github.tminglei" %% "slick-pg_play-json" % "0.13.0",
"com.github.tminglei" %% "slick-pg_joda-time" % "0.13.0",
"com.github.tminglei" %% "slick-pg_jts" % "0.13.0"

changing MyPostgresDriver's "with PgDate2Support" trait to PgDateSupport (error thrown otherwise).

The following changes causes no Tables.scala file to be written, although the activator gen-tables successfully completes. Has someone set up the codegen for these versions? Also tried with most recent 0.14.1, same issue.

**Comment by tminglei** [comment]
I'll check it.

**Comment by tminglei** [comment]
@chuckyouliu I just updated codegen example project, pls check it.
_Thanks!_

**Comment by chuckyouliu** [comment]
Really appreciate the quick turnaround, thanks!

**Comment by tminglei** [comment]
U welcome _;-)_
