### ISSUE TITLE
Update Circe dependency

### ISSUE THREAD

**Issue by callicles** [tminglei/slick-pg#290]
The Json implicit based on Circe is bundled with `0.3`.  

`slick-pg` in version `0.14.1` worked with circe version `0.5.0-M2` but now `slick-pg` in version `0.14.2` breaks with circe `0.5.0-M2`.

Would be nice to update the dependency.
Thx

**Comment by tminglei** [comment]
@callicles it's already upgraded to `v0.4.1` in slick-pg `v0.15.0-M1`, and will be upgraded to latest stable version in next release.

**Comment by callicles** [comment]
@tminglei nice tanks !
