### ISSUE TITLE
String array mapping mishandles blank strings

### ISSUE THREAD

**Issue by jonathancrosmer** [tminglei/slick-pg#294]
When a sequence has multiple elements, and at least one element is a blank (empty, or all whitespace) string, the generated SQL fails due to the array literal being incorrect.  

`implicit val StringSeqTypeMapper = new SimpleArrayJdbcType[String]("text")`

A single-element array is fine, because the generated literal is like `'{   }'`, which is acceptable even though the spaces aren't quoted.  But if the literal has multiple elements, like `'{     ,     }'` it fails: "ERROR:  malformed array literal".  If the strings aren't blank and contain spaces, like `a b c`, they are apparently properly quoted like `'{"a b c"}'`.  My workaround was to prepend an arbitrary character to every element (simple, and our arrays tend to be very small):

```
implicit val StringSeqTypeMapper = new AdvancedArrayJdbcType[String](
      "text",
      (s) => utils.SimpleArrayUtils.fromString[String]({ x => x.drop(1) })(s).orNull,
      (v) => utils.SimpleArrayUtils.mkString[String]({ x => "_" + x
      })(v)
    )
```

**Comment by tminglei** [comment]
@jonathancrosmer fixed, pls help check. Thanks!

**Comment by jonathancrosmer** [comment]
Wow, thanks for fixing it so fast.  You are awesome.
I'm having trouble testing it.  I tried cloning and building `slick-pg`, then running `package` and copying all the jars to the `lib` directory of my own sbt project.  It is definitely on the classpath, according to "-Ylog-classpath".   I think maybe I built it wrong; maybe it needs some other dependencies?  Can you tell what this means?

```
[error] /opt/projects/rzops/rz-ops-server/src/main/scala/com/e2sd/repository/postgres/RedzonePostgresDriver.scala:10: not found: type ExPostgresDriver
[error] trait RedzonePostgresDriver extends ExPostgresDriver
[error]                                     ^
[error] missing or invalid dependency detected while loading class file 'PgArraySupport.class'.
[error] Could not access type PgArrayExtensions in value com.github.tminglei.slickpg.array,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'PgArraySupport.class' was compiled against an incompatible version of com.github.tminglei.slickpg.array.
[error] missing or invalid dependency detected while loading class file 'PgArraySupport.class'.
```

**Comment by jonathancrosmer** [comment]
Nevermind, I was able to use `sbt publish-local` to access the build of `master` branch.  It does appear to have fixed our problem.  Nice work, thanks!!
Do you think it is ok to use this build in production?

**Comment by tminglei** [comment]
It's fine to be used in production.
_After accumulated some more changes, I'll release it._

**Comment by jonathancrosmer** [comment]
Thanks again.  Great library!
