### ISSUE TITLE
column[Option[JsValue]] read null when Option is None

### ISSUE THREAD

**Issue by scweang** [tminglei/slick-pg#297]
I have figured out that this problem is due to 
```scala
 trait PlayJsonImplicits {
    implicit val playJsonTypeMapper: JdbcType[JsValue] =
      new GenericJdbcType[JsValue](
        pgjson,
        (v) => Json.parse(v),
        (v) => Json.stringify(v),
        zero = JsNull,
        hasLiteralForm = false
      )

    implicit def playJsonColumnExtensionMethods(c: Rep[JsValue]) = {
      new JsonColumnExtensionMethods[JsValue, JsValue](c)
    }
    implicit def playJsonOptionColumnExtensionMethods(c: Rep[Option[JsValue]]) = {
      new JsonColumnExtensionMethods[JsValue, Option[JsValue]](c)
    }
  }
```

And I've changed the ```zero = JsNull``` to ```zero = null``` then my old code work. It is because when get across null value from database, slick-pg will consider it as JsNull, which is not a null value, so Option will have Some(JsNull). After that, JsNull in Some is transferred to null, so we've got Some(null) problem, which is really inconvenient for us to handle. Hope this could be fix. Thx.

**Comment by tminglei** [comment]
Well, the null default mechanism was already discarded by slick. So we'd better remove it too.

**Comment by tminglei** [comment]
Removed null default in 7d4b0dd.

**Comment by scweang** [comment]
Thanks!

**Comment by caeus** [comment]
Suffering this... Is there a version where this' been already fixed?

**Comment by tminglei** [comment]
@caeus the removing change was released in slick-pg v0.15.0-M2, you can try it.

**Comment by haya14busa** [comment]
Hi there @tminglei, 

Do you have any plan to backport the patch to 0.14.x?

v0.15.0-M3 is pre-release and it requires updating slick version to v3.2.0-M2 as well.

**Comment by tminglei** [comment]
Hi @haya14busa, no plan to backport to slick-pg 0.14.x, since zero value is an built-in mechanism before slick v3.2.0, and slick-pg followed that for a long time.

**Comment by haya14busa** [comment]
Thank you for the reply.

Hmm... ok I understood. I'll deal with the problem by defining wrapper trait of PlayJsonImplicits to make `zero = JsNull` to `zero = null`
