### ISSUE TITLE
Implicits for date2 and postgis column types not working.

### ISSUE THREAD

**Issue by jan0sch** [tminglei/slick-pg#303]
Hi,

I've come accross an issue in a project of ours that should use column types that are supposed to be supported by date2 and jts are not compiling. I created a very small sample project that illustrates the issue: https://github.com/jan0sch/slick-pg-test

If you clone it and execute `sbt clean compile` then you'll get compiler errors about missing implicits:

```text
[error] .../src/main/scala/Tables.scala:13: could not find implicit value for parameter tt: slick.ast.TypedType[java.time.ZonedDateTime]
[error]     def z = column[ZonedDateTime]("z")
[error]                                  ^
[error] .../src/main/scala/Tables.scala:16: could not find implicit value for parameter tt: slick.ast.TypedType[com.vividsolutions.jts.geom.Point]
[error]     def p = column[Point]("p")
[error]                          ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
```

However if I clone the whole slick-pg repo and execute the tests there everything compiles fine. But everytime I've tried so far using custom column types never compiled. :cry: 

Any ideas what I am missing?

Regards,

Jens

**Comment by tminglei** [comment]
This is the codes you used to override `api`:
```scala
override val api: API = new API with DateTimeImplicits with PostGISImplicits with PostGISAssistants {}
```

Change it to,
```scala
override val api = new API with DateTimeImplicits with PostGISImplicits with PostGISAssistants {}
```

Can resolve the problem.

_Explain: the `API` in `api: API` excluded our date2 and postgis extensions._

**Comment by jan0sch** [comment]
Many thanks that was it. The type annotation `: API` was added by IntelliJ Idea when I used the override methods functionality of it. May this be worth mentioning in the readme?

**Comment by tminglei** [comment]
It's not a `slick-pg` related issue, I don't like to mention it in the README.

_Glad to hear it resolved your problem. :-)_
