### ISSUE TITLE
Support for slick 3.2

### ISSUE THREAD

**Issue by chris-baynes** [tminglei/slick-pg#304]
Is there any plan to support slick v3.2 in the near future? 
There currently isn't a stable release, and there are some changes to internals (e.g. drivers are now referred to as profiles).

We currently rely on the 3.2 release for better handling of UUIDs. It would be great to be able to use slick-pg with that.

**Comment by djx314** [comment]
slick-pg 0.15.0-M2 is out. It's base on slick 3.2.0-M1. You can use it in your application.

**Comment by chris-baynes** [comment]
Thanks, I wasn't aware of the `next` branch
