### ISSUE TITLE
Upsert fails when a table definition is one primary key and one auto-inc column

### ISSUE THREAD

**Issue by pgoggijr** [tminglei/slick-pg#309]
If a table is defined as such:

```
TestClass(autoInc: Option[Int], primaryKey: String)
class TestTable(tag: Tag) extends Table[TestClass](tag, "test_table") {
  def autoInc = column[Option[Int]]("auto_inc", O.AutoInc)
  def primaryKey = column[String]("primary_key", O.PrimaryKey)
  def * = (autoInc, primaryKey) <> (TestClass.tupled, TestClass.unapply
}
```

The generated query for an insertOrUpdate query is syntactically incorrect:
```
insert into "test_table" ("primary_key") values (?) 
on conflict ("primary_key") do nothing where ? is null or ?=?
```
and results in the following org.postgresql.util.PSQLException:
```
ERROR: syntax error at or near "where"
  Position: 92
```

The where clause should not be present, as the action specified is do nothing and shouldn't have any conditions. 

This error does not appear when autoInc is not labeled an auto-incrementing column, or when primaryKey is the solitary column in the table.

My hunch is that this can probably be fixed in ExPostgresDriver.scala on lines 110-111 by stronger filtering on softNames and nonPkAutoIncSyms.

**Comment by tminglei** [comment]
Hi @pgoggijr fixed, you can help check.
_Thanks! :+1:_
