### ISSUE TITLE
Querying field of Option[JsValue]

### ISSUE THREAD

**Issue by arussel** [tminglei/slick-pg#316]
I have a colum[Option[JsValue]] and need to do a query like:

`table.jsonColumnOpt+>>'value' === "the value"`

but this returns a Rep[Option[Boolean]] instead of a Rep[Boolean]. Is there a way to make it returns a Rep[Boolean] ?

Note that I've been using a workaround until now with:

`(table.jsonColumnOpt+>>'value' === "the value").getOrElse(false:Rep[Boolean])`

but this create a `coalese(..., false)` postgres query which can't use our index on `table.jsonColumnOpt+>>'value'`

**Comment by tminglei** [comment]
Have you tried `table.jsonColumnOpt+>>'value' === Some("the value")`

**Comment by arussel** [comment]
It gives me a compilation error (using `table.jsonColumnOpt+>>'value' === Some("the value".bind)`):

> type mismatch;
> [error]  found   : Some[slick.lifted.Rep[String]]
> [error]  required: slick.lifted.Rep[?]

**Comment by tminglei** [comment]
Try `table.jsonColumnOpt+>>'value' === Some("the value").bind` instead of `table.jsonColumnOpt+>>'value' === Some("the value".bind)`.

**Comment by arussel** [comment]
I had try that one already :-)

> value bind is not a member of Some[String]

**Comment by tminglei** [comment]
Well, how about `table.jsonColumnOpt+>>'value' === "the value".bind.?` ?

**Comment by tminglei** [comment]
Well, I just tried on my local, `table.jsonColumnOpt.+>>("value") === "the value"` should be OK.

**Comment by arussel** [comment]
@tminglei thanks a lot, I got my implicits mix up.

**Comment by tminglei** [comment]
_You're welcome! :-)_
