### ISSUE TITLE
Support for `ILIKE`

### ISSUE THREAD

**Issue by raimohanska** [tminglei/slick-pg#321]
Would be nice to have `ILIKE` in addition to regular `LIKE`, for case-insensitive like-queries.

**Comment by tminglei** [comment]
@raimohanska just did some refactoring and released v0.14.4 and v0.15.0-M3, will continue to implement this.

**Comment by tminglei** [comment]
@raimohanska implemented, you can help check. _Thanks!_

**Comment by raimohanska** [comment]
I tried but unfortunately I'm unable to get this revision using jitpack-io to my Maven project that uses Scala 2.11...

**Comment by tminglei** [comment]
It's not released yet. You need build it on your local.

**Comment by raimohanska** [comment]
I upgraded to scala 2.12 and can currently *almost* compile my project. The only remaining issue is:

While trying to update to the newest version, I run into an issue with bind.any: previously I was able to do val things: List[JValue] = ... ; things.bind.any and use this in a query. Now I get "value bind is not a member of List[org.json4s.JValue]". Any idea what could have happened?

Having fixed this, I could move to working on ILIKE...

**Comment by raimohanska** [comment]
To be more exact, with v0.15.0-M3 (or later), these three compile:

        List("asdf").bind.any
        List(1).bind.any
        parse(s"""[]""").bind

While these two don't

        List(parse(s"""[]""")).bind
        List(parse(s"""[]""")).bind.any

The error message is 'value bind is not a member of List[org.json4s.JValue]'

**Comment by tminglei** [comment]
[Here](https://github.com/tminglei/slick-pg/commit/56ad9e0b4576e9410243249c367f45310d882328)'s the changes that I made to support scala v2.12, maybe you can check and adjust if necessary.

**Comment by raimohanska** [comment]
Thanks a ton! My project finally compiles. The best xmax present I got this year :)

**Comment by raimohanska** [comment]
Pls add a Donate button on your project page, I owe you a beer.

**Comment by raimohanska** [comment]
I now use `ilike` in my project and it works like a charm!

**Comment by tminglei** [comment]
Glad to hear that! _You're welcome! ;-)_
