### ISSUE TITLE
Question : How to transform to another SRID

### ISSUE THREAD

**Issue by neljaj** [tminglei/slick-pg#323]
Thanks for a very useful extension.

I need some help please - I need to do the following query : 

```
select * from MYTABLE
 WHERE ST_DWithin(
 ST_Transform(MYTABLE.coordinates,900913),
 ST_Transform(ST_GeomFromText('POINT(-33.73378 18.97523)', 4326),900913),
 70000);
```
I have a problem doing the 2nd ST_Transform

I got as far as : 

_variablePoint is of type Point_

`slickMyTable.filter(_.coordinates.transform(900913).dWithin(myPointValue, varDistance))`

So how do I do a transform to SRID  900913  on myPointValue?

Your help is appreciated.

**Comment by tminglei** [comment]
try
```scala
slickMyTable.filter( _.coordinates.transform(900913) .dWithin( geomFromText("POINT(-33.73378 18.97523)", Some(4326)).transform(900913),  70000)  )
```

**Comment by neljaj** [comment]
Thanks for the speedy answer. That pointed me in the right direction.

**Comment by tminglei** [comment]
You're welcome!
