### ISSUE TITLE
Ambiguous implicit values for BYTEA columns (Array[Byte])

### ISSUE THREAD

**Issue by vanDonselaar** [tminglei/slick-pg#325]
Steps to reproduce:
1. Checkout `slick-pg` master
2. `cd slick-pg/examples/codegen-customization`
3. Edit `src/sql/create-tables.sql` and add a bytea column to one of the tables:
```patch
--- examples/codegen-customization/src/sql/create-tables.sql	(revision 4f3ea94c46cf886e8a829df0965ca05d1f0b6ebf)
+++ examples/codegen-customization/src/sql/create-tables.sql	(revision )
@@ -14,6 +14,7 @@
   PRICE numeric(10,2) NOT NULL,
   SALES integer NOT NULL,
   TOTAL integer NOT NULL,
+  arrofbyteproblem bytea not null,
   PRIMARY KEY (NAME),
   FOREIGN KEY (SUP_ID) REFERENCES SUPPLIER (ID));
```
4. Run `sbt compile`
5. Compile error (ambiguous implicit values):
```
[error] slick-pg/examples/codegen-customization/target/scala-2.11/src_managed/slick/demo/Tables.scala:32: ambiguous implicit values:
[error]  both value getByteArray in trait API of type => slick.jdbc.GetResult[Array[Byte]]
[error]  and value e3 of type slick.jdbc.GetResult[Array[Byte]]
[error]  match expected type slick.jdbc.GetResult[Array[Byte]]
[error]     CoffeeRow.tupled((<<[String], <<[Int], <<[scala.math.BigDecimal], <<[Int], <<[Int], <<[Array[Byte]]))
[error]                                                                                           ^
[error] one error found
[error] (root/compile:compileIncremental) Compilation failed
[error] Total time: 10 s, completed Jan 23, 2017 8:53:51 AM
```
I think this is caused by https://github.com/tminglei/slick-pg/blob/17917c9353e75073e18016128d9cf821fa9db749/core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala#L42 which introduces a second implicit for `Array[Byte]`.

Proposed solution:
Move the implicit from the `API` trait to a separate trait that can be mixed in manually if needed.

**Comment by tminglei** [comment]
Hi @vanDonselaar fixed according to your suggestion. _Thanks! :+1:_

**Comment by vanDonselaar** [comment]
That was quick. Thanks. I wanted to be sure you agreed upon the proposed solution before creating a PR, but you've already fixed it. Great. :+1:
