### ISSUE TITLE
java.time.LocalDate compare

### ISSUE THREAD

**Issue by sanjarbek** [tminglei/slick-pg#326]
I am trying to filter by start_date and end_date columns which have sql DATE type. In Scala I am using java.time.LocalDate. How to do it?

**Comment by tminglei** [comment]
@sanjarbek you can follow these [test case codes](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgDate2SupportSuite.scala) for how to use it.

**Comment by sanjarbek** [comment]
As I understand when using java.time.LocalDate we can't use date columns with operators =, !=, <, >, between? Test case codes don't have this cases. My slick understanding is not well. Stackoverflow suggestion was using plain sql. My current code is filtering after fetching data. It seems to me both of them is not good.

**Comment by tminglei** [comment]
@sanjarbek slick has built-in `=, !=, <, >, between` support for any column type.

**Comment by sanjarbek** [comment]
> @sanjarbek slick has built-in =, !=, <, >, between support for any column type, so slick-pg needn't any test case for these.
Yesterday I found solution to my problem
`case MatchMode.startsWith => columnName match {
            case "orderDate" =>
              orderQuery.filter(_._2.asColumnOf[Date] === Date.valueOf(LocalDate.parse(filterMetaData.value)) )
            case _ => orderQuery
          }`
How do you made filtering by date for LocalDate?

**Comment by tminglei** [comment]
You can use `LocalDate` with `=, !=, <, >, between` directly, why cast it to `Date`?

**Comment by sanjarbek** [comment]
@tminglei because I didn't import implicit date2DateTypeMapper to automatically convert LocalDate. But now thanks to your help I understand it. Thank you very much.
