### ISSUE TITLE
Possible regression in composite support

### ISSUE THREAD

**Issue by DylanArnold** [tminglei/slick-pg#331]
Hi I recently upgraded from `0.10.0-M2` to `0.15.0-M4`

At the same time I upgraded to slick `3.2.0-RC1`

When I do a filter such as `query.filter(_.myComposite < someCompositeValue)` I now get an error from PostgreSQL `input of anonymous composite types is not implemented`.

I'm trying to track down the problem now but I believe the composite type isn't being registered correctly and the query passed to PostgreSQL is incorrect.

I set a breakpoint in `org.postgresql.jdbc.PgStatement` for my query before and afterwards and noticed that the `PgPreparedStatement` differs in the `queryParameters` `paramTypes`.

Before in `0.10.0-M2` 
The paramType for the composite value is `2479208`

![working stack](https://cloud.githubusercontent.com/assets/437338/23289590/ac5ce1c8-faaf-11e6-80d2-50430dfdbef4.png)

Afterwards in `0.15.0-M4`
The paramType for the composite value is `0`

![bug stack](https://cloud.githubusercontent.com/assets/437338/23289582/a17dd1e0-faaf-11e6-9699-e80e09d7c2bf.png)

Could this be the problem? Are these related to the `sqlType` parameter inside `GenericJdbcType` when calling `createCompositeJdbcType` ?

This bug actually made it onto production so any help would be greatly appreciated. Where can I set breakpoints to help find this ?

**Comment by tminglei** [comment]
Hi @DylanArnold, the cause is that pg didn't cast the input value string to the composite type. For this, I can't change it.

But you can follow the way I used in the above commit to bypass it.

**Comment by DylanArnold** [comment]
@tminglei This fix worked perfectly. Thank you!
