### ISSUE TITLE
Update to Slick 3.2 

### ISSUE THREAD

**Issue by agarbutt** [tminglei/slick-pg#333]
Slick has released version 3.2.0. 
See http://slick.lightbend.com/news/2017/02/24/slick-3.2.0-released.html

Update to the 3.2 release version of Slick.

**Comment by tminglei** [comment]
Already upgraded to slick 3.2.0, but can't publish it to central maven repository because of the Government's network blockade.

**Comment by Diagoras** [comment]
@tminglei That sucks. Is there anything that can be done? VPN?

**Comment by agarbutt** [comment]
I know I can publish from my location if that helps.

**Comment by tminglei** [comment]
@agarbutt no, you can't help, since you haven't the signature key.

**Comment by tminglei** [comment]
Successfully released slick-pg v0.15.0-RC.
