### ISSUE TITLE
ST_AsEncodedPolyline support

### ISSUE THREAD

**Issue by kiambogo** [tminglei/slick-pg#334]
Hello,

Is it possible (or on the roadmap) to support the geometry output encoded polyline? 
http://postgis.net/docs/ST_AsEncodedPolyline.html

**Comment by tminglei** [comment]
It can be added on command.
Is there any method that must be used together with? If there is, I can add it together.

**Comment by kiambogo** [comment]
Ideally I'd like to be able to have generated SQL like 

    SELECT ST_AsEncodedPolyline(r.the_geom) FROM tri_route_1((SELECT * from tri_nearest(?, ?)), (SELECT * FROM tri_nearest(?,?))) r;

(tri_route here is a function https://github.com/kiambogo/docker-images/blob/master/postgres_pgrouting/dependencies/pgrouting.sql)

Does that answer your question?

**Comment by tminglei** [comment]
OK. I don't care non postgis function here.
So what you want is only `ST_AsEncodedPolyline`, right?

**Comment by tminglei** [comment]
Added support for `ST_AsEncodedPolyline` and `ST_LineFromEncodedPolyline`, you can help check.
_Thanks!_
