### ISSUE TITLE
How to treat null value in column of jsonb type as None using json4s?

### ISSUE THREAD

**Issue by rogern** [tminglei/slick-pg#336]
When reading null values from a jsonb column I get Option value with JNull instead of None as I would expect.
Is there any configuration I havent done? 
I've based my code on the json4s example from addons but Im using Option[JValue] for a field.

**Comment by tminglei** [comment]
Which version do you use now?

I remember there is this issue in some versions, but it was resolved in later versions. For details, you can refer to #297.

**Comment by rogern** [comment]
Im using version 0.14.6 and slick 3.1.1

**Comment by tminglei** [comment]
Then you can resolve it by changing `zero = JsNull` to `zero = null`.

**Comment by rogern** [comment]
yes, thx
