### ISSUE TITLE
Upsert using only nonAutoIncNames

### ISSUE THREAD

**Issue by teldosas** [tminglei/slick-pg#337]
[Here](https://github.com/tminglei/slick-pg/blob/07921ac573946c796aa133f1ec0197a38454dbd3/core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala#L109) all the names are used to build the query in contrast with [here](https://github.com/slick/slick/blob/39abcda1fed2f6051e8c0202ec72de37c07314d9/slick/src/main/scala/slick/jdbc/PostgresProfile.scala#L207) where only the `nonAutoIncNames` are used to create the query thus leaving the value of the auto inc names to be set by the db. This creates problems when for example you have a case class with an id with default value of zero.
```scala
case class Person(name: String, id: Long = 0L)
```
A new `Person` will be inserted to the database with an `id` of 0 while it should have been inserted with the next value of the auto incremented value.

**Comment by teldosas** [comment]
Actually after a second look the problem is [here](https://github.com/tminglei/slick-pg/blob/07921ac573946c796aa133f1ec0197a38454dbd3/core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala#L98) 
this should be negated
```scala
!s.options.contains(ColumnOption.AutoInc)
```

**Comment by tminglei** [comment]
@teldosas in general, we declare `id` as `Option[Long]` instead of `Long`, which can avoid the wrong default value `0L`.

**Comment by teldosas** [comment]
Well, in the book *Essential Slick* it uses a Long with a default value of 0 and think it's more convenient this way. Plus the default postgres slick driver handles this correctly as I said in the issue description above.

**Comment by tminglei** [comment]
Well, I'll refactor this, since slick/slick#1555 already released.

**Comment by tminglei** [comment]
Well, for autoInc + primaryKey column, we should add it to the inserting column list, and must ensure it non-null. Otherwise, it will violates the not-null constraint.

@teldosas in your case, the `id` column is `autoInc + primaryKey`, right?

**Comment by teldosas** [comment]
Yes it is `autoInc + primaryKey`. Why should we add it to the inserting column list?

**Comment by tminglei** [comment]
If it wasn't added into inserting list, the insert part won't fail.

**Comment by teldosas** [comment]
What do you mean it won't fail? Do you mean it won't conflict? Can't we just put it in the on conflict clause?

**Comment by tminglei** [comment]
Yes, it won't conflict. And you shouldn't put a value instead of a name to the conflict clause.

**Comment by teldosas** [comment]
hmm, it's weird that there's no way to make this work I'll just set `userNativeUpsert` to false then I guess

**Comment by aleksandrmelnyk** [comment]
Hey guys,

how to fix error "PSQLException: ERROR: null value in column "id" violates not-null constraint" when inserting data using insertOrUpdate? Is there any way to disable native upsert if its not working?

thanks in advance.

**Comment by aleksandrmelnyk** [comment]
my id column is as following def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
slick pg inserts null, can we make it use nextval('sequence') instead of null?

**Comment by tminglei** [comment]
@aleksandrmelnyk it's not resolved on slick part. You can watch #213

**Comment by aleksandrmelnyk** [comment]
@tminglei I see, thanks

**Comment by SangeetaGulia** [comment]
I am also facing this same issue.
ERROR: null value in column "id" violates not-null constraint
  Detail: Failing row contains (null, 07dea76d-42c7-4a83-a137-72c2e49a675a, a8928336-3b9a-4db6-9488-545a8dc95b83)

Can someone help me resolve this issue? 

    val id = column[Long]("id", O.AutoInc, O.PrimaryKey)
I am using id as the autoinc field.

**Comment by SangeetaGulia** [comment]
This worked. Had to make only one change, where we could map this autoincrement column to serial type of sql.

    val id = column[Long]("id", O.SqlType("SERIAL"), O.AutoInc, O.PrimaryKey)

  val requestTableQuery = TableQuery[ReqTable]

def insertRequest(request: RequestTable):Future[Long]= {
      db.run {
        requestTableQuery returning requestTableQuery.map(_.id) += RequestTable(0L, request.payloadId, request.runId)
      }
  }
