### ISSUE TITLE
Sequential parsing of TIMESTAMP WITH TIME ZONE to java.util.Calendar is broken

### ISSUE THREAD

**Issue by rgmih** [tminglei/slick-pg#340]
Sequential parsing of multiple `TIMESTAMP WITH TIME ZONE` values to `java.util.Calendar` (with same timezone, in one thread) leads to wrong parse results.

Let's assume we have two rows in table with different values T1 and T2 of type `TIMESTAMP WITH TIME ZONE`. When selecting these rows from table we expect to get two different instances C1, C2 of class `java.util.Calendar` so that: T1 → C1 and T2 → C2. But if parsing of these two values happens in one thread one after another than instead we receive the same `java.util.Calendar` instance C for both values: T1 → C and T2 → C. That happens as a result of following algorithm in `PgDateSupport.scala`:

1. `PgDateSupportUtils.parseCalendar` is invoked for string representation of T1;
2. `loadCalendar` / `parseBackendTimestamp` (depending on PostgreSQL driver version) method is invoked on `TimestampUtils` instance via reflection to parse string representation of T1;
3. fields of parsing result are accessed via reflection;
4. than `java.util.Calendar` instance is acquired with following code:

`val useCal: Calendar = if (tz.get(parsedts) == null) Calendar.getInstance() else tz.get(parsedts).asInstanceOf[Calendar]`

5. finally, fields of `useCal` are set with parsed values;
6. `useCal` calendar instance is returned;
7. steps 1-6 are repeated for string representation of T2.

The problem is that if we have timestamp with timezone (as in case of `TIMESTAMP WITH TIME ZONE`) than `tz.get(parsedts).asInstanceOf[Calendar]` branch of `if` is used on step 4. Somewhere deep in `org.postgresql.jdbc2.TimestampUtils.loadCalendar` (as well as in `org.postgresql.jdbc.TimestampUtils.parseBackendTimestamp` in newer versions of jdbc driver) we may find that `tz` field of parsing result is assigned with a result of method `getCalendar`. Being invoked sequentially for single timezone method `getCalendar` just returns value of internal field `calCache` that doesn't change across sequential invocations and always contains the same `java.util.Calendar` instance. As a result, after parsing T1 to C, when parsing T2 algorithm just UPDATES fields of existing C and returns it again for T2.

All that happens because instance of `TimestampUtils` is created only once for every thread and stored in `ThreadLocal` variable. Avoiding `ThreadLocal` is a possible solution, whenever I think that using private API is not a good practice.

I have patched `slick-pg:0.14.6` locally with code from `PgDate2Support.scala` using `java.time.format.DateTimeFormatter` instead of `org.postgresql.jdbc2.TimestampUtils`.

I have looked through sources of `slick-pg` (current `master`) as well as of Postgresql JDBC driver 9.4.1212 and believe that this bug still exists in `master`. I could make pull request with `DateTimeFormatter`-fix if needed.

**Comment by tminglei** [comment]
@rgmih yes, using private API is not a good practice, but with this, we can avoid to resolve multiple formats of pg date string parsing, which cannot be resolved by `DateTimeFormatter` easily.

**Comment by tminglei** [comment]
Fixed, can you help check?

**Comment by rgmih** [comment]
@tminglei, I would be able to check fix on monday.

Just for my information, why using `DateTimeFormatter` for `timestamptz` is okay in `PgDate2Support` and not enough in current case?

**Comment by tminglei** [comment]
Well, I made a wrong. We can parse it with `DateTimeFormatter`, but how to store the parsed result.
Don't forget old java `date`(java.util.Date) can't store `time zone`.

_p.s. `PgDateSupport` is target to old java `date`, and `PgDate2Support` is target to new java `time`._

**Comment by rgmih** [comment]
@tminglei, I've checked — it doesn't work with branch `slick3`. Now there is always only one instance of `TimestampUtils` (singleton-like) that is used for parsing every value — due to using `private val tsUtil_instance` in `slick3` instead of `private def tsUtil_instance` in `master` (mistype possibly?).

Anyway, in my opinion obtaining new instance of `TimestampUtils` via Reflection every time new value is parsed is unnecessarily slow.

I propose following solution (based on `PgDate2Support`):
```scala
object PgDateSupportUtils {
  private def fromInfinitable[T](max: T, min: T, parse: String => T): String => T = {
    case "infinity" => max
    case "-infinity" => min
    case finite => parse(finite)
  }

  private val date2TzDateTimeFormatter =
    new DateTimeFormatterBuilder()
      .append(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
      .optionalStart()
      .appendFraction(ChronoField.NANO_OF_SECOND, 0, 6, true)
      .optionalEnd()
      .appendOffset("+HH:mm","+00")
      .toFormatter()

  protected val fromZonedDateTimeOrInfinity: String => ZonedDateTime = fromInfinitable(
    LocalDateTime.MAX.atZone(ZoneId.of("UTC")),
    LocalDateTime.MIN.atZone(ZoneId.of("UTC")),
    ZonedDateTime.parse(_, date2TzDateTimeFormatter)
  )

  def parseCalendar(tsStr: String): Calendar = {
    val dt = fromZonedDateTimeOrInfinity(tsStr)
    GregorianCalendar.from(dt)
  }
}
```
We are using this solution as a patch to `slick-pg:0.14.6` for a few days, it just works.

Of course it is better to move `fromInfinitable`, `date2TzDateTimeFormatter` and `fromZonedDateTimeOrInfinity` from `PgDate2Support` to some common code and use it in both `PgDateSupport` and `PgDate2Support` to avoid _copy-paste_.

**Comment by tminglei** [comment]
@rgmih sorry, made a typo. Updated `val tsUtil_instance` to `def tsUtil_instance`.

_This is old date support, I don't want to involve new time classes. So I prefer to use `TimestampUtils`._

**Comment by rgmih** [comment]
@tminglei, okay, that's up to you. Thanks for the fix!

_Hope to see optimized code for java.util.Calendar in future releases because of_
> ** Java 8 is required

_is stated anyway in README.md._
