### ISSUE TITLE
Geometry operators are not type-safe

### ISSUE THREAD

**Issue by polarker** [tminglei/slick-pg#344]
In class `GeometryColumnExtensionMethods`, type `P2` seems could be any type. There should be some type bounds for it. We got trapped here while applying some operator to non-geometry object, and the compiler does not complain.

**Comment by tminglei** [comment]
Yes, geometry operators are not strictly type-safe.
When I recognized strictly follow type-safe rule will bring in great implementation complexity or user experience downgrade (different param type, like `T`/`Option[T]` may require different method signature), I made this trade off decision.

**Comment by polarke** [comment]
It would be great if type P2 is restricted to be a subtype of GEOMETRY. It's not necessary to be strictly type-safe, but being a subtype of GEOMETRY should be practically enough.

**Comment by tminglei** [comment]
It can't be, since P2 can be `Geometry`, `Point` or **`Option[Geometry]`**.

_`Option[Point]` is not sub class of `Option[Geometry]`._

**Comment by polarke** [comment]
Is it possible to define she operators for Geometry, and Point first, and then lifted to Option[Geometry]?

**Comment by tminglei** [comment]
As I remembered it can't be, but you can try it again.
