### ISSUE TITLE
Character \u0000 not allowed in postgres json/jsonb.

### ISSUE THREAD

**Issue by mattfeury** [tminglei/slick-pg#347]
Hey all,

I'm seeing an issue where we have json with the unicode character `\u0000` in it that we're trying to store in our database `jsonb` field. However, it seems like postgres has [disallowed support for this character](https://www.postgresql.org/message-id/E1YHHV8-00032A-Em@gemulon.postgresql.org).

It seems like this is something that the slick-pg play-json encoder should know and handle. Thoughts? Would it be as simple as modifying [this line](https://github.com/tminglei/slick-pg/blob/37ce884e43d0299535c9202a6e2ddeaa10ee299e/addons/play-json/src/main/scala/com/github/tminglei/slickpg/PgPlayJsonSupport.scala#L30) to replace all `\u0000` characters? happy to submit a PR

**Comment by tminglei** [comment]
Yes, pls send a PR. I'd like to merge it.

**Comment by mattfeury** [comment]
@tminglei thanks. working on it now. want to make sure i'm validating tests as well, but having trouble getting running. seeing these messages on `sbt test` in project root:

```
[info] - PostGIS Lifted support - constructor *** FAILED ***
[info]   org.postgresql.util.PSQLException: ERROR: type "geometry" does not exist
```

```
[info] - Composite type Plain SQL support *** FAILED ***
[info]   org.postgresql.util.PSQLException: ERROR: type "hstore" does not exist
```

```
[info] - Ltree Plain SQL support *** FAILED ***
[info]   org.postgresql.util.PSQLException: ERROR: type "ltree" does not exist
```

i created a database on localhost named "test" and a superuser named "postgres". anything I'm missing?

thanks!

**Comment by mattfeury** [comment]
PR added! disregarded that test.
