### ISSUE TITLE
String array elements trimmed unexpectedly

### ISSUE THREAD

**Issue by jonathancrosmer** [tminglei/slick-pg#349]
When I save an array with an element like "   x   ", it gets saved as "x" without the leading or trailing spaces.  I think it may have to do with SimpleArrayUtils or PgTokenHelper deciding whether or not to enclose the element in quotes.  For example, if in psql I save an array like `'{   x   }'`, it is saved in the DB as `{x}`.  I wasn't able to follow all the logic in PgTokenHelper.createString though.  Interestingly, if I save the element  "   x   x   ", it is added double quotes and saved like `{"x   x"}`, still trimmed.

It's caused a problem for us because it is effectively trimming string elements of arrays unexpectedly, and I haven't found a simple workaround.  Any help would be appreciated!

**Comment by tminglei** [comment]
Hi @jonathancrosmer fixed. Can you help check it?

**Comment by jonathancrosmer** [comment]
@tminglei it works!  We are on 0.14.4 and Slick 3.1.1 and Scala 2.11, so I locally cherry-picked it to the 0.14.4 tag, renamed the version to 0.14.4a, built it locally, and tested it in our project.
Whenever there is a release we will figure out how to integrate it into our build.
Thanks!  And great project!

**Comment by tminglei** [comment]
@jonathancrosmer it released in `v0.15.0`.

**Comment by jonathancrosmer** [comment]
Excellent, thanks
