### ISSUE TITLE
pg_trgm support

### ISSUE THREAD

**Issue by ski173** [tminglei/slick-pg#354]
I was just wondering if anyone is working no pg_trgm support.
If not, I can try to learn how to do this myself...
All I need at the moment is to use similarity() function and wanted to merge that in with all of my other Slick code as opposed to having to deal with plain sql.

**Comment by tminglei** [comment]
Ok, I'll add support for pg_trgm.

**Comment by tminglei** [comment]
Hi @ski173 added `pg_trgm` support, you can help check it [here](https://github.com/tminglei/slick-pg/commit/3ab5ee861699c4009a248ad4531d441e1c6c3683).

**Comment by ski173** [comment]
@tminglei Amazing. Thank you very much!

**Comment by tminglei** [comment]
You're welcome! ;-)
