### ISSUE TITLE
is it possible to make MappedJdbcType.base[JBean, JsValue] declared outside api

### ISSUE THREAD

**Issue by timzaak** [tminglei/slick-pg#358]
In some case, I need to transfer a `case class` to different json format in different tables.  

This is the example how to convert `json` and `case class` I can find, But can not solve the case:
https://github.com/tminglei/slick-pg/blob/master/addons/spray-json/src/test/scala/com/github/tminglei/slickpg/PgSprayJsonSupportSuite.scala#L33

我可能需要根据表不同，将一个 case class 转化为不同的 json 格式来存储。 或者说， 能否在  *Table 里面描述这个case class 如何转换？

**Comment by tminglei** [comment]
It's for reusefull to declare the `MappedJdbcType.base[JBean, JsValue]`.
If that's not expected, you're free to declare it outside of the `API`.

**Comment by timzaak** [comment]
thanks... @tminglei
