### ISSUE TITLE
could not find implicit value for parameter f: slick.jdbc.GetResult[com.vividsolutions.jts.geom.Point]

### ISSUE THREAD

**Issue by jfrense** [tminglei/slick-pg#368]
I am trying to run a custom query in Slick and map the result to a custom case class as follows:

```
case class BusinessDistanceResult(businessId: Long, userId: String, name: String, location: Point, address: Option[String], phonenumber: Option[String], email: Option[String], distance: Float )

  object BusinessDistanceResult {


    implicit val getMyMatch = GetResult(r => BusinessDistanceResult(r.<<, r.<<, r.<<, r.<<[Point], r.<<, r.<<, r.<<, r.<<))

  }
```
And here is my Query

```
def businessNearLocation(locationRadiusInput: LocationRadiusInput) =
      sql"""SELECT businessId, userId, name, location, address, phonenumber, email, ST_Distance(location, ref_geom) AS distance
           |FROM business
           |CROSS JOIN (SELECT ST_MakePoint(${locationRadiusInput.longitude}, ${locationRadiusInput.latitude})::geography AS ref_geom) AS r
           |WHERE ST_DWithin(location, ref_geom, ${locationRadiusInput.radius})
           |ORDER BY ST_Distance(location, ref_geom)""".as[BusinessDistanceResult]
```

However It is throwing the compilation Error:

```
could not find implicit value for parameter f: slick.jdbc.GetResult[com.vividsolutions.jts.geom.Point]
[error]     implicit val getMyMatch = GetResult(r => BusinessDistanceResult(r.<<, r.<<, r.<<, r.<<[Point], r.<<, r.<<, r.<<, r.<<))

```

But from my understanding, this implicit conversion should of been taken care of the implicits I declared in my class:

```
object MyAPI extends API with ArrayImplicits
    with DateTimeImplicits
    with JsonImplicits
    with NetImplicits
    with LTreeImplicits
    with RangeImplicits
    with HStoreImplicits
    with SearchImplicits
    with PostGISImplicits
    with PostGISAssistants
```

Is there something I am missing?

**Comment by tminglei** [comment]
@jfrense what you used is `plain` API. You should declare and use it like [this](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/MyPostgresProfile.scala#L29):
```scala
trait MyPostgresProfile ... {
///
  val plainAPI = new API with ByteaPlainImplicits
                         with SimpleArrayPlainImplicits
                         with Date2DateTimePlainImplicits
                         with SimpleJsonPlainImplicits
                         with SimpleNetPlainImplicits
                         with SimpleLTreePlainImplicits
                         with SimpleRangePlainImplicits
                         with SimpleHStorePlainImplicits
                         with SimpleSearchPlainImplicits {}
}

object MyPostgresProfile extends MyPostgresProfile

//////

import MyPostgresProfile.plainAPI._
```

Pls give it a try. _Good luck! ;-)_

**Comment by jfrense** [comment]
Hi @tminglei ,

Thanks for the quick response!

I tried your recommendation with the Plain API and I am still receiving the same compilation error.

Here is what I included:

i```
mport com.github.tminglei.slickpg._

trait MyPostgresProfile extends ExPostgresProfile
  with PgArraySupport
  with PgDateSupport
  with PgDate2Support
  with PgJsonSupport
  with PgNetSupport
  with PgLTreeSupport
  with PgRangeSupport
  with PgHStoreSupport
  with PgPostGISSupport

  with PgSearchSupport {

  override val pgjson = "jsonb"
  ///
  override val api: API = new API {}

  trait API extends super.API with ArrayImplicits
    with SimpleDateTimeImplicits
    with DateTimeImplicits
    with SimpleJsonImplicits
    with NetImplicits
    with LTreeImplicits
    with RangeImplicits
    with HStoreImplicits
    with SearchImplicits
    with SearchAssistants
    with PostGISImplicits

  ///
  val plainAPI = new API with ByteaPlainImplicits
    with SimpleArrayPlainImplicits
    with Date2DateTimePlainImplicits
    with SimpleJsonPlainImplicits
    with SimpleNetPlainImplicits
    with SimpleLTreePlainImplicits
    with SimpleRangePlainImplicits
    with SimpleHStorePlainImplicits
    with PostGISPlainImplicits
    with SimpleSearchPlainImplicits {}
}

object MyPostgresProfile extends MyPostgresProfile
```

**Comment by tminglei** [comment]
Well, you didn't provide all the details.
Maybe you can check the [`PgPostGISSupportSuite`](https://github.com/tminglei/slick-pg/blob/master/addons/jts/src/test/scala/com/github/tminglei/slickpg/PgPostGISSupportSuite.scala), which is a full and working case.

**Comment by jfrense** [comment]
Thanks for referring me to that document! It solved my problem. I just needed to define my getResult as the following:

`  implicit val getMyMatch = GetResult(r => BusinessDistanceResult(r.nextLong(), r.nextString, r.nextString, r.nextGeometry[Point], r.nextStringOption, r.nextStringOption, r.nextStringOption, r.nextFloat))`


Also, Just wanted to say thanks for creating Pg-Slick, it is a really useful library that has benefited me so much in my project!!!

**Comment by tminglei** [comment]
_Glad to hear that! You're welcome! :-)_
