### ISSUE TITLE
nested or 2 dimensional array support

### ISSUE THREAD

**Issue by DhavalKolapkar** [tminglei/slick-pg#386]
Does slick-pg support multi dimensional arrays as postgres does? 
https://www.postgresql.org/docs/9.3/static/arrays.html
@tminglei  pgjdbc is supporting multidimensional arrays
https://jdbc.postgresql.org/documentation/head/arrays.html

**Comment by tminglei** [comment]
@DhavalKolapkar didn't think about it. I can try to support it.

**Comment by tminglei** [comment]
@DhavalKolapkar I did some enhancement to support it. Can you give it a try?

**Comment by tminglei** [comment]
Released in v0.16.0
