### ISSUE TITLE
Support for INSERT ON CONFLICT

### ISSUE THREAD

**Issue by missingfaktor** [tminglei/slick-pg#394]
Hi. I would like to give a shot to adding proper support for `INSERT ON CONFLICT`. If you could guide me on how I can go about doing this - just a general high level idea - I would appreciate that! Thanks.

**Comment by tminglei** [comment]
@missingfaktor can you try `upsert` support? for its usage you can see [the test case](https://github.com/tminglei/slick-pg/blob/master/core/src/test/scala/com/github/tminglei/slickpg/PgUpsertSuite.scala).

**Comment by missingfaktor** [comment]
That only supports a complete replacement. What if one needs `ON CONFLICT DO NOTHING`, or `ON CONFLICT DO UPDATE` but not with all fields, etc?

**Comment by tminglei** [comment]
How about plain sql?

**Comment by missingfaktor** [comment]
Plain SQL is what we use currently but we have a lot of usages of the aforementioned construct, and we would like to use lifted embedding in those cases (for type-safety, compositionality, etc etc).

**Comment by tminglei** [comment]
Current implementation can [auto choose](https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/ExPostgresProfile.scala#L109) `ON CONFLICT DO NOTHING` and `ON CONFLICT DO UPDATE`, which can cover most of use cases.

For other corner cases, using plain sql may be better choice.

**Comment by missingfaktor** [comment]
I am aware what the current implementation does, and it doesn't meet our requirements. Hence the interest in extending this. I would like to give it a shot.

**Comment by tminglei** [comment]
@missingfaktor I'd like to keep current implementation unchanged, since it covered most of normal cases and the logic was consistent with `slick`.

But it shouldn't affect you to customize it on your local. And if any I can help, pls let me know.

**Comment by missingfaktor** [comment]
I am not that familiar with Slick architecture. I could explore on my own, but I was wondering if you could point me to some PR from past trying to solve a similar problem, and that could potentially speed me up.

**Comment by tminglei** [comment]
Found a pr issue #293, hope it's useful to you.
