### ISSUE TITLE
java.sql equals comparisons buggy

### ISSUE THREAD

**Issue by Trekoid** [tminglei/slick-pg#396]
While prepping #395 , I was sporadically getting the PgDateSupportSuite.scala:78 dates did not equal test failure, like the build system got when #390 was merged into master.

I did some research, and apparently it is buggy and the community doesn't suggest relying on it. See https://stackoverflow.com/questions/24790436/jdbc-java-sql-date-comparison-is-giving-false for some of the discussion.

I tried changing lines 77-81 to use the conversion mentioned in the StackOverflow thread with
```sql
              case (b1, b2) => {
                assert(b1.date.toLocalDate === b2.date.toLocalDate)
                assert(b1.time.toLocalTime === b2.time.toLocalTime)
                assert(b1.timestamp.toLocalDateTime === b2.timestamp.toLocalDateTime)
              }
``` 
, but the very next time I ran the test, I got 
```scala
[info] - Date Lifted support *** FAILED ***
[info]   2010-11-04 03:33:01.0 did not equal 2010-11-03 04:33:01.0 (PgDateSupportSuite.scala:86)
```
. Subsequent runs of the test didn't have the problem. As the old adage states, non-repeatable bugs are the worst.

Is it worthwhile to refactor the entire PgDateSupportSuite to use the conversions to java.time types, or leave as is and just retry builds when it fails?

**Comment by tminglei** [comment]
Agreed. I'll refactor it.
