### ISSUE TITLE
`GetResult` and `SetParameter` instances for `UUID`

### ISSUE THREAD

**Issue by missingfaktor** [tminglei/slick-pg#399]
`slick-pg` does not appear to have `GetResult` and `SetParameter` for `UUID`. We have these locally in our project. If there is interest, I will be happy to make a PR with these instances.

**Comment by tminglei** [comment]
`UUID`'s `GetResult` and `SetParameter` should be added to `slick`, since it has built-in `UUIDJdbcType`.
Let's make a PR to [slick](https://github.com/slick/slick).

**Comment by pathikrit** [comment]
Why is this closed? Is this resolved?

**Comment by Daenyth** [comment]
Upstream ticket: https://github.com/slick/slick/issues/161
