### ISSUE TITLE
Empty fields in jsonb[] giving exception for a select query

### ISSUE THREAD

**Issue by dineyw23** [tminglei/slick-pg#400]
For an array of JsValue when one of the values for a field is empty string, I'm getting  `Json.parse(_)` exception for the select query. Is this related to `utils.SimpleArrayUtils.fromString` ? 

```
    implicit val playJsonArrayTypeMapper =
      new AdvancedArrayJdbcType[JsValue](pgjson,
        (s) => utils.SimpleArrayUtils.fromString[JsValue](Json.parse(_))(s).orNull,
        (v) => utils.SimpleArrayUtils.mkString[JsValue](_.toString())(v)
      ).to(_.toList)
```

Example Jsonb[]:

```
[{
     "id": "1",
     "type": ""
},
{
      "id": "2",
     "type": "GET"
}]
```
`Unexpected character ('}' (code 125)): expected a value`

Example:
```
[{
     "id": "1",
     "type": "",
     "url": "google.com"
}]
```
`Unexpected character (',' (code 40)): expected a value`

I think this was a similar issue for string #294.

**Comment by tminglei** [comment]
Not same with #294. I'll fix it asap.

**Comment by dineyw23** [comment]
That'll be great. Thank you!

**Comment by tminglei** [comment]
@dineyw23 fixed, pls help check. _Thanks! 👍_
