### ISSUE TITLE
Postgres returns null for empty arrays, but .length is non-optional

### ISSUE THREAD

**Issue by jonathancrosmer** [tminglei/slick-pg#401]
Version 0.16.0

`com.github.tminglei.slickpg.array.PgArrayExtensions.ArrayColumnExtensionMethods#length`
returns a non-optional value, but `array_length` returns null for empty arrays:

`select array_length(array[]::integer[],1) is null`
 = true

It's kind of a ridiculous quirk of Postgres API.  Arguably it is a bug since null is supposed to mean "unknown", but it seems to be baked in.  I think selecting a count() for zero rows also returns null.

But I think slick-pg should handle it, either making `length` optional or using a `coalesce` to return 0.

**Comment by tminglei** [comment]
Yes, we should adjust it.

**Comment by tminglei** [comment]
@jonathancrosmer resolved, pls help check.
_Thanks! 👍_

**Comment by jonathancrosmer** [comment]
Works for me!  Thanks for the quick fix!

**Comment by tminglei** [comment]
Glad to hear that! You're welcome!
