### ISSUE TITLE
Invalid SQL is generated for UUID values in window functions

### ISSUE THREAD

**Issue by nebehr** [tminglei/slick-pg#404]
Invalid SQL is generated for null UUID values (perhaps some other types as well) in window functions. Basically, the code like this:
```
val query = table.map { t =>
  val w = Over.partitionBy(t.name).sortBy(r.timestamp)
  (t.id, lag(t.id.?) :: w)
}
db.run(query.result)
```
where id is declared as ```def id = column[UUID]("id", O.PrimaryKey, O.SqlType("UUID"))```, generates the following or similar SQL:
```select id, lag(id,1,'null') over ( partition by name order by timestamp) from my_table limit 100 offset 0```
which produces "ERROR: invalid input syntax for uuid: "null"".

More details and some discussion at https://github.com/slick/slick/issues/1901

**Comment by tminglei** [comment]
@nebehr sorry for responsing so late.
Fixed, pls help check.

_Thanks! 👍_

**Comment by tminglei** [comment]
@nebehr sorry for responsing so late.
Fixed, pls help check.

_Thanks! 👍_

**Comment by nebehr** [comment]
@tminglei it works, thanks for the fix.
