### ISSUE TITLE
Error parsing the JSON in get call

### ISSUE THREAD

**Issue by kolapkardhaval** [tminglei/slick-pg#409]
Hi, 
I have a table column which is a JsValue. When doing a get call, I get the below exception:
Unrecognized token 'PF': was expecting ('true', 'false' or 'null')\n
This is because, the JSON has the below key value:
"user-agent": ["PF/02.8.77 (xyz)"]
If I replace this value by removing spaces, (, ) and leading 0 it works:
"user-agent": ["PF2.8.77xyz"]
I had earlier faced a similar issue with empty strings in JSON.
Could you please look into it? Is it possible not to validate the JSON at all while doing a get? That would help a lot.

**Comment by tminglei** [comment]
I'll check it.

**Comment by tminglei** [comment]
@kolapkardhaval I tried your case, for more details pls see above [9e3731b](https://github.com/tminglei/slick-pg/commit/9e3731b388e4153a296b2d03ffeefdc2af639be1), it looks good.
Pls double check.

**Comment by tminglei** [comment]
BTW, which version are you using?

I fixed a related issue #400 in slick-pg `v0.16.1`, maybe you can give it a try.

**Comment by kolapkardhaval** [comment]
Could it be that this code below is causing issues while grouping and tokenizing?
def fromString[T](convert: String => T)(arrString: String): Option[Seq[T]] =
    grouping(Tokenizer.tokenize(arrString)) match {
      case Null => None
      case root => Some(getChildren(root).map {
        case Null  => null.asInstanceOf[T]
        case token => convert(getString(token, 0))
      })
    }

**Comment by tminglei** [comment]
Well, you confused me. Why did you include so many json plugins, and I can't find the point from your pasted codes, which is too clutter.

**Comment by kolapkardhaval** [comment]
I removed them all and kept only play json

**Comment by kolapkardhaval** [comment]
Basically, I did some testing and it seems I am getting here 

def fromString[T](convert: String => T)(arrString: String): Option[Seq[T]] =
grouping(Tokenizer.tokenize(arrString)) match {
case Null => None
case root => Some(getChildren(root).map {
case Null => null.asInstanceOf[T]
case token => convert(getString(token, 0))
})
}
////////////////////////////////////////////////////////
Also, in the extended post gres profile, there is a play json mapper:
new AdvancedArrayJdbcType[JsValue](pgjson,
(s) => utils.SimpleArrayUtils.fromStringJsValue(s).orNull,
(v) => utils.SimpleArrayUtils.mkStringJsValue(v)
).to(_.toList)

I called the method mkString with the input as List(json with issue ) and then called fromString on the value I got from the mkString and it gave me the same error.

**Comment by tminglei** [comment]
@kolapkardhaval  I need codes of pg profile definition, table definition, usage codes, etc.
Maybe a reproducable sample project is a better way.

**Comment by kolapkardhaval** [comment]
@tminglei I would do that. In the meantime, as far as I know, there is some issue with the tokenizer as the error is caused here (s) => utils.SimpleArrayUtils.fromStringJsValue(s).orNull. It seems to be causing issue parsing/tokenizing the jsonb when there are spaces, (, ) or leading 0

**Comment by tminglei** [comment]
@kolapkardhaval I'm not where is wrong. Maybe it's not related to slick-pg, since, as you know, it's ok in my adjusted test case.

**Comment by kolapkardhaval** [comment]
Hi @tminglei I have created a sample project showing the error I am getting while doing a sample call (add/POST in this case).  https://github.com/kolapkardhaval/slick-demo

**Comment by tminglei** [comment]
@kolapkardhaval can it reproduce your error by running `ParticipantControllerSpec`?
Why does it look good on my local?

**Comment by kolapkardhaval** [comment]
@tminglei In ParticipantControllerSpec, the second test case is to assert that there is a Json parse exception,  a[JsonParseException] must be thrownBy
Is the ParticipantControllerSpec failing for you? Could you paste the error if it is failing.

**Comment by tminglei** [comment]
@kolapkardhaval  not failed. After uncommented `a[JsonParseException] must be thrownBy`, I got the error.
I'll check into it.

**Comment by tminglei** [comment]
@kolapkardhaval fixed, can you help check it?

**Comment by kolapkardhaval** [comment]
@tminglei Thank you so much. It is working now. Apologies for the late repsonse.

**Comment by kolapkardhaval** [comment]
Would there be a release for this fix?

**Comment by tminglei** [comment]
Sure. Released in slick-pg v0.16.2
