### ISSUE TITLE
unable to find extensions in custom schema on insert: org.postgresql.util.PSQLException: Unknown type ltree.

### ISSUE THREAD

**Issue by teeterc** [tminglei/slick-pg#420]
I'm seeing an issue with the sqlBaseTypes and custom schemas where the baseType isn't being located correctly. 

Take this example

-- db setup 
SET search_path TO public,extensions_schema;
CREATE extension if NOT EXISTS ltree SCHEMA extensions_schema CASCADE;

-- I create a table (via schema create)
create table "permission" ("guid" VARCHAR NOT NULL PRIMARY KEY,"uris" ltree [] NOT NULL,"permission" varchar NOT NULL,"creation_time" timestamptz NOT NULL,"last_modified" timestamptz NOT NULL);

At this point everything is working

-- selecting works fine (if i add data to the db manually) 
  > permissionsDAO.query.filter ... works fine

However if i try to insert a row
  > . permissionsDAO.query += .. new permission

I get "org.postgresql.util.PSQLException: Unknown type ltree."

If i change the mapper to include the schema: The same query works. 
> override implicit val simpleLTreeListTypeMapper: JdbcType[List[LTree]] =
>       new AdvancedArrayJdbcType[LTree]("**extensions_schema**.ltree",
>         fromString = utils.SimpleArrayUtils.fromString(LTree.apply)(_).map(_.toList).orNull,
>         mkString = utils.SimpleArrayUtils.mkString[LTree](_.toString)(_)
>       ).to(_.toList)

Any ideas?

**Comment by tminglei** [comment]
Why you `CREATE extension if NOT EXISTS ltree SCHEMA extensions_schema CASCADE;`?

**Comment by teeterc** [comment]
I have my reasons :).  but in any case, is it possible to use the built in pg-slick implicits if the extensions are created in a separate schema (and added to the search path)?

**Comment by tminglei** [comment]
It doesn't matter with `slick-pg`. You got a pg driver Exception, which said it can't recognize the type `ltree`.

**Comment by tminglei** [comment]
Well, you just installed the extension in schema `extensions_schema`, so it can't be seen outside.

**Comment by tminglei** [comment]
Ok~
