### ISSUE TITLE
List composite type error when list is Nil.

### ISSUE THREAD

**Issue by jacktok** [tminglei/slick-pg#421]
I try to create the composite type like 
```scala
case class C1 (
    name: String
) extends Struct

case class C2 (
    c1: List[C1]
) extends Struct

```

I got error when list c1 is `Nil` `{}`
```
java.lang.IllegalArgumentException: WRONG token type: Chunk({)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.getChildren(PgTokenHelper.scala:80)
	at com.github.tminglei.slickpg.PgCompositeSupportUtils$SeqConverter.fromToken(PgCompositeSupport.scala:158)
	at com.github.tminglei.slickpg.PgCompositeSupportUtils$CompositeConverter.$anonfun$fromToken$1(PgCompositeSupport.scala:129)
...
```

**Comment by tminglei** [comment]
@jacktok it also threw `WRONG token type: Chunk(()` when list c1 is `List(C1("test"))` and the composite type's value string is `({(test)})`.
To fix this issue, it maybe require a new parsing/resolving way.

I'll find more time to implement it.

**Comment by jacktok** [comment]
@tminglei thanks vm

**Comment by tminglei** [comment]
@jacktok I reimplement composite support, can you help check it?
It's on branch `issue-421`.

**Comment by jacktok** [comment]
sure, let me check.

**Comment by jacktok** [comment]
@tminglei I'm checked. it's ok for me thanks vm. sorry for late.

**Comment by tminglei** [comment]
that's ok 👍
