### ISSUE TITLE
Postgres composite type null

### ISSUE THREAD

**Issue by jacktok** [tminglei/slick-pg#424]
https://github.com/tminglei/slick-pg/blob/1e601ca579bf942030e34f1ebec03dbd4dda9d42/src/main/scala/com/github/tminglei/slickpg/PgCompositeSupport.scala#L148

I think we should check the token is null by 
```scala
def isNull(token: Token): Boolean = {
      token match {
        case members@GroupToken(_) => getChildren(members).forall(isNull)
        case PgTokenHelper.Comma => false
        case PgTokenHelper.Null => true
        case Chunk(_) => false
        case Escape(_) => false
        case _: Border => false
      }
```
because sometimes the Postgres replace null of a composite with `(,,,,)`.
e.g
```scala
case class A(a1: Int, a2: String) extends Struct
case class B(id: Int, a: Option[A]) extends Struct
```
when composite at posegrest is `(1, (,))` it's will throw exception.

> https://stackoverflow.com/questions/43187305/difference-between-null-composite-type-and-composite-type-with-all-null-columns

I'm not sure it's correct :1234:

**Comment by tminglei** [comment]
hi @jacktok I submitted a fix, which treated the composite value of empty members as null value by default. But if it's not expected, user can override the switch `emptyMembersAsNull` to `false`.

Pls help check it. _Thanks!_
