### ISSUE TITLE
update jsonb field partly

### ISSUE THREAD

**Issue by sanjarbek** [tminglei/slick-pg#429]
update action
`val updateAction = table.map(_.json +> "location" +> "lat").update(Some(Json.toJson(52.235685)))`
result is
`[error] (run-main-0) slick.SlickException: A query for an UPDATE statement must select table columns only -- Unsupported shape: ProductNode`

how to do it?

**Comment by tminglei** [comment]
Two ways:
1) `val updateAction = table.map(_.json).update(__mutated_json__)`
2) use plain sql

_p.s. partial update is not supported._

**Comment by sanjarbek** [comment]
I got it. Thank you.
