### ISSUE TITLE
Inconsistent nanoseconds treatment in LocalDateTime

### ISSUE THREAD

**Issue by psttf** [tminglei/slick-pg#433]
With slick-pg 0.16.3 on Scala 2.12.6 I get the following behavior: all the `LocalDateTime`s with not more than 999,999,499 nanoseconds are treated as Postgres timestamps correctly rounded to microsecond precision, but if there is 999,999,500 nanoseconds or more it is all of a sudden treated as Postgres timestamp with just 100 microseconds. 

Unfortunately I am not very familiar with the structure of slick-pg so my minimal example involves sending queries to real Postgres DB. See the following REPL session:

```scala
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).

<... define MyPostgresProfile as in README.md ...>

import com.github.tminglei.slickpg._
defined trait MyPostgresProfile
defined object MyPostgresProfile
import MyPostgresProfile.api._
res0: <... this is my PG DB provider ...>

scala> Compiled((dt: Rep[java.time.LocalDateTime]) => dt)
res1: slick.lifted.CompiledFunction[MyPostgresProfile.api.Rep[java.time.LocalDateTime] => MyPostgresProfile.api.Rep[java.time.LocalDateTime],MyPostgresProfile.api.Rep[java.time.LocalDateTime],java.time.LocalDateTime,MyPostgresProfile.api.Rep[java.time.LocalDateTime],java.time.LocalDateTime] = slick.lifted.CompiledFunction@4b9a0eea

scala> res0.db run res1(java.time.LocalDateTime parse "2018-11-19T11:58:12.999999").result
res2: scala.concurrent.Future[java.time.LocalDateTime] = Future(<not completed>)

scala> res2.value
res3: Option[scala.util.Try[java.time.LocalDateTime]] = Some(Success(2018-11-19T11:58:12.999999))

scala> res0.db run res1(java.time.LocalDateTime parse "2018-11-19T11:58:12.9999999").result
res4: scala.concurrent.Future[java.time.LocalDateTime] = Future(<not completed>)

scala> res4.value
res5: Option[scala.util.Try[java.time.LocalDateTime]] = Some(Success(2018-11-19T11:58:12.100))
```

This breaks order of initial Scala date-times. Thus such queries involving timestamp column comparisons may return unexpected results.

There must be something wrong with rounding. I can help preparing an PR if you give some advice on where to look for the cause of the problem.

**Comment by psttf** [comment]
I've updated the initial description since it was not clear and lacked some details.

**Comment by tminglei** [comment]
Yeah, I reproduced the issue. But `2018-11-19T11:58:12.9999999` was rounded to `2018-11-19T11:58:13` instead of `2018-11-19T11:58:12.100`.
My backend pg is `v10.0`.

But there isn't anything you can do on `slick-pg` side. This is a pg issue.
_p.s. you can look `slick-pg` as a wrapper, and in fact pg did the computation._

**Comment by psttf** [comment]
@tminglei thank you for the response! But if you got `2018-11-19T11:58:13` from `2018-11-19T11:58:12.9999999` this is an expected correct rounding. This means that in your case the issue I reported was not reproduced.

So you say that the datetime is passed to Postgres directly without any conversions to string or other representations?

**Comment by tminglei** [comment]
yes, slick-pg will pass the unchanged value to pg.

**Comment by psttf** [comment]
I'm getting correct rounding in Postgres. It may be a JDBC issue.

**Comment by psttf** [comment]
I'm getting correct rounding in Postgres. It may be a JDBC issue.

**Comment by psttf** [comment]
And here is it: https://github.com/pgjdbc/pgjdbc/issues/1211

Maybe my JDBC version is outdated.

I'll close this slick-pg issue.
