### ISSUE TITLE
Postgres JOIN on Array column?

### ISSUE THREAD

**Issue by kansuke231** [tminglei/slick-pg#439]
Hi all,

I am curious if it's possible to express in slick-pg a join on an Array column as follows:
```sql
SELECT
       title_basics.primary_title,
       name_basics.primary_name
FROM
        title_basics
JOIN name_basics ON title_basics.tconst = ANY(name_basics.known_for_titles);
```

Thanks in advance!

**Comment by tminglei** [comment]
Yes, you can do it.

**Comment by kansuke231** [comment]
Thanks for the response.
However, I'm still stuck with the actual implementation for this scenario.

I have a following piece of code:

```scala
def movieWithCasts() = {
    val a = db.run(
      TitleBasicsTables.
        join(NameBasicsTables).on((title,name) =>  name.knownForTitles ??? title.primaryTitle ).result
    )
  }
```
 I'm not sure how to actually implement `title_basics.tconst = ANY(name_basics.known_for_titles);`
where `name_basics.known_for_titles` is an Array of String and `SELECT title_basics.primary_title, name_basics.primary_name`. In the code above `name.knownForTitles` is `Rep[List[String]]` type and it does not seem to have a comparable method for `ANY` operator in PostgreSQL.

**Comment by tminglei** [comment]
@kansuke231 you can try
```scala
(TitleBasicsTables.join(NameBasicsTables)
    .on((title,name) => name.knownForTitles.any === title.primaryTitle)
).result
```

**Comment by kansuke231** [comment]
Nope, it does not work; I see `cannot resolve symbol any` on the IDE (IntelliJ). I also cannot find any example that is similar to this case.

**Comment by tminglei** [comment]
Check [this](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgArraySupportSuite.scala) for setting up.

**Comment by kansuke231** [comment]
Having  a`import MyPostgresProfile.api._` statement within the class in which the method above is implemented  solved the issue. Thanks @tminglei !
So it was like this:
```scala
class MyContext(db: Database) {

  import MyContext._
  import MyPostgresProfile.api._

 
  def movieWithCasts(primaryTitle: String) = {

    val a = db.run(
      MovieBasicsTables.
        join(NameBasicsTables).on((title,name) =>  name.knownForTitles.any === title.tconst).result
    )
  }
}
```

**Comment by tminglei** [comment]
:-)
