### ISSUE TITLE
List[List[Int]] for plain sql?

### ISSUE THREAD

**Issue by katjabercic** [tminglei/slick-pg#448]
I need to get a query result from a plain sql query that includes a two-dimensional int array column and I found a solution online that works with a regular slick query (below).  This does not help with the plain queries and I was unable to figure out what I need to do.  I can get one-dimensional arrays with `r.<<[Seq[Int]].toList` in the GetResult.

Here's my Postgres profile:

```
trait MyPostgresProfile extends ExPostgresProfile with PgArraySupport {

  override val api: API = new API {}

  trait API extends super.API
    with ArrayImplicits
    with SimpleArrayPlainImplicits {

    implicit val intintWitness: ElemWitness[List[Int]] = ElemWitness.AnyWitness.asInstanceOf[ElemWitness[List[Int]]]

    implicit val simpleIntIntListTypeMapper: DriverJdbcType[List[List[Int]]] = {
      new SimpleArrayJdbcType[List[Int]]("int4[]").to(_.asInstanceOf[Seq[Array[Any]]]
        .toList.map(_.toList.asInstanceOf[List[Int]]))
    }

  }
}

object MyPostgresProfile extends MyPostgresProfile
```

Thanks!

**Comment by tminglei** [comment]
@katjabercic array of array is not supported yet!

**Comment by katjabercic** [comment]
Thank you!
