### ISSUE TITLE
nodeMCU driver error

### ISSUE THREAD

**Issue by shyam9092** [tminglei/slick-pg#450]
In arduino IDE, under file >> preferences, additional boards manager URL I've added the following link: 'http://arduino.esp8266.com/stable/package_esp8266com_index.json'. When I click Ok, the following error comes.

Skipping contributed index file C:\Users\Shyam\AppData\Local\Arduino15\package_esp8266com_index.json, parsing error occured:
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Dropping': was expecting ('true', 'false' or 'null')
 at [Source: (FileInputStream); line: 1, column: 10]
Skipping contributed index file C:\Users\Shyam\AppData\Local\Arduino15\package_esp8266com_index.json, parsing error occured:
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Dropping': was expecting ('true', 'false' or 'null')
 at [Source: (FileInputStream); line: 1, column: 10]
How do I solve this?

**Comment by tminglei** [comment]
@shyam9092 are you sure it's related to `slick-pg`?

**Comment by shyam9092** [comment]
@tminglei I'm sorry I don't follow. What is slick-pg?

**Comment by tminglei** [comment]
this lib, [slick-pg](https://github.com/tminglei/slick-pg)
