### ISSUE TITLE
Mention scala-parser-combinators dependency in README

### ISSUE THREAD

**Issue by falconepl** [tminglei/slick-pg#451]
`scala-parser-combinators` is a provided dependency for `slick-pg`, so it's required to include it in a project that uses `slick` along with `slick-pg`. Otherwise, we end up with a runtime error such as:

```
[error] (db-2) java.lang.NoClassDefFoundError: scala/util/parsing/combinator/RegexParsers
[error] java.lang.NoClassDefFoundError: scala/util/parsing/combinator/RegexParsers
[error]     at java.lang.ClassLoader.defineClass1(Native Method)
[error]     at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
(...)
```

That can happen e.g. when using custom `AdvancedArrayJdbcType` for database reads.

Could we add a _Setup_/_Using slick-pg_ section to the README that reminds to include `scala-parser-combinators` in one's `build.sbt`? What do you think @tminglei? I can prepare a pull request if needed

**Comment by tminglei** [comment]
@falconepl yes, it's welcome, please. Thanks! 👍

**Comment by falconepl** [comment]
By the way, I was also wondering, why `scala-parser-combinators` is a `provided` dependency, rather than the standard one?

**Comment by tminglei** [comment]
Oh yes, it should be a standard dependency for `scala 2.12+`.
