### ISSUE TITLE
doesn't make plural results

### ISSUE THREAD

**Issue by elyphas** [tminglei/slick-pg#452]
I have this sql statement and works fine: 
```sql
select programa, substring(descripcio,1,40) as descr from tblpresu where to_tsvector(descripcio) @@ to_tsquery('PROGRAMAS');
```
but this slick_pg:
```scala
query
        .filter( t =>
          tsVector(t.descripcion) @@ plainToTsQuery("PROGRAMAS".bind)
          //{toTsVector(t.descripcion, Some("spanish")) @@ toTsQuery("PROGRAMAS".bind) }
        )
        .map( r => ( r.programa, r.descripcion, tsRank(tsVector( r.descripcion ), tsQuery( queryStr.bind ))))
```
the records with the word `PROGRAMA` are not included in the results.
Someone please, Could tell me what I need to do?

**Comment by elyphas** [comment]
also I tried this:
```scala
{toTsVector(t.descripcion, Some("spanish")) @@ toTsQuery(queryStr.bind) }
```

**Comment by elyphas** [comment]
and this:
```scala
tsVector(t.descripcion) @@ tsQuery("PROGRAMAS".bind)
```

**Comment by tminglei** [comment]
@elyphas sorry, I can't catch your mean.
As slick-pg simply translated the operators to pg like [this](https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/search/PgSearchExtensions.scala#L40), you can check it yourself.

**Comment by elyphas** [comment]
Ok, thank you, I think is solved, was my  mistake, sorry

**Comment by tminglei** [comment]
Ok
