### ISSUE TITLE
Please support scala 2.13

### ISSUE THREAD

**Issue by aquamatthias** [tminglei/slick-pg#453]
Scala 2.13 has been released. In order to move forward it would be great to see an updated version for this version.

**Comment by tminglei** [comment]
Should wait some days. Some plugins' dependencies didn't catch up.

**Comment by tminglei** [comment]
Merged #454, but the issue wasn't fixed yet.

**Comment by tminglei** [comment]
@aquamatthias done.

**Comment by pjfanning** [comment]
@tminglei it looks like it could be a number of weeks before full releases that support scala 2.13.0 for cats and circe are available. Both projects are on milestone releases and have RC releases planned.

Would it be possible to release slick-pg without circe support (temporarily) or to release with a dependency on the existing milestone release for circe?

**Comment by tminglei** [comment]
@pjfanning well, let's release it.

**Comment by tminglei** [comment]
Released at v0.18.0.
