### ISSUE TITLE
JTS Point not honoring SRID

### ISSUE THREAD

**Issue by gnp** [tminglei/slick-pg#456]
I've mapped a case class that has a parameter of type Point, which I've imported from LocationTech's JTS:

```scala
import org.locationtech.jts.geom.Point
```

I've inserted values into the corresponding table with SQL manually like this:

```sql
ST_SetSRID(ST_MakePoint(-118.2427777778, 34.0522222222),4326))
```

But, when I fetch records from the database, the `point` I get back has SRID of zero instead of 4326!

```scala
point.getFactory.getSRID
```

I haven't tried yet to `INSERT` a `Point` with `SRID` set to a non-zero value, so I don't know yet whether *slick-pg* is honoring SRID in that direction. But, for my application, I'm going to want both of them working so all my data that is pre-loaded and that is later created as a result of user activity has the correct SRID stored with the points.

Have I missed a feature that makes this work, or is this a bug in slick-pg?

**Comment by gnp** [comment]
I'm using version 1.16.1 of LocationTech's JTS library.

I'm using version 0.18.0 of slick-pg (with jts_lt add-on).

I'm using version 4.0.2 of play-slick.

**Comment by gnp** [comment]
I just tested writing Points into the database, and I am seeing in pgAdmin the SRID I set (4326) is being stored in PostgreSQL.

Here's how I built up the value I wrote to the database:

```scala
val xy = new CoordinateXY(lon, lat)
val ca = new CoordinateArraySequence(Array[Coordinate](xy), 2)
val gf = new GeometryFactory(new PrecisionModel(), 4326)
val ll = new Point(ca, gf)
```

**Comment by gnp** [comment]
There was a typo in my code. What above I have shown:

```
point.getFactory.getSRID
```

should have been:

```
point.getSRID
```

fixing that typo resolved the problem.

**Comment by tminglei** [comment]
Good! 👍
