### ISSUE TITLE
Wrong <@: (is contained by) array operator implementation

### ISSUE THREAD

**Issue by rgmih** [tminglei/slick-pg#464]
It seems that there is a bug in [PgArrayExtensions.scala](https://github.com/tminglei/slick-pg/blob/9484247c6f608252644d99882109f8e0c380ad1c/core/src/main/scala/com/github/tminglei/slickpg/array/PgArrayExtensions.scala#L40) in `<@:` operator implementation:
```
def <@:[P2, R](e: Rep[P2])(implicit om: o#arg[SEQ[B0], P2]#to[Boolean, R]) = {
    om.column(ArrayLibrary.ContainedBy, e.toNode, n)
}
```
Arguments `e.toNode` and `n` should be rearranged: `n` should be `ContainedBy` `e.toNode` but not vice versa.

p.s.: By the way, function `<@:` is referenced in [documentation](https://github.com/tminglei/slick-pg/tree/master/core/src/main/scala/com/github/tminglei/slickpg/array) as `<@` (without `:`).

**Comment by tminglei** [comment]
When implementing `<@`, I referred the way of `||` in `3 || ARRAY[4,5,6]`.
So for `arr1 <@: arr2`, the `<@:` is an operator of `arr2` instead of `arr1`.

**Comment by rgmih** [comment]
Okay, my bad, that's not a bug but just my misunderstanding. Thank you for the quick response!
