### ISSUE TITLE
Is Joda Convert a required dependency?

### ISSUE THREAD

**Issue by KaoruDev** [tminglei/slick-pg#467]
## Problem
I noticed that I have a version conflict in one of my projects and notice that it was conflicting with joda-convert. `slick-pg_joda-time` compiles just fine without `joda-convert` and I don't see any references to class inside of `joda-convert`.

## Proposal
Could we remove the dependency from the library? It's confusing to have it if `slick-pg_joda-time` doesn't depend on it.

**Comment by tminglei** [comment]
@KaoruDev yes, it's required.

**Comment by KaoruDev** [comment]
@tminglei sorry this might be an irritating question, but could you show me how? I forked the project, removed `joda-convert` and was still able to compile and run the tests green: https://github.com/tminglei/slick-pg/compare/master...KaoruDev:master

**Comment by tminglei** [comment]
Well, `joda-convert` was imported several years ago because of build requirement.
For whether it is still required, I need check it again, under scala 2.11/2.12/2.13.

**Comment by tminglei** [comment]
@KaoruDev you're right, it's unnecessary anymore. I removed it at 08dde3dfccc42537b4fa240f30b78c2d322edc69

**Comment by KaoruDev** [comment]
fantastic, thank you!
