### ISSUE TITLE
Null in array serialized wrongly

### ISSUE THREAD

**Issue by Katrix** [tminglei/slick-pg#488]
Using code like this
```scala
implicit private val listOptionStrType: DriverJdbcType[List[Option[String]]] =
  new SimpleArrayJdbcType[String]("text")
    .mapTo[Option[String]](Option(_), _.orNull)
    .to(_.toList)
```

Trying to insert a None in the list produces an empty string for that element, and not the NULL identifier. For example, trying to insert `List(Some("[2.3,)"), Some("[0.3.0,)"), None, Some("7.1.0"), None)`
produces the error `org.postgresql.util.PSQLException: ERROR: malformed array literal: "{"[2.3,)","[0.3.0,)",,7.1.0,}"`.

From the [Postgres docs](https://www.postgresql.org/docs/12/arrays.html#ARRAYS-INPUT), NULL values should be written as null, and not as an empty string
> To set an element of an array constant to NULL, write NULL for the element value. (Any upper- or lower-case variant of NULL will do.)

**Comment by Katrix** [comment]
Here's a working workaround which I assume works on the fact that String is a primitive
```scala
implicit private val listOptionStrType: DriverJdbcType[List[Option[String]]] =
  new SimpleArrayJdbcType[String]("text")
    .to[List](
      _.map(Option(_)).toList.asInstanceOf[List[String]],
      _.asInstanceOf[List[Option[String]]].map(_.orNull)
    )
    .asInstanceOf[DriverJdbcType[List[Option[String]]]]
```

**Comment by tminglei** [comment]
@Katrix well, I missed to test `List[Option[_]]`.

**Comment by tminglei** [comment]
@Katrix fixed, pls help double check. Thanks!
