### ISSUE TITLE
Weird timezone manipulation when reading OffsetDateTime from timestampz column

### ISSUE THREAD

**Issue by slnowak** [tminglei/slick-pg#493]
I'm using slick-pg to map `column[OffsetDateTime]` to a `timestampz` type in postgres. 
Recently, after daylight saving time change in Poland I realised some of my tests are failing.

Turns out, it's because of this mapper: `PgDateJdbcTypes.GenericDateJdbcType[OffsetDateTime]` (https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/date/PgDateJdbcTypes.scala). 

For some reason, when reading OffsetDateTime from a database, there's a timezone manipulation happening here 
`Option(r.getObject(idx, classOf[OffsetDateTime])).map(t => if (t != OffsetDateTime.MAX && t != OffsetDateTime.MIN) t.atZoneSameInstant(TimeZone.getDefault.toZoneId).toOffsetDateTime else t)`
which basically forces the timezone to the jvm's one. 

May I ask why? Is it a bug? These 2 dates are of course equivalent, but it seems really weird to perform such an optimisation - I'd expect to get back exactly what I've written to the database.

**Comment by tminglei** [comment]
@slnowak  well, this should be a bug. I'll change it to `ZoneOffset.UTC`, which is consistent with `setValue(..)`.

**Comment by slnowak** [comment]
@tminglei But this will still result in a potentially different timezone when re-reading it from the database, right?

**Comment by tminglei** [comment]
@slnowak sorry for the misunderstanding.
I double checked, and here's some founds:
1. the logic was introduced by #355
2. the jdbc driver can't return back the time zone, here's the related codes
```java
// in `org.postgresql.jdbc.PgResultSet#getOffsetDateTime(..)`
      if (oid == Oid.TIMESTAMPTZ || oid == Oid.TIMESTAMP) {
        return connection.getTimestampUtils().toOffsetDateTimeBin(thisRow.get(col));
      } else if (oid == Oid.TIMETZ) {
...

// in `org.postgresql.jdbc.TimestampUtils#toOffsetDateTimeBin(..)`
  public java.time.OffsetDateTime toOffsetDateTimeBin(byte[] bytes) throws PSQLException {
    ParsedBinaryTimestamp parsedTimestamp = this.toProlepticParsedTimestampBin(bytes);
    if (parsedTimestamp.infinity == Infinity.POSITIVE) {
      return java.time.OffsetDateTime.MAX;
    } else if (parsedTimestamp.infinity == Infinity.NEGATIVE) {
      return java.time.OffsetDateTime.MIN;
    }

    // hardcode utc because the backend does not provide us the timezone
    // Postgres is always UTC
    java.time.Instant instant = java.time.Instant.ofEpochSecond(parsedTimestamp.millis / 1000L, parsedTimestamp.nanos);
    return java.time.OffsetDateTime.ofInstant(instant, java.time.ZoneOffset.UTC);
  }
```

So **the timezone can't be restored**. I'll rollback the changes.

**Comment by slnowak** [comment]
@tminglei Oh, I understand now - so postgres always stores timestampz in UTC? Does it mean if I want to preserve the original Timezone I should store it in a separate column?

**Comment by tminglei** [comment]
@slnowak it seems yes.
