### ISSUE TITLE
hstore's +> should return Option[String] instead of String

### ISSUE THREAD

**Issue by luksow** [tminglei/slick-pg#494]
PG's `->` op can return a `NULL` if key is not present in the hstore, hence I think +> should return `Option[String]` to mimick this functionality.

**Comment by tminglei** [comment]
But we should cover a case `Option(hstore) -> 'a'`, which should return `Option[String]` here.

**Comment by luksow** [comment]
@tminglei would that be a problem when both return `Option[String]`. From the SQL point of view you won't know if you get NULL because column was null or key was not present in hstore. So I think both should return `Option[String]`.

**Comment by tminglei** [comment]
@luksow well, I don't think `NULL`'s so bad. And I don't want to break many codes because of it.

**Comment by luksow** [comment]
I have nothing against `NULL`s but I think we're missing proper handling in `slick-pg`. See this example:

``` sql
CREATE EXTENSION HSTORE;

CREATE TABLE problem(
	id SERIAL,
	nonoptional HSTORE NOT NULL,
	optional HSTORE
);

INSERT INTO problem VALUES (1, '', NULL);

SELECT nonoptional->('a') FROM problem WHERE id = 1;
SELECT nonoptional->('a') FROM problem WHERE id = 2;
SELECT optional->('a') FROM problem WHERE id = 1;
```

First `SELECT` yields `NULL`, second yields empty set, third yields `NULL`. In slick-pg the first one will cause an exception, the second one empty set, the third one Option[String] - that's big inconsistency and a surprise factor. Moreover, if you want to avoid exception, you have to perform two queries, which is not good. If you want to avoid breaking any codebases, maybe it's a good idea to release a fixed `+>` operator (ex. `++>`) that simply returns `Option[String]` for both `Map[String, String]` and `Option[Map[String, String]]`.

**Comment by tminglei** [comment]
Well, I didn't find it will cause an exception. I'll check it.

**Comment by tminglei** [comment]
@luksow I recognized I wrongly looked it as a `json` related issue. [Facepalm]
Resolved, pls help double check.

**Comment by luksow** [comment]
LGTM, great, thanks!
