### ISSUE TITLE
Non-uniform isEmpty behaviour

### ISSUE THREAD

**Issue by Shyrff** [tminglei/slick-pg#498]
Ordinary isEmpty is translated to is null, which has binary logic.
For geomenry it is translated to ST_IsEmpty, which has ternary logic. To get binary responce one has to use isEmpty twice.
Even if it seems to be intended behaviour, it is extremely frustrating to have different logical behavior for the same operator.

**Comment by tminglei** [comment]
Well, maybe we should change it to **`IsEmpty`**, to distinguish it from the built-in **`isEmpty`**.
