### ISSUE TITLE
Using with static sql

### ISSUE THREAD

**Issue by plamb** [tminglei/slick-pg#51]
I probably just missed it, is there a way to use the converters with a static sql query? The documentation shows using a GetResult[T] method that reads the values from the result using methods like nextInt, nextString, etc.

http://slick.typesafe.com/doc/2.0.1/sql.html

I have several rather nasty, handwritten queries we use with postgis that return some geometry or json.

**Comment by tminglei** [comment]
Changes released in latest `slick-pg` v0.8.0.
