### ISSUE TITLE
Release for 3.4.0-M1?

### ISSUE THREAD

**Issue by nafg** [tminglei/slick-pg#514]
Hi, I've published 3.4.0-M1. Do you plan to provide a release of slick-pg for prereleases? If not I could figure out a different solution for testing.

P.S. Do you have interest in merging slick-pg into https://github.com/slick/slick and helping maintain it?

**Comment by tminglei** [comment]
Hi @nafg, I'll find time to release a version for slick `3.4.0-M1`. 
And it will be great if slick-pg could be merged into slick and maintained, since I'm afraid I didn't have enough time to maintain it for long time.

**Comment by nafg** [comment]
Well, Slick itself is lacking in maintenance manpower. I'm not offering to
maintain it. But if you merge it in after 3.4.0 is released, perhaps
whatever resources there are can be applied more efficiently

**Comment by tminglei** [comment]
Yes, it's better choice to merge it into slick and maintain them together. Let's do it.

**Comment by tminglei** [comment]
Yes, it's better choice to merge it into slick and maintain them together. Let's do it.

**Comment by nafg** [comment]
Ok I added you as a maintainer. I don't know what approach you want to take, if you want you can keep it as separate modules like now and add it to the repo so it's built and published together, or you can integrate it more tightly. Maybe start with the first way and later it can evolve.

Should we do it for Slick 3.4.0 (we only released M1 so far so it could potentially be in M2 and on)?

**Comment by nafg** [comment]
Hi, will you be releasing it soon?

**Comment by tminglei** [comment]
@nafg released `v0.21.0-M1`, which upgrade to slick `3.4.0-M1`.

**Comment by nafg** [comment]
Thank you!
