### ISSUE TITLE
slick-pg optimized code generator for slick

### ISSUE THREAD

**Issue by diwa** [tminglei/slick-pg#58]
One of the major features in slick 2.x is the [code generator](http://slick.typesafe.com/doc/2.0.1/code-generation.html) which can introspect the database schema and generate all the slick table boilerplate. This code generation can also be customized.

It will be great if slick-pg can offer a customized version of this generator which can generate all the right datatypes like RANGE, POINT etc.

**Comment by Voltir** [comment]
Ive been using CustomizedCodeGenerator.scala as an example, and I found that this conversion doesnt appear to work: 

 case "java.sql.Timestamp" => "org.joda.time.LocalDateTime"

As far as I can tell, the mapped column implicit isnt in scope although I cannot for the life of me figure out why. I was able to get "int4range" => "Range[4]" to work however.

**Comment by guizmaii** [comment]
Is there any progression about this issue ?

**Comment by tminglei** [comment]
@guizmaii it already can be used, but some more customization is still necessary.

_Pls check the [demo](https://github.com/tminglei/slick-pg/tree/master/examples/codegen-customization) project for more details._
