### ISSUE TITLE
Filter on nested json

### ISSUE THREAD

**Issue by levinotik** [tminglei/slick-pg#69]
I'm pretty new to the postgres json operators and to slick-pg (which is awesome, btw). I'm wondering if there's a way to do a query based on some nested json object. For example, given:

{"a":101,"b":"aaa","foo":{"bar":true},"c":[3,4,5,9]} 

is there a way to filter for all rows where foo.bar == true?

Thanks a lot!

**Comment by exp0nge** [comment]
I know this is a old thread but I wanted to post this to make it a complete answer:
`{"a":101,"b":"aaa","foo":{"bar":true},"c":[3,4,5,9]}`

To get `foo.bar == true` you can do:

`(_.yourJsonField +> "foo" +>> "bar" === your-comparison)` The mappings posted above helps. The `+>` maintains the result as JSON until you want to compare it as text on "bar"
