### ISSUE TITLE
How to map a geometric Path column 

### ISSUE THREAD

**Issue by Fraer** [tminglei/slick-pg#692]
Hello,

Given a column typed as geometric `path` in my postgres db (no postgis), what would be the preferable way to map it with slick-pg?

Native postgres path type definition: https://www.postgresql.org/docs/current/datatype-geometric.html#DATATYPE-GEOMETRIC-PATHS
JDBC postgres japth type definition: https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/geometric/PGpath.html

Would it be enough to use a MultiPoint mapping defined in `slick-pg_jts` or `slick-pg_jts_lt`?

**Comment by tminglei** [comment]
Hi @Fraer  there isn't built-in support for pg `path` in `slick-pg`. MultiPoint mapping defined in `slick-pg_jts` or `slick-pg_jts_lt` is not fit for this. Maybe you need define mapping for it by yourself.
