### ISSUE TITLE
Slick 3.5.0 and Akka 2.6.x compatibility problem

### ISSUE THREAD

**Issue by maxcom** [tminglei/slick-pg#705]
I found that I can't update from slick 3.4.1 to 3.5.0 due to this:

```
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.scala-lang.modules:scala-parser-combinators_2.13:2.3.0 (early-semver) is selected over {1.1.2}
[error] 	    +- com.github.tminglei:slick-pg_play-json_2.13:0.22.0 (depends on 2.3.0)
[error] 	    +- com.github.tminglei:slick-pg_core_2.13:0.22.0      (depends on 2.3.0)
[error] 	    +- com.github.tminglei:slick-pg_2.13:0.22.0           (depends on 2.3.0)
[error] 	    +- com.typesafe:ssl-config-core_2.13:0.4.3            (depends on 1.1.2)
[error] 
```

`ssl-config-core` dependency comes from akka-streams 2.6.21, and `scala-parser-combinators` 2.3.0 is required by `slick-pg`.

**Comment by fcv** [comment]
maybe a regression ?
it looks like https://github.com/tminglei/slick-pg/issues/586.

**Comment by reibitto** [comment]
I encountered basically the same situation upgrading to 3.5.0, except with Play:

```
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error]         * org.scala-lang.modules:scala-parser-combinators_2.13:2.3.0 (early-semver) is selected over {1.1.2}
[error]             +- com.github.tminglei:slick-pg_play-json_2.13:0.22.0 (depends on 2.3.0)
[error]             +- com.github.tminglei:slick-pg_core_2.13:0.22.0      (depends on 2.3.0)
[error]             +- com.github.tminglei:slick-pg_2.13:0.22.0           (depends on 2.3.0)
[error]             +- org.playframework:play_2.13:3.0.2                  (depends on 1.1.2)
[error]             +- org.playframework:cachecontrol_2.13:3.0.0          (depends on 1.1.2)
```

**Comment by jcazevedo** [comment]
Can we follow what was done in #587 and rollback to 1.1.2 on Scala 2.x? I have opened #707 to propose that.

**Comment by reibitto** [comment]
Thanks! I can confirm #707 fixed the issue for me and all tests pass.

**Comment by mkurz** [comment]
> I encountered basically the same situation upgrading to 3.5.0, except with Play:
> 
> ```
> [error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
> [error]
> [error]         * org.scala-lang.modules:scala-parser-combinators_2.13:2.3.0 (early-semver) is selected over {1.1.2}
> [error]             +- com.github.tminglei:slick-pg_play-json_2.13:0.22.0 (depends on 2.3.0)
> [error]             +- com.github.tminglei:slick-pg_core_2.13:0.22.0      (depends on 2.3.0)
> [error]             +- com.github.tminglei:slick-pg_2.13:0.22.0           (depends on 2.3.0)
> [error]             +- org.playframework:play_2.13:3.0.2                  (depends on 1.1.2)
> [error]             +- org.playframework:cachecontrol_2.13:3.0.0          (depends on 1.1.2)
> ```

For next (major) Play release we will very likely upgrade scala-parser-combinators to v2 for Scala 2.13+ (but keep v1 for 2.12, which for us only affects the play sbt plugins). You can follow:
- https://github.com/playframework/playframework/issues/13179

(if no show stoppers come up)
