### ISSUE TITLE
Is there a way to support Java 8+ for Slick 3.5.0

### ISSUE THREAD

**Issue by jim-mccabe** [tminglei/slick-pg#708]
I see in the release notes for [slick-pg v0.22.0](https://github.com/tminglei/slick-pg/releases/tag/v0.22.0) that it requires Java 11+.

Is there any way to still work with Java 8?

I noticed in the march up to the Slick 3.5.0 release, they initially dropped support for 8 and later restored it, since there are so many people still using it (even with Scala 3).

**Comment by tminglei** [comment]
@jim-mccabe it's ok for `slick-pg` itself and most of the addons, except `play-json` addon, which requires `java 11+`.
Ok, let's restore the java 8 support.

**Comment by tminglei** [comment]
@jim-mccabe released v0.22.1, which restored java 8 support. 
Pls check it.

**Comment by jim-mccabe** [comment]
Thank you!!
